### ISSUE TITLE
Do we have prepared statements and do we cache them?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#10]
Do we have prepared statements and do we cache them?

Can we add a page in docs explaining this?

**Comment by frederikhors** [comment]
I just found out this on docs:

> It might be a good idea to disable prepared statements in pgx for performance reasons:

Why?

**Comment by frederikhors** [comment]
Here it says the opposite: https://github.com/jackc/pgx#performance

**Comment by vmihailenco** [comment]
>Prepared statements have the largest performance advantage when a single session is being used to execute a large number of similar statements. The performance difference will be particularly significant if the statements are complex to plan or rewrite, for example, if the query involves a join of many tables or requires the application of several rules. If the statement is relatively simple to plan and rewrite but relatively expensive to execute, the performance advantage of prepared statements will be less noticeable.

I don't have much to add.

**Comment by vmihailenco** [comment]
"if you disable it goes faster" reflects my understanding accurately, but either way the performance difference is not big.

>Instead, reading the PG docs I understand that if them are activated DON'T necessarily decrease performances, even in the simplest cases.

Prepared statements may improve performance if you prepare a statement once and then use it multiple times. But what really happens in practice is more like
- prepare a statement
- use the statement
- reset the session
- repeat

**Comment by frederikhors** [comment]
Oh wow.

This makes me understand the amount of lack of knowledge that I already felt I had.

> reset the session

Can you add a page in the docs that explains well how a DB connection works using Bun?

_Today there are so many things to learn and it is often very convenient to copy code from the "Getting started" page without really understanding what you are doing._

I ask you only a few lines (even schematic) that I can then also improve with PR.

Or maybe we can link to some guides that explain well how the connection to a db between Golang, Bun (or others) and Postgres works.

Please, we newbies need it!

**Comment by vmihailenco** [comment]
I try to update docs on a regular basis, but I don't think that this is kind of information that new users should worry about. Even for experienced users my advice is to not waste your time on prepared statements (with Postgres). No matter what database client you are using. There is nothing bad with it, but it is a premature optimization and there are better ways to speedup your queries (batching).

So I don't see the point in writing an article about prepared statements that in the end says "don't use prepared statements". Most users already don't.
