### ISSUE TITLE
Is it possible to support the default mapping of go type `string` to PostgreSQL type `text` when using postgresql?

### ISSUE THREAD

**Issue by danclive** [uptrace/bun#101]
As the question, I am switching from `pg` to `bun` and found that it is different here.

**Comment by danclive** [comment]
For example, add 2 lines to this function：

https://github.com/uptrace/bun/blob/280e5ec349c474c8293abbc0063e0d5dcddaa7f9/dialect/pgdialect/sqltype.go#L74

```go
func sqlType(typ reflect.Type) string {
	switch typ {
	case ipType:
		return pgTypeInet
	case ipNetType:
		return pgTypeCidr
	case jsonRawMessageType:
		return pgTypeJSONB
	}

	sqlType := schema.DiscoverSQLType(typ)
	switch sqlType {
	case sqltype.Timestamp:
		sqlType = pgTypeTimestampTz
	}

	switch typ.Kind() {
	case reflect.Map, reflect.Struct:
		if sqlType == sqltype.VarChar {
			return pgTypeJSONB
		}
		return sqlType
	case reflect.Array, reflect.Slice:
		if typ.Elem().Kind() == reflect.Uint8 {
			return pgTypeBytea
		}
		return pgTypeJSONB
+	case reflect.String:
+		return pgTypeText
	}

	return sqlType
}

```

**Comment by vmihailenco** [comment]
It looks like there is no [difference](https://stackoverflow.com/questions/4848964/difference-between-text-and-varchar-character-varying) between `varchar` and `text`. And we try to not introduce dialect-specific changes that don't bring any practical benefits.

**Comment by danclive** [comment]
OK! thanks!
