### ISSUE TITLE
NullZero if set for field if it is marked as PK

### ISSUE THREAD

**Issue by cbitensky** [uptrace/bun#102]
I need an uint32 field as part of primary key. And I need to have ability to write value 0. I can’t. 
```
func (f *Field) markAsPK() {
	f.IsPK = true
	f.NotNull = true
	f.NullZero = true
}
```

**Comment by vmihailenco** [comment]
I guess it is best to remove `f.NullZero = true` so we don't end up with another tag to undo it, .e.g. `usezero` for go-pg... `f.NotNull` probably should be removed too, because NULLs in primary keys have their usage too...
