### ISSUE TITLE
How to disable logging for specific queries?

### ISSUE THREAD

**Issue by qtt153759** [uptrace/bun#1020]
Hi, I currently want to disable logging of some specific queries, while still enabling the others. However, it seems that bun currently only supports two modes: logging all or only logging failed queries

Example according to document: https://bun.uptrace.dev/guide/debugging.html
```
db.AddQueryHook(
	bundebug.NewQueryHook(
		bundebug.WithEnabled(true),
		bundebug.WithVerbose(true),
	),
)
```
 It would be great if bun supported this feature in detail down to the specific query. If anyone has a solution to this problem, please share it with me, thanks.

**Comment by Ashique-1010** [comment]
Are there any updates on this ?
