### ISSUE TITLE
Copy slice of bytes from driver

### ISSUE THREAD

**Issue by bnonce** [uptrace/bun#1030]
Bun version: v1.2.3

We must make a copy [here](https://github.com/uptrace/bun/blob/760de7d0fad15dc761475670a4dde056aef9210d/model_map.go#L85) ​​taking into account the [doc](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L451).

Now select is broken and can return invalid data.

**Comment by vmihailenco** [comment]
@bnonce could you prepare a PR?

**Comment by bnonce** [comment]
@vmihailenco yep. [pr](https://github.com/uptrace/bun/pull/1031)
