### ISSUE TITLE
[Request] Add multiple DB endpoints for reader/writer

### ISSUE THREAD

**Issue by reesmanp** [uptrace/bun#1037]
I know that ProxySQL exists but it would be nice to be able to give Bun a writer endpoint and 0+ reader endpoints and have it decide which connection to use. I know this is an extension of the usecase of Bun but it still would be great to have, even as a hook or part of pgdriver's config.

**Comment by vmihailenco** [comment]
I think the first version can be quite simple:

```go
db := bun.NewDB(sqldb, dialect, bun.WithReadOnlyDB(db2))
```

And then use the `db2` when calling `db.NewSelect`.
