### ISSUE TITLE
NewInsert can't override default true boolean

### ISSUE THREAD

**Issue by JustNZ** [uptrace/bun#1041]
bun is part of my API Backend which accepts incoming json data and uses this data for db actions (insert,update,delete,..).

One of my endpoints is responsible to create new things. The schema looks as following:
```
type Projects struct {
	bun.BaseModel `bun:"table:projects"`

	ID                           uuid.UUID `bun:",pk,type:uuid,default:gen_random_uuid()" json:"id"`
	Name                     string    `bun:"name,type:text,notnull" json:"name"`
	Description           string    `bun:"description,type:text,default:''" json:"description"`
	Runners                 bool      `bun:"runners,type:bool,default:true" json:"runners"`
	Color                      string    `bun:"color,type:text,default:''" json:"color"`
	Icon                        string    `bun:"icon,type:text,default:''" json:"icon"`
	Disabled                bool      `bun:"disabled,type:bool,default:false" json:"disabled"`
	DisabledReason   string    `bun:"disabled_reason,type:text,default:''" json:"disabled_reason"`
	CreatedAt             time.Time `bun:"created_at,type:timestamptz,default:now()" json:"created_at"`
}
```

And my code as below:
```
var project models.Projects
if err := context.ShouldBindJSON(&project); err != nil {
	httperror.StatusBadRequest(context, "Error parsing incoming data", err)
	return
}

_, err = db.NewInsert().Model(&project).Column("id", "name", "description", "runners", "icon", "color").Exec(context)
if err != nil {
	log.Error(err)
	httperror.InternalServerError(context, "Error creating project on db", err)
	return
}
```

Now I got the problem that **Runners** can't be set to false - no matter what I try.
Even with `project.Runners = false` above the insert it is still set to true on the DB.

Some things I discovered:
- NewUpdate and NewRaw is not affected by the problem.
- having an `default:false` will allow you to set the value to true on insert

I tried every version above 1.1.17 but all result in the same issue

**Comment by j2gg0s** [comment]
false is the zero value of bool in Go.
When you set runners to false during insertion, the ORM cannot distinguish that you’ve explicitly set this value.
Therefore, the ORM will use the default value when the field has a zero value.

You can:
- use zero value as field's default
- or change filed's type to ptr, so its default is nil
- or add a temporary update operation

**Comment by JustNZ** [comment]
thanks for the reply and answer on that. I will give it a try and think we can close the issue then
