### ISSUE TITLE
Connection read buffer and connection's re-usage

### ISSUE THREAD

**Issue by inaneverb** [uptrace/bun#1047]
It's not an issue, rather some questions for better understanding how things are works.

Let's assume I instantiated Postgres DB handle with setting connections limit to 10. Then I made a request of 100k rows, handling them successfully. That conn was using some internal buffer to store these 100k, I presume, that:
- is large than default one (some number of re-allocations + copy ops); Btw what is the default size of read buffer?
- is keep being occupied by this conn for some amount of time (for how much?)

So, how can I manage with these parameters? Can I even do this? 

I mean, let's say these 100k records requires 100mb of RAM to be represented in binary pg format. Is it true that if I'd do 10 such queries each with different conn (in occasion), then I could have 1gb RAM consumed for some amount of time (larger than amount of time required to process these queries)? If so then:
- for how long? 
- is it completely regulated by GC or there are some rules I may expect and can rely on? Something like guarantee that this large buffer will ever be replaced by the smaller one?

I assume, I can get these answers by spending hours reading the sources, but I am finding this information rather critical and it could be great if such information could be reflected somewhere in docs.

**Comment by j2gg0s** [comment]
Most databases use TCP, and the default read buffer is generally between 8KB and 128KB. When the read buffer is slow, I assume the connection will get blocked and wait.

Bun is an ORM and does not directly manage these underlying details. It loads all the data into memory at once. The raw data is released after func return, waiting for the GC. [scan](https://github.com/uptrace/bun/blob/master/query_base.go#L567)

Therefore, avoid loading too much data from the database at once, for example, more than 10k rows.
