### ISSUE TITLE
Bug: Issue with PGDialect in Bun v1.2.6

### ISSUE THREAD

**Issue by Clemintina** [uptrace/bun#1078]
Hello, 

After upgrading to `github.com/uptrace/bun v1.2.6`, I encountered the following error:

`Cannot use pgdialect. New() (type *Dialect) as the type schema. Dialect Type does not implement schema. Dialect as some methods are missing: DefaultSchema() string`

This issue appears to be related to the latest version of pgdialect with Bun v1.2.6. When downgrading to v1.2.5, the error is resolved, indicating the bug was introduced in v1.2.6.

```
github.com/uptrace/bun  v1.2.6
github.com/uptrace/bun/dialect/pgdialect  v1.2.6
github.com/uptrace/bun/driver/pgdriver v1.2.6
```

**How to reproduce**

1. Initialise a Go project with bun and pgdialect v1.2.6.
2. Attempt to use pgdialect.New() as the dialect type for Bun's NewDB function.
3. Encounter the following error message:
`Cannot use pgdialect. New() (type *Dialect) as the type schema. Dialect Type does not implement schema. Dialect as some methods are missing: DefaultSchema() string`

My Environment:

OS: MacOS Sequoia 15.1.1
GoLang: 1.23.1
Bun: 1.2.6
PGDialect: 1.2.6

**Comment by j2gg0s** [comment]
- dialect implement this method [sqltype.go#L57](https://github.com/uptrace/bun/blob/v1.2.6/dialect/pgdialect/sqltype.go#L57)
- and we have type assert [dialect.go#L33](https://github.com/uptrace/bun/blob/v1.2.6/dialect/pgdialect/dialect.go#L33)

Could you check the version of pgdialect? If you upgraded bun to v1.2.6 but didn’t upgrade dialect, this issue might occur.

**Comment by Tiscs** [comment]
I've tried to reproduce the issue, but it works fine.

```
module github.com/uptrace/bun/dialect/pgdialect

go 1.23.3

...

require (
	...
        github.com/uptrace/bun v1.2.6
	github.com/uptrace/bun/dialect/pgdialect v1.2.6
	github.com/uptrace/bun/driver/pgdriver v1.2.6
      ...
)
...
```

``` go
package pgdialect_test

import (
	"testing"

	"github.com/uptrace/bun/dialect/pgdialect"
	"github.com/uptrace/bun/schema"
)

func TestNewPgDB(t *testing.T) {
	var dialect schema.Dialect = pgdialect.New()
	if dialect.DefaultSchema() != "public" {
		t.Fatalf("dialect.DefaultSchema() failed: %v", dialect.DefaultSchema())
	}
}

```

**Comment by Clemintina** [comment]
Hello,

After further investigation and testing using the IDE `Zed`, it appears the issue was related to the IntelliJ GoLand plugin.
The plugin falsely flags the dialects as incompatible, even though they are functioning perfectly fine in practise.

Apologies for the confusion, and thank you for your time.

**Comment by renxzen** [comment]
in my case i was getting this error with sqlite.
As @j2gg0s mentioned, i had to upgrade the dialect to 1.2.6

Problem was solved
