### ISSUE TITLE
How to use Bulk() with NewUpdate() ?

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#129]
I am unable to make work the `Bulk()` function. There is no example in docs. Can you please tell me if it's possible to use `Bulk()` to bulk update without manually creating CTE?

**Comment by imraan-go** [comment]
```golang
OrderStages := []OrderStage{}
_, err = database.DB.NewUpdate().
		Model(&OrderStages).
		Bulk().
		Exec(ctx)
```

I was able to make it work but this updates all the columns. Is it possible to update specific column with bulk?

**Comment by vmihailenco** [comment]
See https://bun.uptrace.dev/guide/queries.html#update - there is an example how to update multiple books.

**Comment by imraan-go** [comment]
Thanks. works perfectly fine.

**Comment by imraan-go** [comment]
Why did you close this issue? Were you not able to reproduce this issue?

**Comment by vmihailenco** [comment]
@imraan-go you've changed the message :) Anyway, this should work in 1.0.0-rc.3 - please try.

**Comment by imraan-go** [comment]
> @imraan-go you've changed the message :) Anyway, this should now work in 1.0.0-rc.3 - please try.

I am not able to use this version. `go get -u` does not update bun. https://pkg.go.dev/github.com/uptrace/bun shows latest version is `0.4.3`

**Comment by vmihailenco** [comment]
Try

```
go mod edit -require github.com/uptrace/bun@1.0.0-rc.3
```

**Comment by imraan-go** [comment]
`go: errors parsing go.mod:
go.mod:10:2: require github.com/uptrace/bun: version "1.0.0-rc.3" invalid: unknown revision 1.0.0-rc.3`

**Comment by vmihailenco** [comment]
I've missed `v` in the version

```
go mod edit -require github.com/uptrace/bun@v1.0.0-rc.3
```

**Comment by imraan-go** [comment]
Thanks, It works perfectly fine.
