### ISSUE TITLE
Can Bun create tables if I don't know how to?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#13]
With go-pg I was using this code:

```go
func main() {
	opts := &orm.CreateTableOptions{
		IfNotExists:   true,
		FKConstraints: true,
	}

	tables := []interface{}{
		(*Team)(nil),
		(*Player)(nil),
		(*User)(nil),
		(*Invoice)(nil),
		(*Address)(nil),
		(*Tax)(nil),
		(*Service)(nil),
		(*Setting)(nil),
	}

	for _, model := range tables {
		err := db.Model(model).CreateTable(opts)
		// if err...
	}
}
```

and this was quite awesome (especially if you don't know how to create such tables in Postgres or SQLite)!

**Is this possible with Bun?**

**Comment by merefield** [comment]
Yes, see [migrations](https://bun.uptrace.dev/guide/migrations.html)

Your `for` loop can look something like:
```
for _, model := range models {
	_, err := db.NewDropTable().Model(model).IfExists().Exec(ctx)
	if err != nil {
		panic(err)
	}

	_, err = db.NewCreateTable().Model(model).Exec(ctx)
	if err != nil {
		panic(err)
	}
}
```

**Comment by vmihailenco** [comment]
See also https://github.com/uptrace/bun/blob/master/db.go#L116-L126 and [fixtures](https://bun.uptrace.dev/guide/fixtures.html)

**Comment by frederikhors** [comment]
Ok please don't close. I will close it in a few hours.

**Comment by frederikhors** [comment]
I didn't know `NewCreateTable()` because it's not in [migrations](https://bun.uptrace.dev/guide/migrations.html) but in fixtures.

I think we should add it in https://bun.uptrace.dev/guide/pg-migration.html#migrating-from-go-pg.

But what scares me is that with `go-pg` I was able to write this:

```go
type Model struct {
	ID        int
	CreatedAt time.Time `pg:"default:now(),notnull"`
	UpdatedAt *time.Time
}

type Tenant struct {
	Description string
}

type BaseModel struct {
	Model

	TenantID int     `pg:",pk"`
	Tenant   *Tenant `pg:"rel:has-one"`
}

type Player struct {
	BaseModel

	Name string
	Teams []Team
}

type Team struct {
	BaseModel

	Name     string
	PlayerID int
}
```

and event if I don't know Postgresql syntax I can have multi primary keys (`TenantID` and `ID`) tables and other "advanced" features which I don't know how to write in PSQL.

Is this the same with Bun?

If I use that structs with the below code it doesn't create the same tables of go-pg:

```go
models := []interface{}{
  (*Tenant)(nil),
  (*Player)(nil),
  (*Team)(nil),
}

myDB.RegisterModel(models...)

fixture := dbfixture.New(myDB, dbfixture.WithRecreateTables())

if err := fixture.Load(context.Background(), os.DirFS("./fixture"), "fixture.yml"); err != nil {
  panic(err)
}
```

- fixture.yml:

```yml
- model: Player
- model: Team
```

**Comment by merefield** [comment]
> I didn't know `NewCreateTable()` because it's not in [migrations](https://bun.uptrace.dev/guide/migrations.html) but in fixtures.

I picked it up from the migration guide:

https://bun.uptrace.dev/guide/pg-migration.html#new-features

**Comment by vmihailenco** [comment]
>Is this the same with Bun?

AFAIR the only thing that Bun does not support is foreign keys. But go-pg only supported fks for has-one relation which was confusing. With Bun you need to use `ForeignKey` method - https://bun.uptrace.dev/guide/queries.html#creating-tables
