### ISSUE TITLE
Intercept internal logs

### ISSUE THREAD

**Issue by NathanBaulch** [uptrace/bun#131]
In go-pg I used `pg.SetLogger` to integrate with my logging system. It doesn't look like this is possible in bun based on what I'm seeing in `/internal/logger.go`. Is there a recommended approach?

**Comment by vmihailenco** [comment]
I've sent https://github.com/uptrace/bun/pull/133 but it looks like `internal.Logger` is unused right now. I've seen requests asking for ability to overwrite `Warn` and `Deprecated`, but it is not clear how API should look like.
