### ISSUE TITLE
Foreign key constraint errors are ignored when inserting row with Slice index

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#136]
Postgresql DDL:

```sql
CREATE TABLE "order_items" (
  "id" int4 NOT NULL DEFAULT nextval('order_items_id_seq'::regclass),
  "order_id" int8 NOT NULL,
  "sku" text COLLATE "pg_catalog"."default" NOT NULL,

  CONSTRAINT "order_items_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "order_items_fk" FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED
)
;
```
Bun definitions:
```golang
type OrderItem struct {
bun.BaseModel      `bun:"order_items"`
	ID                 int      `json:"id"`
	OrderID            int      `json:"order_id"`
	Sku                string   `json:"sku"`
}
```

Code: 
```golang

// Initiate Orderitems with invalid order_id
items := []OrderItem{
		OrderItem{
			BaseModel: schema.BaseModel{},
			ID:        0,
			OrderID:   0,
			Sku:       "",
		},
		OrderItem{
			BaseModel: schema.BaseModel{},
			ID:        0,
			OrderID:   0,
			Sku:       "",
		},
	}
// This does not produce error and row is not inserted
row, err  := database.DB.NewInsert().
		Model(&items[0]).
		Exec(ctx)
	if err != nil {
panic(err)
}


// This produces error as expected!
row, err  := database.DB.NewInsert().
		Model(&items).
		Exec(ctx)
	if err != nil {
panic(err)
}
```

Here `OrderItem.ID = 0` is an invalid foreign key. When using index of a slice in `NewInsert()` , row is not inserted and errors are ignore for some reason. But using slice produces errors as expected. 

Also is there anyway to override a column with `NewInsert()` method similiar to `ColumnExpr` ? Like in the above example, if we want to set `OrderID` to `22` we have to iterate all items like so:

```
for i := range items {
		items[i].ID = 22
	}
```

Instead we could do something like this:

```
row, err  := database.DB.NewInsert().
		Model(&items).
ColumnExpr("order_id", 22).
		Exec(ctx)
	if err != nil {
panic(err)
}
```

So it will override the column `order_id` when inserting rows.

**Comment by vmihailenco** [comment]
First make sure to upgrade to v1.0.0

Then we have a test for this - see https://github.com/uptrace/bun/blob/master/internal/dbtest/db_test.go#L641-L682. Please provide something similar that I can run (or make an existing test fail).

>Instead we could do something like this:

You can try

```go
row, err  := database.DB.NewInsert().
		Model(&items).
                Value("order_id", 22).
		Exec(ctx)
	if err != nil {
panic(err)
}
```

**Comment by imraan-go** [comment]
> First make sure to upgrade to v1.0.0
> 
> Then we have a test for this - see https://github.com/uptrace/bun/blob/master/internal/dbtest/db_test.go#L641-L682. Please provide something similar that I can run (or make an existing test fail).

`v1.0.0` fixed the issue with the `DEFERRABLE INITIALLY DEFERRED`.


> 
> > Instead we could do something like this:
> 
> You can try
> 
> ```go
> row, err  := database.DB.NewInsert().
> 		Model(&items).
>                 Value("order_id", 22).
> 		Exec(ctx)
> 	if err != nil {
> panic(err)
> }
> ```
Value accepts string only. I think It should be interface{} like `Where()`. So it's not necessary to to convert int to string.

**Comment by imraan-go** [comment]
Also, there is no way to use expression when using `Value()` method. From bun example [https://bun.uptrace.dev/guide/models.html#null-and-default](https://bun.uptrace.dev/guide/models.html#null-and-default) , how to update `updated_at` column  with SQL expression CURRENT_TIMESTAMP() ?
```golang
type User struct {
	CreatedAt time.Time `bun:",nullzero,notnull,default:current_timestamp"`
	UpdatedAt bun.NullTime
}

row, err  := database.DB.NewInsert().
		Model(&User).
                Value("updated_at", CURRENT_TIMESTAMP). //Not possible
		Exec(ctx)
	if err != nil {
panic(err)
}
```

I think Value should behave more like `Set` which can accept arbitrary values and expression.
