### ISSUE TITLE
Unable to select relation field

### ISSUE THREAD

**Issue by NathanBaulch** [uptrace/bun#139]
I'm getting incorrect SQL when trying to select relation fields using the `apply` func argument due to missing table aliases.

```go
db.NewSelect().Model((&model.Session{})).
	Relation("User",
		func(q *bun.SelectQuery) *bun.SelectQuery {
			return q.Column("name")
		}).
	Scan(ctx))
```

I found that changing 
```go
if field, ok := q.table.FieldMap[col.Query]; ok {
```
on [line 585 of query_select.go](https://github.com/uptrace/bun/blob/f6610a2a314161db49e4fe737f14c93975b38928/query_select.go#L585) to
```go
if field, ok := join.JoinModel.Table().FieldMap[col.Query]; ok {
```
seems to fix the problem. Bug or am I missing something?

**Comment by vmihailenco** [comment]
Looks like a bug and the suggested fix looks correct :+1:
