### ISSUE TITLE
TCP error on idle connection

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#141]
After the connection idles for few hours, the first few request fails with TCP error:

`write tcp 192.168.3.4:65383->3.1.14.XXX:5432: write: broken pipe`

This is the code i'm using on startup of my application:

```golang
dsn := fmt.Sprintf("postgres://%v:%s@%v:5432/%v?sslmode=disable", dbconfig.Get("dbuser").(string), url.QueryEscape(dbconfig.Get("dbpass").(string)), dbconfig.Get("dbhost").(string), dbconfig.Get("dbname").(string))
	sqldb := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(dsn)))

	if err != nil {
		log.Fatal(err)
	}
	err = sqldb.Ping()
	if err != nil {
		log.Fatal(err)
	}

	db := bun.NewDB(sqldb, pgdialect.New())
	db.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose()))

```

I didn't have that issue with lib/pq  driver before.

**Comment by imraan-go** [comment]
The fix should be similar to this: https://github.com/lib/pq/pull/1013

**Comment by vmihailenco** [comment]
Thanks for bringing this :+1:
