### ISSUE TITLE
Selecting nested relations

### ISSUE THREAD

**Issue by NathanBaulch** [uptrace/bun#149]
This select query returns all columns for Child and Parent as expected:

```go
pdb.NewSelect().Model(&model.Child{ID: 123}).
	WherePK().
	Relation("Parent").Scan(ctx)
```

However if I try to join another level I only get back Child fields (no Parent and no Grandparent):

```go
pdb.NewSelect().Model(&model.Child{ID: 123}).
	WherePK().
	Relation("Parent", func(q *bun.SelectQuery) *bun.SelectQuery {
		return q.Relation("Grandparent")
	}).Scan(ctx)
```

This used to be really easy in go-pg with `Relation("Parent.Grandparent")` so I'm hoping this is still possible.

**Comment by vmihailenco** [comment]
Can you try:

```go
pdb.NewSelect().Model(&model.Child{ID: 123}).
	WherePK().
	Relation("Parent").
	Relation("Parent.Grandparent").
	Scan(ctx)
```

**Comment by NathanBaulch** [comment]
Thanks, I thought I tried that but somehow missed it.
I'll leave it to you to decide if my nested relation apply func pattern should be supported.
