### ISSUE TITLE
Only select columns from nested relation

### ISSUE THREAD

**Issue by NathanBaulch** [uptrace/bun#150]
I'm trying to port a query from go-pg that only selects columns from a nested parent. Is this still possible now that the special "_" placeholder isn't supported? Using `ExcludeColumn("*")` seems to drop all columns including those from relations.

```go
pdb.Model(&model.Child{ID: 123}).
	WherePK().
	Column("_").
	Relation("Parent._").
	Relation("Parent.Grandparent").
	Select()
```

I initially assumed `ExcludeColumn("*")` was equivalent to `Column("_")` and would be scoped to the current query level but the following returns zero columns:

```go
pdb.NewSelect().Model(&model.Child{ID: 123}).
	WherePK().
	ExcludeColumn("*").
	Relation("Parent", func(q *bun.SelectQuery) *bun.SelectQuery { return q.ExcludeColumn("*") }).
	Relation("Parent.Grandparent").
	Scan(ctx)
```

**Comment by vmihailenco** [comment]
Seems to be working as expected - https://github.com/uptrace/bun/blob/master/internal/dbtest/orm_test.go#L284-L341

It will not work for has-many and m2m relations, but it is not a bug - just how those relations are working. go-pg should handle this the same.

**Comment by NathanBaulch** [comment]
Thanks, not sure where I went wrong on this one.
