### ISSUE TITLE
returning does not work properly with Bulk()

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#151]
The following code does not return the data from the table. It returns data from the CTE
```golang
database.DB.NewUpdate().
		Model(&OrderItem).
		ExcludeColumn("order_id", "created_at").
		Value("updated_at", "CURRENT_TIMESTAMP").
		Bulk().
		Returning("*").
		Exec(ctx)
```

Instead the following works properly. 
```golang
database.DB.NewUpdate().
		Model(&OrderItem).
		ExcludeColumn("order_id", "created_at").
		Value("updated_at", "CURRENT_TIMESTAMP").
		Bulk().
		Returning("order_item.*").
		Exec(ctx)
```

This is not a problem with Bun. Thats how postgres works. Do you think the second solution should be the default behavior for Bun as it makes sense?  Also, `time.Time`  type is always treated as `timestamptz` in SQL query. But I want this to be `timestamp`. How to enforce this behavior?

**Comment by vmihailenco** [comment]
>Do you think the second solution should be the default behavior for Bun as it makes sense?

Perhaps, but Bun does not rewrite the SQL provided by the user because it is too complex and fragile.

>Also, time.Time type is always treated as timestamptz in SQL query. But I want this to be timestamp.

You can change the SQL type via tag fields: `type:timestamp`.

**Comment by vmihailenco** [comment]
See [bulk-update](https://bun.uptrace.dev/guide/query-update.html#bulk-update) and [timestamptz vs timestamp](https://bun.uptrace.dev/postgres/data-types.html#timestamptz-vs-timestamp)
