### ISSUE TITLE
ColumnExpr with Relation queries

### ISSUE THREAD

**Issue by YeemBoi** [uptrace/bun#155]
Hi,
I've been looking for functionality similar to `ColumnExpr()` that will select into the right field when used in a Relation query.
Although it's a different module, [go-pg's Issue #1852 ](https://github.com/go-pg/pg/issues/1852) describes this exact problem.

This could, perhaps, be addressed be implementing a function similar to `*InsertQuery.Value(column string, expr string, args ...interface{})`, so that the name of the column could be taken as a separate argument. Then, maybe it could be handled similar to the way #139 addressed this?

See [this gist](https://gist.github.com/YeemBoi/d96fd023b9ad114fb6b89b8047d63387) for a clearer example.
Any help would be much appreciated.

**Comment by vmihailenco** [comment]
Can you try:

```go
func AlsoAnInvalidRelationQuery(q *bun.SelectQuery) *bun.SelectQuery {
	return q.ColumnExpr("? AS author__name", "Ronald")
}
```

**Comment by YeemBoi** [comment]
Sorry for your time, the issue was that the `Relation()` apply func was being used in different joins (with different prefixes / aliases)...

The solution is to pass the prefix / alias (eg `"author__"`) to a parent func

```go
func GetRelationQuery(joinPrefix string) func(*bun.SelectQuery) *bun.SelectQuery {
	return func(q *bun.SelectQuery) *bun.SelectQuery {
		return q.ColumnExpr("? AS ?", "Ronald", bun.Ident(joinPrefix+"name"))
	}
}
````
