### ISSUE TITLE
Scan into array of structs (that contain Postgres arrays)?

### ISSUE THREAD

**Issue by lalotai** [uptrace/bun#156]
Having some trouble (`1.0.2`) scanning into array of structs that have Postgres arrays inside.

Struct exampe:

```golang
type Position struct {
	bun.BaseModel `bun:"positions,alias:positions"`

	DB         *bun.DB        `json:"-" bun:"-"`
	PositionID int64          `json:"-" bun:"position_id,pk"`
	Categories *[]int32       `json:"categories,omitempty" bun:"categories,array"`
	Status     *common.Status `json:"status,omitempty" bun:"status"`
	UpdatedAt  time.Time      `json:"-" bun:",nullzero,default:null"`
	CreatedAt  time.Time      `json:"-" bun:",nullzero,notnull,default:current_timestamp"`
}
```

Selecting using:

```golang
var positions []Position
err := p.DB.NewSelect().
		ColumnExpr("*").
		Model(&positions).
		Where("status IN (?)", bun.In(statuses)).
		Offset((page - 1) * pageSize).
		Limit(pageSize).
		Scan(ctx)
```

For some reason gives me something like this:

```bash
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type({0x0, 0x0, 0xc0000ca130})
	/usr/local/go/src/reflect/value.go:2249 +0x12e
github.com/uptrace/bun/dialect/pgdialect.arrayScanner.func1({0x1908700, 0xc0003fe350, 0xc0003fe320}, {0x191dfa0, 0xc000198138})

...
```

I'm assuming the problem is with the way I use Postgres arrays, because the select works with other simpler structures. Am I missing some tags somewhere or not selecting correctly?

I've checked out https://bun.uptrace.dev/postgres/arrays.html that has an example of selecting only Postgres arrays, but still not sure what I'm doing wrong. Apologies if missing something basic.

---

**Edit:** Also tried `json:"categories,omitempty" bun:"categories,type:integer[],array"` tag with no luck.

**Comment by vmihailenco** [comment]
Slice pointers like `*[]int32` were not supported. https://github.com/uptrace/bun/pull/157 should fix this.

**Comment by lalotai** [comment]
Ah, that explains it. Thank you!
