### ISSUE TITLE
Error checking when creating new db with invalid DSN?

### ISSUE THREAD

**Issue by merefield** [uptrace/bun#16]
If my DSN is, for example, the string `"bogus"`, this will not generate an error:
```
	sqldb, err := sql.Open("pgx", cnf.Database.PSN)
```

This is exacerbated by this not returning an error attribute:
```
  db := bun.NewDB(sqldb, pgdialect.New())
```

Should the connection be tested at this point and return an error if it's an erroneous PSN?

I can force a health query at this stage in setup, but should we need to?  e.g.:

```
_, err = db.Exec("SELECT 1=1")
```

**Comment by vmihailenco** [comment]
>I can force a health query at this stage in setup, but should we need to? e.g.:

Yes, you should if that is what you want. database/sql, pgx, and Bun seem to agree that DSN should not be validated until you issue a query. That makes if there are no any queries.

Also you can use `db.Ping` instead of `SELECT 1`.
