### ISSUE TITLE
Bulk soft deletes

### ISSUE THREAD

**Issue by NathanBaulch** [uptrace/bun#160]
I'm getting the "bun: to bulk Update, use CTE and VALUES" error when executing a delete query with a slice model.
I'm familiar with the `UpdateQuery.Bulk` func but what about soft deletes?

```go
sessions := []model.Session{{ID: 1}, {ID: 2}, {ID: 3}}
_, err := pdb.NewDelete().Model(&sessions).WherePK().Exec(ctx)
```

**Comment by vmihailenco** [comment]
Thanks for the report - this is an overlook.
