### ISSUE TITLE
How to use bunotel? 

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#163]
i've setup bunotel with this:
```golang
db := bun.NewDB(sqldb, pgdialect.New())
	db.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose()))
	db.AddQueryHook(bunotel.NewQueryHook())
```

However bun does not create child span with the following code.
```golang
tracer := opentracing.GlobalTracer()
	spanCtx, _ := tracer.Extract(
		opentracing.HTTPHeaders,
		opentracing.HTTPHeadersCarrier(c.Request().Header),
	)

	span := tracer.StartSpan("get API", ext.RPCServerOption(spanCtx))
	defer span.Finish()
	orders := []Orders{}
	ctx := opentracing.ContextWithSpan(context.Background(), span)
	err := database.DB.NewSelect().
		Model(& orders).
		Scan(ctx)

```

Am i missing something?

**Comment by vmihailenco** [comment]
`bunotel` is for OpenTelemetry, but you are using opentracing. In theory, there is a bridge between opentracing and opentelemetry, but I doubt it is in a good shape (did not try though!).

I will add an example for bunotel, but meanwhile you can check [go-pg](https://github.com/uptrace/uptrace-go/tree/master/example/go-pg) or [grpc](https://github.com/uptrace/uptrace-go/tree/master/example/grpc) examples.

**Comment by imraan-go** [comment]
> `bunotel` is for OpenTelemetry, but you are using opentracing. In theory, there is a bridge between opentracing and opentelemetry, but I doubt it is in a good shape (did not try though!).
> 
> I will add an example for bunotel, but meanwhile you can check [go-pg](https://github.com/uptrace/uptrace-go/tree/master/example/go-pg) or [grpc](https://github.com/uptrace/uptrace-go/tree/master/example/grpc) examples.

@vmihailenco  Yes you are right! Using OpenTelemetry works. However, bun uses empty span name. I think it would be nice to have a span name with context to operation. For `db.NewSelect()` span name could be `Bun: SELECT` . In that way, we can find all db calls easily with jaeger UI. Otherwise, there is just an empty field in Jaeger  operation listing:

<img width="361" alt="Screen Shot 2021-09-08 at 7 05 20 PM" src="https://user-images.githubusercontent.com/66571123/132514897-5997b553-d1c5-499d-b7cf-1f5eb84bd0be.png">

**Comment by imraan-go** [comment]
In otel.go Line 40  
```golang
 ctx, _ = tracer.Start(ctx, "")
```
There should be an appropiate name.

**Comment by vmihailenco** [comment]
@imraan-go yep, I've sent https://github.com/uptrace/bun/pull/171/files. The backend I am using generates a short version of the query and uses it as a span name so that's why I have not noticed...

**Comment by imraan-go** [comment]
> @imraan-go yep, I've sent https://github.com/uptrace/bun/pull/171/files. The backend I am using generates a short version of the query and uses it as a span name so that's why I have not noticed...

Thanks, now span name works is set based on operation. Do you think "Bun" keyword should be prefixed on the span name to make it standout if there are lots of different operations? Or make it user configurable to add a prefix/suffix ?

**Comment by vmihailenco** [comment]
I did not see any instrumentations doing this... so I guess it should be an option.
