### ISSUE TITLE
OnConflict Without Set

### ISSUE THREAD

**Issue by chriskolenko** [uptrace/bun#164]
Just migrating my codebase from go-pg however the OnConflict functionality is different.

https://bun.uptrace.dev/guide/pg-migration.html#other-changes

`Replace q.OnConflict("(column) DO UPDATE") with q.On("CONFLICT (column) DO UPDATE")` looks like SET needs to be provided. 

Will there be support for On Conflict without SET?

**Comment by vmihailenco** [comment]
I don't follow. Can you provide an example of the Bun query and the desired SQL?

**Comment by chriskolenko** [comment]
```
	_, err := s.db.NewInsert().
		Model(entity).
		On("CONFLICT (id) DO UPDATE").
		Exec(ctx)
```

**Comment by vmihailenco** [comment]
Yes, that makes sense - should be fixed soon. Thanks for the report.

**Comment by chriskolenko** [comment]
Can confirm this works 100%.

**Comment by edalford11** [comment]
Quick note here, the default SET fields being added appear to ignore the `bun:",skipupdate"` tag on the model definitions. I would think we'd want it to honor that tag.
