### ISSUE TITLE
MariaDB support?

### ISSUE THREAD

**Issue by YeemBoi** [uptrace/bun#166]
#33 mentions the main problem I'm having: bun is using `AS` aliases in `DELETE` statements

Output of `SELECT VERSION()`: `10.4.14-MariaDB-1:10.4.14+maria~eoan`

Driver: `github.com/go-sql-driver/mysql`
Dialect: `dialect/mysql`

**Comment by vmihailenco** [comment]
MariaDB should be fully supported and tested now.
