### ISSUE TITLE
TIMEZONE issue with version before mysql 8.0

### ISSUE THREAD

**Issue by shawn246** [uptrace/bun#168]
[https://github.com/uptrace/bun/blob/57ab844745cfc84bd902250ffd6042fe907f3fe9/dialect/append.go#L97](https://github.com/uptrace/bun/blob/57ab844745cfc84bd902250ffd6042fe907f3fe9/dialect/append.go#L97)

test mysql version: 5.7.*

time.Time is converted to a time string(in UTC without timezone) in AppendTime function, while mysql will consider this time string as the local time of the timezone set in the connection session. For ‘timestamp’ columns, mysql will convert this time string to UTC time again. 

So, if original time is '2021-09-08T12:00:00+08:00', it becomes to '2021-09-08 04:00:00' after sql building, then it becomes to '2021-09-07T20:00:00+00:00' in db if the session timezone is '+08:00'.

In my view, bun should convert time.Time according to the session timezone.

**Comment by vmihailenco** [comment]
As a workaround, you can set server timezone to UTC.

**Comment by shawn246** [comment]
What's the schedule for the bug?

**Comment by vmihailenco** [comment]
I though about fixing this for v1.1 in 1-2 weeks because there is a workaround. Is this critical for you?

**Comment by shawn246** [comment]
OK for me:)

**Comment by choyri** [comment]
This problem also bothered me, looking forward to the new version 😄

**Comment by vmihailenco** [comment]
It looks like MySQL driver allows to change the MySQL timezone - see https://github.com/go-sql-driver/mysql#loc . Alternatively, you can set Go timezone to match MySQL timezone.

As for Bun, it should stop appending time in UTC.

**Comment by choyri** [comment]
@vmihailenco When will v1.1 be released? 👀️

**Comment by vmihailenco** [comment]
I will release 1.0.10 today.

**Comment by choyri** [comment]
@vmihailenco I think the problem is still unsolved 😢

![image](https://user-images.githubusercontent.com/13994362/135998025-142484da-164e-4f50-9d90-ba4c7dbffe53.png)

**Comment by vmihailenco** [comment]
Indeed, should be fixed by https://github.com/uptrace/bun/pull/236/files

**Comment by GreenHatHG** [comment]
In the appendTime method of pgdialect, the UTC()method is also called. Don't you need to synchronize this? @vmihailenco

**Comment by vmihailenco** [comment]
@vmihailenco no, AFAIR PostgreSQL needs UTC to work correctly. We can reconsider it if there are any issues with that.

**Comment by GreenHatHG** [comment]
> @vmihailenco no, AFAIR PostgreSQL needs UTC to work correctly. We can reconsider it if there are any issues with that.

Do you mean to configure the timezone when reading?
Some front-end pages directly displayed by connecting to the database do not support the configuration of timezone, but directly display the values in the database.
