### ISSUE TITLE
bundebug color output is hard to read in dark terminals

### ISSUE THREAD

**Issue by wavded** [uptrace/bun#174]
<img width="334" alt="Screen Shot 2021-09-09 at 7 59 34 AM" src="https://user-images.githubusercontent.com/26638/132690258-d6d8494e-2920-4dba-8bab-e4c85ab4fa0d.png">

Is it possible to disable the color or set a foreground color to see this better?

**Comment by vmihailenco** [comment]
I use a dark theme and that is not what I see. Let's try https://github.com/uptrace/bun/pull/176 - it sets foreground colors.
