### ISSUE TITLE
ExcludeColumn(columns ...string) *InsertQuery

### ISSUE THREAD

**Issue by oiime** [uptrace/bun#18]
Hello, I was trying to exclude some columns from an insert query and noticed that method is not supported, Would it make sense to add it? excludeColumns already exists in baseQuery

**Comment by vmihailenco** [comment]
Yes, it makes sense to have `ExcludeColumn` on `InsertQuery`. Please send a PR if you have a chance.

**Comment by vmihailenco** [comment]
Closed by https://github.com/uptrace/bun/pull/19
