### ISSUE TITLE
Model migration issue from go-pg to bun

### ISSUE THREAD

**Issue by wavded** [uptrace/bun#180]
Given this simplified example, I have a model:

```go
type Token struct {
	ID           int
	CompanyID    int       `bun:"-" json:"company_id"`
}
```

And this query:

```go
rows, err := db.QueryContext(ctx, `
SELECT t.id, u.company_id
  FROM tokens t
  LEFT JOIN users u ON t.user_id = u.id
  WHERE t.id = ?`, id)

err = m.DB.ScanRows(ctx, rows, token)
```

I get an error of:

```
Scan error on column index 8, name \"company_id\": bun: Token does not have column \"company_id\""
```

In go-pg, I was able to parse columns that didn't exist in the database to a struct.  Did this change or what is the recommended way to do that now?  Thank you.

**Comment by metalrex100** [comment]
@wavded it seems that `ScanRows` method is just a wrapper over `database/sql` [Rows.Scan()](https://pkg.go.dev/database/sql#Rows.Scan) method: https://github.com/uptrace/bun/blob/master/model_scan.go#L29

So probably it does not take `bun` tags into account.

According to the docs you should write your select query with `db.NewSelect()` method:
```
err := db.NewSelect().Model(&user).Where("id = 1").Scan(ctx)
```

https://bun.uptrace.dev/guide/queries.html#scan-and-exec

**Comment by vmihailenco** [comment]
You should use `bun:",scanonly"` instead of `bun:"-"`:

```
type Token struct {
	ID           int
	CompanyID    int       `bun:",scanonly" json:"company_id"`
}
```

I will document this.

**Comment by vmihailenco** [comment]
The migration guide should be updated.

**Comment by wavded** [comment]
Thanks @vmihailenco !

**Comment by wavded** [comment]
@vmihailenco Just FYI, that option isn't documented here, seems like it should: https://bun.uptrace.dev/guide/models.html#struct-tags

**Comment by vmihailenco** [comment]
@wavded thanks, will update.
