### ISSUE TITLE
Pointer fields in model

### ISSUE THREAD

**Issue by skayred** [uptrace/bun#181]
Hello!

I have recently started to migrate to Bun from go-pg,  and I faced an issue with my models that look like  that:

```
type User struct {
	bun.BaseModel `bun:"users"`

	ID       *int    `json:"id" bun:"id,pk,nullzero"`
	Login    *string `json:"login" bun:"login"`
	Email    *string `json:"email" bun:"email"`
	Password *string `bun:"password"`
}
```

When I try to create new User, I get that error:

```reflect: call of reflect.Value.Int on ptr Value```

Reason why I need all those pointers in a model is that I use `gqlgen`, and pointers are used to distinguish 0, value, and Null.
Same model definition did work with go-pg, how can I make it work with Bun?

**Comment by vmihailenco** [comment]
Thanks for the report. This should be fixed by https://github.com/uptrace/bun/pull/185, but I am not sure you can use NULL values in primary keys. I guess you want `0` instead of `NULL` for the primary key:

```go
type User struct {
	bun.BaseModel `bun:"users"`

	ID       *int    `json:"id" bun:",allowzero,default:0"`
}
```
