### ISSUE TITLE
Documentation: Connection clarification?

### ISSUE THREAD

**Issue by lalotai** [uptrace/bun#182]
[Getting started](https://bun.uptrace.dev/guide/getting-started.html) section mentions how to connect. It would be nice to clarify some of the following info, esp since other similar libs mention it in one form or another:

1. Do we need to worry about deferring closing connections? (I assume not since it's not mentioned)
2. Does `pgdialect` use pooling? (If yes: is there anything to configure, if no: why not?)
3. Anything special to tweak for production env?

I ask because I'm currently using Postgres+pgdialect and I don't know if I'm setup correctly going into prod. I see there was some talk [here](https://github.com/uptrace/bun/issues/14), but it'd be awesome if it was briefly mentioned in the docs too.

PS: this lib is awesome.

**Comment by vmihailenco** [comment]
Thanks for the feedback. I've tried to answer your questions in https://bun.uptrace.dev/postgres/running-bun-in-production.html#database-sql

>PS: this lib is awesome.

Thanks!

**Comment by lalotai** [comment]
Thank you @vmihailenco, this is exactly what I was looking for :pray:

**Comment by jianmaikj** [comment]
> Thanks for the feedback. I've tried to answer your questions in https://bun.uptrace.dev/postgres/running-bun-in-production.html#database-sql
> 
> > PS: this lib is awesome.
> 
> Thanks!

Got 404, where can I see it

**Comment by bogab** [comment]
You can find it here: https://bun.uptrace.dev/guide/running-bun-in-production.html
