### ISSUE TITLE
'unique' fields being put into unique groups when they shouldn't be

### ISSUE THREAD

**Issue by tsmethurst** [uptrace/bun#183]
Hi bun devs!

Seeing a spicy issue with unique tags not behaving as they should.

A struct has the following fields:

```go
	ID                                string             `validate:"required,ulid" bun:"type:CHAR(26),pk,nullzero,notnull,unique"`
	CreatedAt                time.Time     `validate:"-" bun:"type:timestamp,nullzero,notnull,default:current_timestamp"`
	UpdatedAt               time.Time     `validate:"-" bun:"type:timestamp,nullzero,notnull,default:current_timestamp"`
	URI                              string             `validate:"required,url" bun:",unique,nullzero,notnull"`
```

When we were using go-pg, the ID and URI fields were constrained correctly in the database as having to be unique on their own. Now with bun when I inspect the constraints on my Postgres database I see the following:

![Screenshot from 2021-09-10 09-42-00](https://user-images.githubusercontent.com/31960611/132819162-ab88db68-896d-432c-a296-fbd328c2c3c2.png)

Without me defining it, the id and uri fields have been put in a unique group. This is causing all sorts of problems in our application logic, because we rely on ID and URI being unique *separately*. Is there a fix for this?

Thanks!

**Comment by vmihailenco** [comment]
This is a bug - thanks for the report.

**Comment by tsmethurst** [comment]
Thanks for the very quick fix!
