### ISSUE TITLE
Does it have such a great abstraction as orm.DB interface?

### ISSUE THREAD

**Issue by MetalRex101** [uptrace/bun#184]
One of the reasons i prefer go-pg is orm.DB interface out of the box, which gives enough abstraction to build you queries without specifying concrete connection type pg.DB or pg.TX. Does bun have something similar?

**Comment by vmihailenco** [comment]
Yes, see https://pkg.go.dev/github.com/uptrace/bun#IConn and https://github.com/uptrace/bun/tree/master/example/tx-composition
