### ISSUE TITLE
SelectOrInsert method?

### ISSUE THREAD

**Issue by metalrex100** [uptrace/bun#186]
In pg-go there was a method `SelectOrInsert`. The migration guide does not contain any info about deletion of this method. Does it exist in Bun?

If not - any chance you will add it in near future?

**Comment by vmihailenco** [comment]
It does not exist in Bun, because it seems to be obsoleted since PostgreSQL added support for upserts. Nowadays you  should just use `INSERT ON CONFLICT DO UPDATE`. Let me know if that works for you and I will update the migration guide.

We may add something like `SelectOrInsert` in future but we need to understand
1. what task does it solve that you can't achieve with upserts
2. it should work for mysql and sqlite

**Comment by metalrex100** [comment]
@vmihailenco thanks for the fast response!
If no update needed I thing workaround for `SelectOrInsert` method will be:
```
res, err := conn.NewInsert().Model(entity).Where("name = ?", name).On("CONFLICT DO NOTHING").Returning("*").Exec(ctx)
```

So actually no need in separate `SelectOrInsert` method since it will break backward compatibility with other database drivers.

**Comment by vmihailenco** [comment]
:+1: I will mention this in the migration guide.

**Comment by metalrex100** [comment]
@vmihailenco such solution is not working, because it is illegal to specify `WHERE` clause in INSERT queries. The error will be: `ERROR #42601 syntax error at or near "WHERE"`.

Also Bun automatically adds WHERE `table.deleted_at IS NULL` to insert query for models with `soft_delete` field if `On("CONFLICT DO NOTHING")` specified.

By this I want to say that seems like currently it is impossible to make SelectOrInsert query with `On` method.
Probably `On("CONFLICT UPDATE")` will also not work for models with `soft_delete` field.

**Comment by vmihailenco** [comment]
It is hard to guess why you need `where`, but you can use a second `SELECT` query if needed.

**Comment by metalrex100** [comment]
Bun will add where clause automatically for models with "soft_delete" field.

**Comment by tpoxa** [comment]
But if I want to select by using non-PK, such insert won't be conflicting.

**Comment by tpoxa** [comment]
Also no chance to select sth with Relation in case if record exists.

**Comment by vmihailenco** [comment]
>But if I want to select by using non-PK, such insert won't be conflicting.

It is not safe to insert by a non-unique index. You will have duplicate rows in the database.

>Also no chance to select sth with Relation in case if record exists.

Inserts don't support `Relation` so `SelectOrInsert` will produce very different results depending on db state.
