### ISSUE TITLE
Postgres DSN issue on AWS+Docker

### ISSUE THREAD

**Issue by lalotai** [uptrace/bun#189]
On my localhost, Postgres DSN in this format works great:

`postgres://postgres:password@localhost:5432/test?sslmode=disable`

On AWS inside docker, it tries to connect to AWS RDS via something like this:

`postgres://postgres:password@app.xxx.us-east-1.rds.amazonaws.com:5432/test?sslmode=disable`

But gives the following error:

`dial tcp 127.0.0.1:5432: connect: connection refused`

I'm guessing it doesn't know how to lookup the IP of that endpoint? I seem to remember [other](https://stackoverflow.com/a/62436959) libs wrapping the endpoint in `tcp()`, making it look something like this:

`postgres://postgres:password@tcp(app.xxx.us-east-1.rds.amazonaws.com:5432)/test?sslmode=disable`

But then it gives the following error:

`panic: parse "postgres://postgres:password@tcp(app.xxx.us-east-1.rds.amazonaws.com:5432)/test?sslmode=disable"`

What is the proper way to connect in this example (without setting an IP address)?

(sorry to be bombarding with some Github issues lately)

**Comment by vmihailenco** [comment]
>I'm guessing it doesn't know how to lookup the IP of that endpoint?

It looks like it tries to connect to `127.0.0.1:5432`. Are you sure that your app uses the correct DSN? It does not look so.

>I seem to remember other libs wrapping the endpoint in tcp(), making it look something like this:

This is not needed with pgdriver.

**Comment by lalotai** [comment]
@vmihailenco Thanks for taking the time. Just now did a sanity check -- yes, definitely sure.

It's a static string that's hardcoded and pointing to `app.xxx.us-east-1.rds.amazonaws.com:5432`. Tried 2 diff ones: one has a `tcp()` wrapped around it, which gives the parse error, and the other is just the above endpoint, which somehow translates to localhost (not sure if Docker is failing a lookup so it defaults to localhost or if bun/pgdriver is doing that..?).

**Comment by vmihailenco** [comment]
>(not sure if Docker is failing a lookup so it defaults to localhost or if bun/pgdriver is doing that..?).

pgdriver does not do anything special with the hostname - it is just passed to dial. Looks like Docker resolves app.xxx.us-east-1.rds.amazonaws.com to 127.0.0.1.

To rule out pgdriver, you can try pgx - https://bun.uptrace.dev/guide/drivers.html#pgx

**Comment by lalotai** [comment]
Hmm. Before I try pgx (I've had a few issues with gorm using it + simpleprotocol), is it possible somehow to allow parsing of `tcp(*)` syntax here: https://github.com/uptrace/bun/blob/master/driver/pgdriver/config.go#L156 ?

Since, bun uses pgdriver internally, I'm not sure how I could try that on my end. Any ideas?

**Comment by vmihailenco** [comment]
>is it possible somehow to allow parsing of tcp(*) syntax here

It is possible, but does not make much sense - TCP is the default.

>Since, bun uses pgdriver internally, I'm not sure how I could try that on my end. Any ideas?

Bun does not use pgdriver internally - you use the driver when creating sql.DB. See the link I've provided how to work with pgx.

**Comment by imraan-go** [comment]
> On my localhost, Postgres DSN in this format works great:
> 
> `postgres://postgres:password@localhost:5432/test?sslmode=disable`
> 
> On AWS inside docker, it tries to connect to AWS RDS via something like this:
> 
> `postgres://postgres:password@app.xxx.us-east-1.rds.amazonaws.com:5432/test?sslmode=disable`
> 
> But gives the following error:
> 
> `dial tcp 127.0.0.1:5432: connect: connection refused`
> 
> I'm guessing it doesn't know how to lookup the IP of that endpoint? I seem to remember [other](https://stackoverflow.com/a/62436959) libs wrapping the endpoint in `tcp()`, making it look something like this:
> 
> `postgres://postgres:password@tcp(app.xxx.us-east-1.rds.amazonaws.com:5432)/test?sslmode=disable`
> 
> But then it gives the following error:
> 
> `panic: parse "postgres://postgres:password@tcp(app.xxx.us-east-1.rds.amazonaws.com:5432)/test?sslmode=disable"`
> 
> What is the proper way to connect in this example (without setting an IP address)?
> 
> (sorry to be bombarding with some Github issues lately)

Did you try pinging that hostname from docker container? I think the problem is with docker configuration not Bun!

**Comment by lalotai** [comment]
Ok, I took a break to re-evaluate all.

**tl&dr:** I messed something up in my infra. I still don't know what. It's definitely not bun.

---

How I got it to work is by switching from RDS Postgres db, to RDS Aurora Postgres-compatible version. Same security group, same VPC, same everything else I can think of. And yet, Aurora+Postgres version is reachable via Docker, and Postgres version is not. Again, I don't know enough to understand why one is reachable and other is not. I can reach both versions via CLI on EC2, I just can't reach the Postgres one via Docker.

If you (future reader) knows whatsup, please comment.

---

@vmihailenco I'm sorry for wasting your time, I know it's valuable. Thank you for the suggestions.

@imraan-go You're right, definitely not Bun!
