### ISSUE TITLE
Missing Exists() method

### ISSUE THREAD

**Issue by metalrex100** [uptrace/bun#191]
Go-pg had `Exists()` method.
According to its [implementation](https://github.com/go-pg/pg/blob/v10/orm/query.go#L1300) it was just a sugar to check if given select query returns rows:

```
func (q *Query) Exists() (bool, error) {
	q = q.Clone() // copy to not change original query
	q.columns = []QueryAppender{SafeQuery("1")}
	q.order = nil
	q.limit = 1
	res, err := q.db.ExecContext(q.ctx, NewSelectQuery(q))
	if err != nil {
		return false, err
	}
	return res.RowsAffected() > 0, nil
}
```

Seems like it can be implemented in `Bun` since it does not related to specific DB driver. What do you think?

**Comment by metalrex100** [comment]
I may suggest PR for `Exists()` method

**Comment by vmihailenco** [comment]
I omitted this method because there is no `Query.Clone` in Bun which is nice I think. Let me try to add proper `EXISTS (?)` helper method.
