### ISSUE TITLE
Alternative to pg.PoolStats?

### ISSUE THREAD

**Issue by metalrex100** [uptrace/bun#193]
What is the alternative for the `pg.PoolStats` struct, method in `Bun`?

https://github.com/go-pg/pg/blob/v10/base.go#L27

**Comment by vmihailenco** [comment]
Bun does not have a pool and uses sql.DB. See https://pkg.go.dev/database/sql#DBStats

**Comment by metalrex100** [comment]
Got it, thanks. May be makes sense to also add this info to go-pg -> bun migration guide.

**Comment by vmihailenco** [comment]
:+1: will do
