### ISSUE TITLE
Postgres `DATE` type change from go-pg

### ISSUE THREAD

**Issue by wavded** [uptrace/bun#196]
`go-pg` would convert `date` type to a `string` which was more ideal IMO.  `bun` converts it to a UTC `time.Time` with the time portion zeroed out.  Is there a way to override that behavior so you can use a `string` instead or would you consider switching back to a `string` value in that case?

**Comment by wavded** [comment]
It seems the mysql driver prefers `string` as well for `DATE` by default, but allows an opt-in for `time.Time` parsing -> https://github.com/go-sql-driver/mysql#parsetime

Maybe an option like this makes sense?

**Comment by vmihailenco** [comment]
Do you mean scanning `time.Time` (date) into a string? Please show some code.

**Comment by wavded** [comment]
This model definition worked in go-pg:

```
DLExp   string   `pg:"type:date"`
```

This no longer works in `bun`:

```
DLExp   string   `bun:"type:date"`
```

As I get an error:

```
sql: Scan error on column index 22, name \"dl_exp\": bun: can't scan time.Time{wall:0x0, ext:63762768000, loc:(*time.Location)(nil)} into string
```

This is due to the `date` type being scanned in as a `time.Time` instead of a `string`.

`go-pg` would scan `date` in as a string, per this code:

https://github.com/go-pg/pg/blob/v10/types/column.go#L103

The pgdriver within `bun` now scans it in as a `time.Time`:

https://github.com/uptrace/bun/blob/master/driver/pgdriver/column.go#L53

**Comment by vmihailenco** [comment]
Looks like we should improve Bun to scan time.Time into a string :+1: 

>https://github.com/go-pg/pg/blob/v10/types/column.go#L103

True, but this code is only used to scan into a `map[string]interface{}`.

**Comment by wavded** [comment]
Thx @vmihailenco for the quick turnaround!
