### ISSUE TITLE
Bulk update error for model with `soft_delete` field

### ISSUE THREAD

**Issue by metalrex100** [uptrace/bun#199]
I'm trying to make bulk update query (with specified columns) for model with `soft_delete` field (named `deleted_at`).
The query ends-up with following error:
```
ERROR #42702 column reference \"deleted_at\" is ambiguous
```
Query:
```
tx.NewUpdate().Model(&sliceOfModels).Column("col1", "col2").WherePK().Bulk().Exec(context.TODO())
```
Updated model does not have relations, all fields are primitives (uuid, time, bool, string, int, float64)

I see in resulting query part 
```
AND "deleted_at" IS NULL
```

Probably need to add table prefix to avoid collisions between `_data` columns and table columns:
```
AND tableAlias."deleted_at" IS NULL
```

I don't know if same situation may occur with part:
```
AND "id" IN (...)
```
but may be it makes sense to also add there table prefix.

**Comment by imraan-go** [comment]
What is the query produced by bun? Please enable Bundebug to print the raw query. And you are right, bun added column without table alias. So SQL server got confused with table column and  CTE columns.

**Comment by metalrex100** [comment]
Sorry, can't share query, since it's production code under NDA.
