### ISSUE TITLE
Logrus logging

### ISSUE THREAD

**Issue by oiime** [uptrace/bun#20]
I've added a small package that provides a hook to enable logging with logrus, Is it implemented correctly? I've based it on how the logging is done internally: https://github.com/oiime/logrusbun

**Comment by vmihailenco** [comment]
Looks pretty good :+1: What do you think about adding a link with brief description to https://github.com/go-bun/bun-docs/blob/master/docs/guide/tracing.md ?

**Comment by oiime** [comment]
Ok, https://github.com/go-bun/bun-docs/pull/2

**Comment by vmihailenco** [comment]
:+1:
