### ISSUE TITLE
Delete query on model with `soft_delete` field throws panic

### ISSUE THREAD

**Issue by metalrex100** [uptrace/bun#204]
The panic occurs in method `updateSoftDeleteField` of the `structTableModel` struct. For some reason `m.strct` param has a nil pointer. I did not investigate it further.

**Comment by vmihailenco** [comment]
Please show the stacktrace and the model.

**Comment by metalrex100** [comment]
The model:
```
type AliasToGroup struct {
	bun.BaseModel `bun:"entity_subtype_aliases_to_alias_group,alias:estatag"`

	Id        uuid.UUID `bun:"type:uuid,default:uuid_generate_v4(),pk"`
	AliasId   uuid.UUID `bun:"type:uuid,notnull"`
	GroupId   uuid.UUID `bun:"type:uuid,notnull"`
	CreatedAt time.Time `bun:",nullzero,notnull,default:current_timestamp"`
	DeletedAt time.Time `bun:",soft_delete"`
}
```

**Comment by metalrex100** [comment]
I will provide stacktrace from the part, when RunInTx method called. Some paths details rewritten since project under NDA.
Stacktrace:
```
runtime.gopanic at panic.go:971
reflect.Value.Field at value.go:850
github.com/uptrace/bun/schema.fieldByIndexAlloc at reflect.go:50
github.com/uptrace/bun/schema.(*Field).Value at field.go:51
github.com/uptrace/bun.(*structTableModel).updateSoftDeleteField at model_table_struct.go:219
github.com/uptrace/bun.(*DeleteQuery).AppendQuery at query_delete.go:145
github.com/uptrace/bun.(*DeleteQuery).Exec at query_delete.go:225
db.(*entitySubtypeAliasToGroupRepo).DeleteByAliasId at entity_subtype_alias_to_group_repo.go:94
entity_subtype_alias.(*updater).runUpdateTransaction.func1 at updater.go:92
github.com/uptrace/bun.(*DB).RunInTx at db.go:367
```

**Comment by vmihailenco** [comment]
There is no enough info to reproduce this. Similar code works fine in tests - https://github.com/uptrace/bun/blob/master/internal/dbtest/soft_delete_test.go#L61-L114

**Comment by metalrex100** [comment]
Hum, what if you try to make delete query in `Model((*Model)(nil))`?

**Comment by metalrex100** [comment]
My query is:
```
conn.NewDelete().Model((*pgmodel.AliasToGroup)(nil)).Where("alias_id = ?", alias).Where("group_id in (?)", bun.In(groups.Ids())).Exec(ctx)
```

I guess it is wrong query since I'm trying to perform bulk delete query, but specify single model in `.Model` method.

Probably correct query should be:
```
conn.NewDelete().Model(groups).Where("alias_id = ?", alias).Exec(ctx)
```
or
```
conn.NewDelete().Model(([]pgmodel.AliasToGroup)(nil)).Where("alias_id = ?", alias).Where("group_id in (?)", bun.In(groups.Ids())).Exec(ctx)
```

Will test both.

**Comment by metalrex100** [comment]
The query works fine:
```
conn.NewDelete().Model(&[]pgmodel.AliasToGroup{}).Where("alias_id = ?", alias).Where("group_id in (?)", bun.In(groups.Ids())).Exec(ctx)
```

If it possible - may be make sense to add check for bulk deletes to throw error (instead of panic) if single model ptr specified in `Model` method instead of ptr of models slice.

**Comment by metalrex100** [comment]
Update:
Query also works fine:
```
conn.NewDelete().Model(&pgmodel.AliasToGroup{}).Where("alias_id = ?", alias).Where("group_id IN (?)", bun.In(groups.Ids())).Exec(ctx)
```

So no need to specify slice of models in `Model` method.
Seems like the problem definitely with `NewDelete().Model((*Model)(nil))` approach. For some reason delete query does not allow such way of model specification.
