### ISSUE TITLE
Error on scanning when model does not contain field for existing column in table

### ISSUE THREAD

**Issue by metalrex100** [uptrace/bun#205]
In go-pg there was no error when model did not have some fields for existing columns.
Bun throws error on scan if table has `deleted_at` column, but model does not.

table:
```
create table locks
(
    id         uuid      default uuid_generate_v4(),
    name       varchar                 not null
    timeout_ms integer                 not null,
    created_at timestamp default now() not null,
    deleted_at timestamp
);
```

```
type Lock struct {
	bun.BaseModel `bun:"locks,alias:l"`

	Id         uuid.UUID `bun:"type:uuid,default:uuid_generate_v4(),pk"`
	Name       string    `bun:",notnull"`
	Timeout_ms int       `bun:",notnull"`
	CreatedAt  time.Time `bun:",nullzero,notnull,default:current_timestamp"`
}
```

Is it correct behavior? If so - probably should be described in migration guide.

**Comment by vmihailenco** [comment]
AFAIK the default behavior is the same in go-pg and Bun. In go-pg there was a table-level option called `discard_unknown_columns`, but in Bun it is a global option - https://bun.uptrace.dev/postgres/running-bun-in-production.html#bun-withdiscardunknowncolumns
