### ISSUE TITLE
Bun stores jsonb nil value as string "null" instead of NULL

### ISSUE THREAD

**Issue by metalrex100** [uptrace/bun#206]
I have a model with field:
```
Attributes json.RawMessage `bun:"type:jsonb"`
```
Associated column in table:
```
attributes jsonb default '{}'::jsonb
```
In my table the associated column is nullable, which means that I expect to have NULL in database in case, when `Attributes` field value is nil.

Instead Bun converts nil value to string "null". It breaks the logic of the default value.

In go-pg it worked as expected.

**Comment by vmihailenco** [comment]
There is a test and it seems to be working as expected - https://github.com/uptrace/bun/blob/master/internal/dbtest/query_test.go#L373-L384

**Comment by metalrex100** [comment]
@vmihailenco Am I right that test you provided only checks that it is possible to insert model with `nil` json.RawMessage field?
If so, it is not the case I'm talking about.

Check please my first comment for the details.

**Comment by vmihailenco** [comment]
I don't see additional details in your first message. Anyway, if somehow there is a `"null"` string in `json.RawMessage`, Bun does not have any choice but to store it. I doubt go-pg worked any different.

**Comment by metalrex100** [comment]
@vmihailenco I don't set anything manually to my `json.RawMessage` field. Right before `tx.NewInsert().Model(&stateObj).Exec(ctx)` the field `stateObj.Attributes` (json.RawMessage) is **nil**.

But resulting query for some reason contains not `NULL` value, but `'null'`. So it is Bun the one who transforms `json.RawMessage` field from `nil` to `'null'` instead of `NULL`.

**Comment by vmihailenco** [comment]
Please provide the code that reproduces the problem.

**Comment by metalrex100** [comment]
@vmihailenco I compared how both libraries add value to the query. The problem was in `nullzero` tag.
go-pg set `DEFAULT` value for the column because by default it set `nullzero` tag to each field.

For some reason I thought that `nullzero` tag make sense only for strings, ints, bools.
`json.RawMessage` has a `nil` value by default, but still needs `nullzero` tag if `DEFAULT`/`NULL` value is needed. Otherwise `nil` value will be marshaled to json. Marshal result will be string `'null'`.

Thanks for the help!
