### ISSUE TITLE
[Bug] Unable to save 0 in postgresql

### ISSUE THREAD

**Issue by lonelyevil** [uptrace/bun#207]
Environment:
go version go1.17.1 windows/amd64
bun v1.0.7
PostgreSQL 13.4, compiled by Visual C++ build 1914, 64-bit

Example code:
```go
func main() {
	db := bun.NewDB(....)
	result, err := db.NewInsert().Model(&Temp{ID: 0}).Exec(context.Background())
	if err != nil {
		panic(err)
	}
	fmt.Println(result)
}

type Temp struct {
	ID int64 `bun:",allowzero"`
}
```

SQL schema:
```sql
CREATE TABLE IF NOT EXISTS public.temps
(
    id bigint NOT NULL,
    CONSTRAINT temp_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.temps
    OWNER to postgres;
```

Expected result:
Record successfully inserted.

Actual result:
```
panic: ERROR #23502 null value in column "id" of relation "temps" violates not-null constraint
```

By adding hook, the generated sql query is
```sql
INSERT INTO "temps" ("id") VALUES (DEFAULT) RETURNING "id"
```

Temporary solution:
1. Change this line from
```go
result, err := db.NewInsert().Model(&Temp{ID: 0}).Exec(context.Background())
```
to 
```go
result, err := db.NewInsert().Model(&Temp{ID: 0}).Value("id", "?", 0).Exec(context.Background())
```

or
2. Change SQL schema to
```sql
CREATE TABLE IF NOT EXISTS public.temps
(
    id bigint NOT NULL DEFAULT 0,
    CONSTRAINT temp_pkey PRIMARY KEY (id)
)
```

Also in Select/Delete queries, the 0 in struct passed to Model() is transformed to null. I assume there is some problem in Model().

**Comment by imraan-go** [comment]
I think BUN tries not to generate primary keys by itself. Usually primary keys are autogenerated by DBMS. In your case, you are manually inserting primary which is pretty rare. I think your workaround is fine.
