### ISSUE TITLE
Typo in hook cheking

### ISSUE THREAD

**Issue by jpascal** [uptrace/bun#21]
https://github.com/uptrace/bun/blob/v0.1.17/schema/table.go#L788 mistake

**Comment by vmihailenco** [comment]
Thanks for the heads up, but this code is going away with the new hooks in v0.2.

**Comment by jpascal** [comment]
@vmihailenco, hi.
Yes, I know about v0.2. Could you tell me date of release v0.2?

**Comment by vmihailenco** [comment]
Just released - https://github.com/uptrace/bun/blob/master/CHANGELOG.md
