### ISSUE TITLE
Add schema configuration support

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#214]
By default bun searches for table in public schema. but in microservice era, It is very common to use different schema other than public. Currently the only way to set a different schema is to use override default table name:

`bun.BaseModel `bun:"table_name"``

This is very counter productive. Because now I have to override all table definitions. With libpq "postrgres" I can specify schema with `search_path` in the DSN. But `pgdriver` does not support this. Is it possible to add `currentschema` or `search path` configuration in connection string?

**Comment by vmihailenco** [comment]
In go-pg this was solved with AfterConnect hook. I guess we can try a similar approach with pgdriver.

**Comment by imraan-go** [comment]
Cant we solve this with simpler approach such as providing default/current schema  with the DSN just like lib/pq ? Or follow pgx implementation : [https://pkg.go.dev/github.com/jackc/pgx#ParseDSN](https://pkg.go.dev/github.com/jackc/pgx#ParseDSN) 
```
Any options not used by the connection process are parsed into ConnConfig.RuntimeParams.

e.g. ParseDSN("application_name=pgxtest search_path=admin user=username password=password host=1.2.3.4 dbname=mydb")

```

**Comment by vmihailenco** [comment]
See https://bun.uptrace.dev/postgres/#pgdriver for docs
