### ISSUE TITLE
Bulk Inserts with generated always column

### ISSUE THREAD

**Issue by rohitkg98** [uptrace/bun#215]
Columns which are `GENERATED ALWAYS`, don't work with insert queries containing multiple rows and the column values as `DEFAULT`

for example:

consider a table:
```sql
CREATE TABLE example
(id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY);
```

the following generated query fails:
```sql
INSERT INTO "example" ("id") 
VALUES 
(DEFAULT),
(DEFAULT)
RETURNING "id";
```

more about it can be read [here](https://www.postgresql.org/docs/12/ddl-generated-columns.html), not sure if this can be considered as a postgres bug.

**Comment by vmihailenco** [comment]
Your example works just fine...

**Comment by rohitkg98** [comment]
my bad, the DDL had `GENERATED BY DEFAULT` instead of `GENERATED ALWAYS`, generated by default is the work around I'm using

**Comment by vmihailenco** [comment]
Well, use `GENERATED BY DEFAULT` then. There is no easy way to make `GENERATED ALWAYS` work without adding a flag or a new tag option, which does not look worth it.

**Comment by bearsh** [comment]
just for the record, adding the `scanonly` tag to `ID` also seems to workaround the problem
