### ISSUE TITLE
How to use omitZero for UpdateQuery

### ISSUE THREAD

**Issue by rohitkg98** [uptrace/bun#232]
UpdateQuery has a member `omitZero`, which is used to omit null fields from update but it is not being set anywhere and there is no way to do so either since it's a private variable.

variable in question: https://github.com/uptrace/bun/blob/65feecad7cf307a253515a5947cac1b0b7ddef56/query_update.go#L20

**Comment by vmihailenco** [comment]
This is an overlook. I will add `OmitZero()` method.
