### ISSUE TITLE
Getting wrong data

### ISSUE THREAD

**Issue by Edwin-Luijten** [uptrace/bun#25]
I'm having a weird issue where I can't wrap my head around.
I'm trying to get an item with ID 13, but it returns a wrong one.
```
fmt.Println(id)
	mdl := &db.Model{}
	if err := r.client.NewSelect().Model(mdl).Where("id = ?", id).Scan(context.Background()); err != nil {
		return nil, fmt.Errorf("get model: %w", err)
	}

	properties := make([]*model.Property, 0)
	if err := json.Unmarshal([]byte(mdl.Properties), &properties); err != nil {
		return nil, err
	}

	fmt.Println("before return", mdl.Id, mdl.Slug)
	return &model.Model{
		Id:         mdl.Id,
		Name:       mdl.Name,
		Slug:       strings.ToLower(mdl.Slug),
		TitleField: mdl.TitleField,
		Properties: properties,
	}, nil
```

Logs:
In my controller I fetch the ID from the url: requesting model entities 13
Before running the query the ID is: 13
Query log: [bun]  16:49:16.332   SELECT                  460µs  SELECT "model"."id", "model"."name", "model"."slug", "model"."title_field", "model"."properties" FROM "models" AS "model" WHERE (id = 13)

Before I return the data, id and slug are from a different record: ID = 14 and slug = aap.

Any pointers?

**Comment by vmihailenco** [comment]
No ideas here. I don't think the problem is in Bun.

**Comment by Edwin-Luijten** [comment]
Probably indeed, I extracted the logic to another file, where this issue is not occurring, seems an issue with the http (net/http) server (using github.com/go-chi/chi/v5 as router).

**Comment by vmihailenco** [comment]
Please re-open if you have more details.

**Comment by merefield** [comment]
@vmihailenco @Edwin-Luijten I'm was getting the same issue:

```
err = s.db.NewSelect().
  Model(thisuser).
  Where("id = ?", OwnerUUID).
  Scan(ctx)
```

This was populating the wrong user in the Model despite the CORRECT query being run.

Once I did this, it worked!:

```
err = s.db.NewSelect().
  Model(thisuser).
  Where("? = ?", bun.Ident("id"), OwnerUUID).
  Scan(ctx)
```

Is that expected behaviour?
