### ISSUE TITLE
Is PK automagically create for fields with name ID or UUID if there is another `,pk` field?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#252]
### Discussed in https://github.com/uptrace/bun/discussions/250

Your answer, @vmihailenco:

> ```go
> type Genre struct {
>   ID int
> }
> ```
> 
> Should be working, e.g. see https://github.com/uptrace/bun/blob/master/internal/dbtest/orm_test.go#L432-L441

You're right it works, but it doesn't if you have a struct with double `pk`:

```go
type Genre struct {
	ID       int
	TenantID int     `bun:",pk"`
	Tenant   *Tenant `bun:"rel:belongs-to"`
}

type Tenant struct {
	ID   int
	Name string
}
```

I need `Genre` to have both `PK`: `ID` and `TenantID`.

In this case it doesn't generate schema with `SEQUENCE` for both `pk`.

Am I right?

I think we should write this in docs or if this is a "bug" we should fix it.

**Comment by vmihailenco** [comment]
I would say you have a pk on `id` column and an unique index on `(id, tenant_id)`.

>Am I right?

Right, Bun does not recognize that and I don't think it should. You should add tags explicitly.
