### ISSUE TITLE
db.RunInTx helper (similar to what we have in go-pg)

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/bun#26]

**Comment by jpascal** [comment]
In my project I have this code
```go
func Transaction(db *bun.DB, callback func(tx bun.Tx) error) error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	err = callback(tx)
	if err != nil {
		if rErr := tx.Rollback(); rErr != nil {
			return rErr
		}
		return err
	}
	return tx.Commit()
}
```

**Comment by vmihailenco** [comment]
That looks good. What do you think about also accepting `TxOptions`?

Also the code should probably use `defer tx.Rollback()` to better handle panics.

**Comment by jpascal** [comment]
> That looks good. What do you think about also accepting `TxOptions`?
> 
> Also the code should probably use `defer tx.Rollback()` to better handle panics.

Good ideas.

**Comment by vmihailenco** [comment]
Added in v0.2.5
