### ISSUE TITLE
Change migrations table name

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#283]
I would like to be able to change the name of the `bun_migrations` and `bun_migration_locks` tables, please.

Even without the `bun_` in front it would be fine.

**Comment by frederikhors** [comment]
I think we should change these lines with an option?

https://github.com/uptrace/bun/blob/master/migrate/migrator.go#L47-L48

**Comment by vmihailenco** [comment]
Have you tried  WithTableName and WithLocksTableName?

**Comment by frederikhors** [comment]
It works. Thanks.
