### ISSUE TITLE
Relation types seem to contradict each other

### ISSUE THREAD

**Issue by sbward** [uptrace/bun#284]
For me, the definitions of `has-one`, `belongs-to` and `m2m` seem to contradict each other.

When defining `m2m` one creates an intermediate type with two `has-one` relations, although `has-one` by itself means that the association (ID) is stored in the other model. However in `m2m` it seems the meaning of `has-one` is altered within the scope of the intermediate type; the association ID is stored within itself, instead of in the other model (as is usually the case with `has-one`).

It seems like the easiest way to fix this problem would be to use `belongs-to` relations within the `m2m` intermediate types, instead of `has-one` relations.

**Comment by vmihailenco** [comment]
You are right, the example in docs is outdated. See https://github.com/uptrace/bun/blob/master/example/rel-many-to-many/main.go for correct usage.

**Comment by vmihailenco** [comment]
Docs should be updated.
