### ISSUE TITLE
Add warning when zero time ('0001-01-01 00:00:00+00:00') is appended

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/bun#29]

**Comment by rojanDinc** [comment]
Hi I'd like to contribute. To what should this warning be displayed when a zero time is appended?

**Comment by vmihailenco** [comment]
Hi @rojanDinc,

We have the `warn` logger here - https://github.com/uptrace/bun/blob/master/internal/logger.go#L10. Then in schema/table.go you can add a check like:

```go
if field.Type == timeType && !field.NullZero {
    // warn user
}
```

**Comment by rojanDinc** [comment]
Thanks for the pointers 👍
