### ISSUE TITLE
db CopyFrom/CopyTo Support similar to go pg

### ISSUE THREAD

**Issue by ganesh-karthick** [uptrace/bun#299]
I see go pg has support for [CopyFrom CopyTo](http://godoc.org/github.com/go-pg/pg#example-DB-CopyFrom) commands. Any plans to add support for this in [IDB](https://pkg.go.dev/github.com/uptrace/bun#IDB) interface?

**Comment by vmihailenco** [comment]
This should be added to pgdriver package. IDB is a common interface for SQLite, Postgres, and MySQL and thus can't have it.

**Comment by erstam** [comment]
+1 I wish we get this at some point!

**Comment by victordeleau** [comment]
+1 We really need this

**Comment by vmihailenco** [comment]
Should be available in v1.0.18 - see https://bun.uptrace.dev/postgres/copy-data.html
