### ISSUE TITLE
Documentation error for Before/AfterCreateTableHook

### ISSUE THREAD

**Issue by AnsonT** [uptrace/bun#301]
https://bun.uptrace.dev/guide/query-create-table.html

The documentation site uses: BeforeCreateTable**Query**Hook and BeforeCreateTable**Query**. (Also for AfterCreateTable)

It should be BeforeCreateTableHook and BeforeCreateTable, AfterCreateTableHook and AfterCreateTable

**Comment by vmihailenco** [comment]
Thanks :+1: Docs should be updated soon.
