### ISSUE TITLE
Backslash not escaped

### ISSUE THREAD

**Issue by maebeam** [uptrace/bun#305]
Hello!

It seems like backslashes are not properly escaped when inserting rows. I'm not sure if there are other characters that are also not being escaped. Reproduce:

```go
model := Model{
	Description: string('\\'),
}
_, err = db.NewInsert().Model(&model).Exec(context.Background())
panic(err)
```

Note, I am using MySQL. Not sure if this applies to postgres

**Comment by vmihailenco** [comment]
Thanks for the report. Should be fixed in v1.0.17
