### ISSUE TITLE
PostgreSQL "Has many relation"  optimization

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#309]
This example : https://github.com/uptrace/bun/tree/master/example/rel-has-many

Currently, with Bun's has many implementation, Bun executes two queries. 

```sql
[bun]  14:10:17.279   SELECT                   20µs  SELECT "user".* FROM "users" AS "user" ORDER BY user.id ASC LIMIT 1
[bun]  14:10:17.279   SELECT                   23µs  SELECT "profile"."id", "profile"."lang", "profile"."active", "profile"."user_id" FROM "profiles" AS "profile" WHERE ("profile"."user_id" IN (1)) AND (active IS TRUE)
```

But this can be done in one query with left join. In PostgreSQL one can do, 

```sql
 SELECT "users".*,array_agg(profiles.*) FROM "users" left join profiles on profiles.user_id=users.id group by users.id
```
This will effectively get the same results without needing to chain multiple queries.

**Comment by vmihailenco** [comment]
Yes, as long as you know how to parse `array_agg(profiles.*)` results. Given the amount work it requires, I doubt it will ever be implemented.

**Comment by imraan-go** [comment]
> Yes, as long as you know how to parse `array_agg(profiles.*)` results. Given the amount work it requires, I doubt it will ever be implemented.

Even with separate queries, you have to parse the results. right? 

```sql
SELECT "profile"."id", "profile"."lang", "profile"."active", "profile"."user_id" FROM "profiles" AS "profile" WHERE ("profile"."user_id" IN (1,2,3,4)) AND (active IS TRUE)
```
After the 2nd queries, you have to create iterate through the rows. With my approach, this seems easier.

**Comment by frederikhors** [comment]
This is interesting. But like everything, time and therefore performance must be measured. Can you give us some numbers on a test DB?

**Comment by vmihailenco** [comment]
>Even with separate queries, you have to parse the results. right?

Yes, it is already done and is somewhat standardize / abstracted. What you suggest here is a separate format specific to PostgreSQL `array_agg` function.

I am closing this since I don't expect this to be implemented.

**Comment by imraan-go** [comment]
> > Even with separate queries, you have to parse the results. right?
> 
> Yes, it is already done and is somewhat standardize / abstracted. What you suggest here is a separate format specific to PostgreSQL `array_agg` function.
> 
> I am closing this since I don't expect this to be implemented.

It can be done with simple left join as well. It doesn't necessarily have to be done with array_agg.

**Comment by vmihailenco** [comment]
Yes, it would be easier to scan results with left join, but then you have to do some post-processing to deduplicate rows and get the results in the expected format.

**Comment by frederikhors** [comment]
@vmihailenco, you are one of my myths, which I love.

But I have a question about this last sentence of yours: does it mean that we will never have the use of automatic JOINs in Bun?

**Comment by vmihailenco** [comment]
I am not going to work on this issue, because it is significant amount of work and the demand is low. GORM/Entgo don't even have optimizations available in go-pg and that does not stop anyone.

**Comment by imraan-go** [comment]
@vmihailenco I'll try to work on this issue. Will submit a PR in the weekend.

**Comment by vmihailenco** [comment]
You are welcome to try :+1:
