### ISSUE TITLE
There seems to be a problem with the returned Operation here

### ISSUE THREAD

**Issue by danclive** [uptrace/bun#310]
https://github.com/uptrace/bun/blob/b6fa7674b2cfd808c22c644074a92beb4c1218d2/query_update.go#L169

This issue causes the logs to not print as expected：

```
[bun]  18:39:38.017   SELECT                   73µs  UPDATE "source" AS "source" SET "name" = 'source'  WHERE "source"."deleted" IS NULL AND ("source"."id" = '017bb54ddc3ab7314de068d8')
```

**Comment by vmihailenco** [comment]
Closed by https://github.com/uptrace/bun/commit/687a004ef7ec6fe1ef06c394965dd2c2d822fc82
