### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#312]
I get i/o timeout error after a connection reset.

`*net.OpError: read tcp 192.168.3.3:60799->13.x.x.x:5432: i/o timeout`

After 10seconds, the connection times out and subsequent requests works fine.

**Comment by vmihailenco** [comment]
Timeouts happen. It's okay.

Bun itself can't be responsible for timeouts, because conns are created and managed by database/sql drivers. If you using pgdriver and suspect it, you can switch to pgx and see if the problem goes away.
