### ISSUE TITLE
Is there a way I can query the parent model from has-one child?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#313]
If I'm using has-one relation like in the docs example:

```go
type Profile struct {
	ID     int64 `bun:",pk"`
	Lang   string
	UserID int64
}

type User struct {
	ID      int64 `bun:",pk"`
	Name    string
	Profile *Profile `bun:"rel:has-one,join:id=user_id"`
}
```

I can query Profile using `.Relation("Profile")`.

**Is there a way I can query the User from Profile?**

Using

```go
var profile Profile

err := db.NewSelect().Model(&profile).Where("?TableAlias.id = ?", id).
		Relation("User").
		Scan(ctx)
```

it gives `model=Profile does not have relation=\"User\""`.

**Comment by vmihailenco** [comment]
You can define a relation on Profile model:

```go
type Profile struct {
	ID     int64 `bun:",pk"`
	Lang   string
	UserID int64
        User *User `rel:"belongs-to"`
}
```

**Comment by frederikhors** [comment]
It works. Thanks. I think docs should be extended because I didn't understand it right away and I had to open this issue.

What do you think?

![image](https://user-images.githubusercontent.com/41120635/142846464-311348c3-f4a1-40e6-bf40-cd4f8674610b.png)

**Comment by vmihailenco** [comment]
Do you have a suggestion how to improve it?

**Comment by frederikhors** [comment]
Yeah. I will add this:

### A little note about Has-One and Belongs-To:

You can query each other by using `.Relation()`, example:

```go
err := db.NewSelect().Model(&user).Where("?TableAlias.id = ?", id).Relation("Profile").Scan(ctx)
```

and the opposite:

```go
err := db.NewSelect().Model(&profile).Where("?TableAlias.id = ?", id).Relation("User").Scan(ctx)
```

**Comment by frederikhors** [comment]
An example is worth a thousand words.

**Comment by frederikhors** [comment]
If you make the docs repo public I can help you with some PR for other things as well.
