### ISSUE TITLE
Automatically update updated_at without hook

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#320]
Currently is there any way to update update_at without any hook? I  don't want to update the  updated_at column when the row is inserted.

**Comment by vmihailenco** [comment]
What do you expect?

All we have now is documented at https://bun.uptrace.dev/guide/models.html#automatic-timestamps

**Comment by imraan-go** [comment]
If I use bun.Nulltime, the field is not updated automatically. I want the update_at column to update automatically when the row is updated and insert `NULL` when a row is inserted. Seems like currently I either have to update the column manually or use hooks. Is that correct?

**Comment by vmihailenco** [comment]
>Is that correct?

Correct.

**Comment by imraan-go** [comment]
> > Is that correct?
> 
> Correct.

But do you reommend manual update instead of hooks ? Any particular reason why hooks are discouraged?

**Comment by vmihailenco** [comment]
Hooks are not discouraged but there is a [disclaimer](https://bun.uptrace.dev/guide/hooks.html#disclaimer)

>But do you reommend manual update instead of hooks ?

I recommend just writing simple and idiomatic code. When I need to set `UpdatedAt` field, I just do so.

```go
model.UpdatedAt = time.Now()
```

**Comment by imraan-go** [comment]
thanks for clarification!

**Comment by Flipped199** [comment]
Perhaps we do indeed want an automatically updating tag, and in other logic, focus on other matters. Bun is good, I like it.
