### ISSUE TITLE
Generate uuid for pk ID

### ISSUE THREAD

**Issue by kkereziev** [uptrace/bun#321]
Hello I'm trying to use the default tag as `bun:default:gen_random_uuid()` in order to generate new uuid for the pk, but each time I run the query error with message "ERROR: null value in column "id" violates not-null constraint (SQLSTATE 23502)" is shown. Do you have any idea what am I missing here ?

**Comment by vmihailenco** [comment]
`default:gen_random_uuid()` makes `CreateTable` query to set a default expression for the column. I guess you've created the table manually and the column does not have the `DEFAULT gen_random_uuid()` expression.

**Comment by kkereziev** [comment]
Right, this makes a lot of sense, thank you.
