### ISSUE TITLE
Correct way to doing reversed-relation query in m2m example?

### ISSUE THREAD

**Issue by leopku** [uptrace/bun#322]
There are many examples to show how to query m2m relation. But it seems no example to show how to query reversed-relation.

As m2m example, querying items of an order was clearly. But it was confused to query orders of an item.

```go
type Order struct {
	ID int64 `bun:",pk"`
	// Order and Item in join:Order=Item are fields in OrderToItem model
	Items []Item `bun:"m2m:order_to_items,join:Order=Item"`
}

type Item struct {
	ID int64 `bun:",pk"`
}

type OrderToItem struct {
	OrderID int64  `bun:",pk"`
	Order   *Order `bun:"rel:belongs-to,join:order_id=id"`
	ItemID  int64  `bun:",pk"`
	Item    *Item  `bun:"rel:belongs-to,join:item_id=id"`
}
```

What's the correct way to query orders which related to an item?

**Comment by vmihailenco** [comment]
I've updated the example - https://github.com/uptrace/bun/commit/5ddb4b44af38e9309ecf4780d2cafa0de9c8bf59
