### ISSUE TITLE
Need some help with fixtures

### ISSUE THREAD

**Issue by kkereziev** [uptrace/bun#323]
So the current use case, which I'm facing is that I went with the approach of using pure sql for my migrations. Is there a difference between the ways fixtures are done with pure sql migration and go based migrations, because in the tutorial there are only fixtures with go based migrations ?

**Comment by vmihailenco** [comment]
Fixtures are meant to to be used to load some initial data for tests or demonstrations. They don't replace migrations. And you can't use fixtures with pure SQL migrations.

**Comment by kkereziev** [comment]
Thanks a bunch.
