### ISSUE TITLE
Handle Postgres advisory locks (and other functions?)

### ISSUE THREAD

**Issue by ndrpnt** [uptrace/bun#324]
Hi, what's the correct way to obtain a [Postgres advisory lock](https://www.postgresql.org/docs/9.6/functions-admin.html#:~:text=9.26.10.%20advisory%20lock%20functions) using Bun ?

Right now we use the following helper:
```
func obtainAdvisoryLock(ctx context.Context, db bun.IDB) error {
       rows, err := db.QueryContext(ctx, "SELECT pg_advisory_xact_lock(?, ?)", 12, 34)
       if err != nil {
               return err
       }

       for rows.Next() {
               if rows.Err() != nil {
                       return rows.Err()
               }
       }

       return rows.Err()
}
```

We expect something like `db.NewSelect().ColumnExpr("SELECT pg_advisory_xact_lock(?, ?)", 12, 34).Scan(ctx)` to work. Sadly it is not valid because of missing model: error `bun: Model(nil)` is returned.

We are on Bun `v1.0.14` if that helps.

Thanks

**Comment by vmihailenco** [comment]
I would use `_, err := db.ExecContext(ctx, "SELECT pg_advisory_xact_lock(?, ?)", 12, 34)`, but you can do that with Bun too:

```go
_, err := db.NewSelect().ColumnExpr("pg_advisory_xact_lock(?, ?)", 12, 34).Exec(ctx)
```

No need to use `Scan` or `QueryContext`, because `pg_advisory_xact_lock` does not return anything. Also, `pg_advisory_xact_lock` must be run in a transaction.

**Comment by ndrpnt** [comment]
Thanks @vmihailenco , we'll try that.
