### ISSUE TITLE
Do we will support MySQL@5.7?

### ISSUE THREAD

**Issue by j2gg0s** [uptrace/bun#33]
MySQL@5.7 does not support `AS` in `DELETE`.

https://dev.mysql.com/doc/refman/5.7/en/delete.html

If we try to support MySQL@5.7, auto alias is a bug.

**Comment by vmihailenco** [comment]
Please try v0.2.6 - it should check MySQL version and generate queries accordingly.

But you can't use WherePK with it. Anyway, WherePK will be removed in v0.3.0.
>If we try to support MySQL@5.7

Let's try and see how much work it takes.

**Comment by vmihailenco** [comment]
In v0.2.8 `WherePK` should work as well.

**Comment by j2gg0s** [comment]
our code under v0.2.6 is ok.

`go-pg`&`bun` is a great project, thanks for your work.
