### ISSUE TITLE
Tag table does not work for postgres models

### ISSUE THREAD

**Issue by senseyman** [uptrace/bun#332]
I'm trying to override table name on my model but it doesn't work.

Example:

```
type Some struct {
		bun.BaseModel `bun:"table:aaaaa"`
}
ci := Some{}
query := db.NewInsert().Model(&ci)
fmt.Println(query.GetTableName())
```

As a result I see _somes_

In go.mod file 
**github.com/uptrace/bun v1.0.18
github.com/uptrace/bun/dialect/pgdialect v1.0.18
github.com/uptrace/bun/driver/pgdriver v1.0.18**

**Comment by vmihailenco** [comment]
I have just released v1.0.19 which should have this feature. In v1.0.18 you can use `bun:"aaaaa"`.
