### ISSUE TITLE
Is this a bug or am I a bug?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#336]
I don't know if this is a bug or I don't know how to query something that can not be in DB.

Example:

```go
type Team struct {
	CreatedAt time.Time `bun:",nullzero,notnull,default:current_timestamp"`

	ID int `bun:",pk,autoincrement"`

	Description string
}

func Something(ctx context.Context, id int) (*Something, error) {
	var player Player

	var team *Team

	err := r.db.NewSelect().Model(&player).Where("?TableAlias.id = ?", options.PlayerID).Scan(ctx)
	if err != nil {
		return nil, fmt.Errorf("select player: %w", err)
	}

	err = r.db.NewSelect().Model(team).Where("?TableAlias.player_id = ?", options.PlayerID).Scan(ctx)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return nil, fmt.Errorf("select team: %w", err)
	}

	return &Something{
		Player: player,
		Team:  team, // I need a *Team here
	}, nil
}
```

If I use this code and the `Team` for this `Player` is not in DB I get this error:

```
ERR  error="select team: sql: Scan error on column index 0, name \"description\": bun: Model(nil)"
reflect: call of reflect.Value.Field on zero Value
...
```

If I use `var team Team` bun returns me a `Team{ID: 0,...}` which I think is not correct.

Is there a way to handle this situation?

**Comment by vmihailenco** [comment]
You probably should replace `var team *Team` with `team := new(Team)`.

You can also try `Model(&team)`, but I am not sure that will always work...

**Comment by frederikhors** [comment]
I cannot try anymore because the code is changed. Can we write a test for this case? I think this is an interesting case.

Why `team := new(Team)` should be different from `var team *Team`? I mean is the same, right?

**Comment by imraan-go** [comment]
> I cannot try anymore because the code is changed. Can we write a test for this case? I think this is an interesting case.
> 
> Why `team := new(Team)` should be different from `var team *Team`? I mean is the same, right?

Not really.  `team := new(Team)` equals to `team := &Team{}` which means allocate memory for the struct and return a pointer to it. But  `var team *Team` just declares variable, does not actually allocate any memory for the struct.

**Comment by frederikhors** [comment]
You're right. I'll re-open it for future issues about this. Thanks!
