### ISSUE TITLE
JSON in Fixtures

### ISSUE THREAD

**Issue by kkereziev** [uptrace/bun#337]
Hey, currently I'm adding seed data for one of my models but I'm having trouble with one of my struct props, which is of postgres type jsonb. When I try to add values for the json keys in the db INSERT query all zero values are inserted for the given keys. How is this type of property supposed to be populated in the .yml file ?

**Comment by vmihailenco** [comment]
Basically, YAML is first loaded into a Go struct and then the struct is saved to the db with Bun. So the problem is probably with YAML unmarshaling (check field/column names). See https://github.com/uptrace/bun/commit/47e28c331dd1f85657562759e084a5dcec28f233

**Comment by kkereziev** [comment]
Nope, still have the problem. This is what I got:

```
type GeneralConfigOptions struct {
	LoyaltyAllowance        float64 `json:"loyalty_allowance" validate:"gte=0.0"`
	PointSizer              int     `json:"point_sizer" validate:"gte=0"`
	AdjustmentBonusWagers   float64 `json:"adjustment_bonus_wagers" validate:"gte=0.0"`
	InitialBonusPoints      int     `json:"initial_bonus_points" validate:"gte=0"`
	MaxPointsPerBet         int     `json:"max_points_per_bet" validate:"gte=0"`
	MinOddsForAwardedPoints float64 `json:"min_odds_for_awarded_points" validate:"gte=1.0"`
}

type GeneralConfigEntity struct {
	bun.BaseModel `bun:"general_config,alias:general_config"`
	db.Timestamp

	ID   uuid.UUID            `bun:"type:uuid,pk"`
	Opts GeneralConfigOptions `bun:"type:jsonb"`
}
```

and the yml. file is:

- model: GeneralConfigEntity
  rows:
    - id: '{{ gen_random_uuid }}'
      opts: {
        loyalty_allowance: 1.0,
        point_sizer: 1,
        adjustment_bonus_wagers: 1.3,
        initial_bonus_points: 1,
        max_points_per_bet: 1,
        min_odds_for_awarded_points: 2.2
      }
      created_at: '{{ now }}'
      updated_at: '{{ now }}'

**Comment by vmihailenco** [comment]
You need to add yaml tag to `GeneralConfigOptions`:

```go
type GeneralConfigOptions struct {
	LoyaltyAllowance        float64 `json:"loyalty_allowance" yaml:"loyalty_allowance" validate:"gte=0.0"`
        ...
}

```

**Comment by kkereziev** [comment]
Ohh.. this solved the problem, thank you very much.
