### ISSUE TITLE
Singular table name 

### ISSUE THREAD

**Issue by razibulhasanbs23** [uptrace/bun#338]
**Model:** 
```go
type Organization struct {
	bun.BaseModel `bun:"table:organization"`
	ID            int64  `bun:"id,pk"`
	Name          string `bun:"name"`
}
```
The existing database table name is **organization**. when I'm trying to apply an insert query `db.NewInsert().Model(&organization).Exec(ctx)` it's returning an error **`ERROR #42P01 relation \"organizations\" does not exist`**. Its expecting plural form. Is there any support to use singular or specific table name?

Another issue is when I'm trying to add tag: table on model it's throwing an error like : `Organization.BaseModel has unknown tag option: "table"`

**Comment by vmihailenco** [comment]
Please make sure you are using v1.0.19
