### ISSUE TITLE
RunInTx, ScanAndCount unexpected message

### ISSUE THREAD

**Issue by sergolius** [uptrace/bun#341]
go: `1.17.3`
bun: `v1.0.20-0.20211201113811-47e28c331dd1`

Calling `ScanAndCount` in `RunInTx` results in different variants of `unexpected message` error (depends on order of `Scan`, `Count`).

1. `pgdriver: newRows: unexpected message 'D'`
2. `pgdriver: Next: unexpected message 'T'`

Error may not occur for first time call, that why used infinite loop in test example.

```go
package main

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/uptrace/bun" // v1.0.20-0.20211201113811-47e28c331dd1
	"github.com/uptrace/bun/dialect/pgdialect"
	"github.com/uptrace/bun/driver/pgdriver"
)

type User struct {
	ID        uuid.UUID `bun:"type:uuid,default:uuid_generate_v4()"`
	FirstName string    `bun:"first_name,nullzero"`
	ProfileID uuid.UUID `bun:"profile_id,nullzero,type:uuid"`
}

func main() {
	ctx := context.Background()
	sqlDB := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN("postgres://postgres:12345@localhost:5432/postgres?sslmode=disable")))
	db := bun.NewDB(sqlDB, pgdialect.New())

	defer func() {
		_, err := db.NewDropTable().IfExists().Model((*User)(nil)).Exec(ctx)
		if err != nil {
			panic(err)
		}
	}()

	_, err := db.NewCreateTable().IfNotExists().Model((*User)(nil)).Exec(ctx)
	if err != nil {
		panic(err)
	}

	var users []User

	for {
		users = users[:0]

		err := db.RunInTx(ctx, nil, func(ctx context.Context, tx bun.Tx) error {
			_, err := tx.NewSelect().Model(&users).ScanAndCount(ctx)
			return err
		})
		if err != nil {
			panic(err)
		}
	}
}
```

**Comment by vmihailenco** [comment]
The problem here is that `ScanAndCount` concurrently call 2 queries on a `*sql.Tx` which is not thread-safe. I guess we don't have much choice but to remove concurrency from `ScanAndCount`...

**Comment by imraan-go** [comment]
The concurrent call comes in very handy. I never had a problem with it. Instead of removing it altogether like the recent PR, Maybe just make it sequential for Transaction calls? Perhaps introduce another parameter to toggle it Like `ScanAndCount(ctx,false)`

**Comment by sergolius** [comment]
@imraan-go In my investigation and understanding: Tx shares connection between underlying Queries(`SelectQuery`, `InsertQuery`, etc). In case `ScanAndCount` at lucky randomness `Count` request get response of `Scan` and vice versa.

@vmihailenco should be docs updated with warning about using concurrency within transactions?
Why it was safe in go-pg?

**Comment by vmihailenco** [comment]
In go-pg, transactions are thread-safe.
