### ISSUE TITLE
Main page is out of date

### ISSUE THREAD

**Issue by l1ving** [uptrace/bun#347]
Hello, I'm unsure whether there is a separate repo for Bun's website, but I am referring to this one https://bun.uptrace.dev/.

The example has the line 
```go
	// Print all queries to stdout.
	db.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose()))
```

This syntax will no longer compile, due to `bundebug.WithVerbose()` now requiring an explicit on/off bool parameter.

The docs for it look like so:
```go
// WithVerbose configures the hook to log all queries
// (by default, only failed queries are logged).
func WithVerbose(on bool) Option {
	return func(h *QueryHook) {
		h.verbose = on
	}
}
```

I believe to modify this to the old default behavior, you should do
```diff
=	// Print all queries to stdout.
-	db.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose()))
+	db.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose(true)))
```

The other docs on the website should also be checked for instances of this.

**Comment by vmihailenco** [comment]
Thanks for the report. Should be fixed.
