### ISSUE TITLE
Problem with numeric

### ISSUE THREAD

**Issue by kkereziev** [uptrace/bun#348]
Hey, I have a table with one of the properties being numeric type. When I try to insert values there is a error thrown:
sql: Scan error on column index 6, name "bet_amount": bun: can't scan "42.12" into float64Result []. The problem was solved when I changed the sql type for the property to be float. Could u dig into this problem, please?

**Comment by vmihailenco** [comment]
Please show the code that reproduces the problem.

**Comment by kkereziev** [comment]
My mistake- the operations is a select one-

```
var result []CasinoRoundBet

		db.
			NewSelect().
			Model(&result).
			Where("player_id = ? AND round_id = ? AND bet_status = ?", playerID, roundID, _placedStatus).
			Scan(ctx, &result)
```
This returns - sql: Scan error on column index 6, name "bet_amount": bun: can't scan "42.12" into float64 in case where bet_amount is numeric. But if I change the type of bet_amount to float this works out fine.

**Comment by imraan-go** [comment]
If you use numeric in database, you should NOT use float64 datatype to store their values. Float datatype has loss of precision. There are some third party libraries available to store numeric or currency datatypes. You should use those

**Comment by kkereziev** [comment]
Yes, I'm using float64 and numeric. Can you give me link for such library ?
