### ISSUE TITLE
docs: add info & examples to `Exec()` function

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#357]
Can we add some info and examples to `Exec()` function?

![image](https://user-images.githubusercontent.com/41120635/145805149-8e183311-40af-471b-9cc3-b7d3e5b2ed35.png)

**Comment by vmihailenco** [comment]
That is just a wrapper over database/sql Tx. There is an example how to work with transactions at https://bun.uptrace.dev/guide/transactions.html#idb-interface
