### ISSUE TITLE
Unexpected data populated into model instance after SELECT

### ISSUE THREAD

**Issue by merefield** [uptrace/bun#36]
@vmihailenco (similar to #25)

```
thisuser := new(model.User)

err = s.db.NewSelect().
  Model(thisuser).
  Where("id = ?", OwnerUUID).
  Scan(ctx)
```

This was populating the wrong user in the model instance `thisuser` despite the CORRECT query being run and the correct data returning if run directly in, say, pgAdmin.

Once I did this, however, it worked! (despite the same query being apparently generated each time!):

```
err = s.db.NewSelect().
  Model(thisuser).
  Where("? = ?", bun.Ident("id"), OwnerUUID).
  Scan(ctx)
```

Is that expected behaviour?

FYI, this may partially explain it, I'm doing something funky with my IDs

Each model shares this struct:

```
type IDRecord struct {
	ID        uuid.UUID `bun:"type:uuid,default:uuid_generate_v4()"`
	CreatedAt time.Time `bun:",nullzero,notnull,default:current_timestamp"`
	UpdatedAt time.Time
	DeletedAt time.Time `bun:",soft_delete"`
}
```

so my User model begins:

```
type User struct {
	IDRecord
```

This is done to avoid repetition and inconsitency, but may create issues with bun?

**Comment by vmihailenco** [comment]
I doubt that adding `bun.Ident("id")` can make any difference at all. I am using Bun in prod at uptrace.dev and I don't see such behaviour. And the test coverage is not that bad to not catch such bugs.

>This is done to avoid repetition and inconsitency, but may create issues with bun?

No, such code should work fine.

**Comment by merefield** [comment]
Thanks for responding on weekend (not expected!).

I've just reverted it back again (to ` Where("id = ?", OwnerUUID).`) to double check and can reproduce the problem, again the wrong record is populated into the model instance.

Happy to close my issue as I have a workaround, but it's a very interesting, and in my case a reproduceable result!

**Comment by Edwin-Luijten** [comment]
I haven't solved it code/query wise, I tried changing the way the client is build. I took it from one files in the example folder:
Before:
```
sqldb, err := sql.Open("pgx", connectionString)
	if err != nil {
		return nil, err
	}

	d := bun.NewDB(sqldb, pgdialect.New())
	d.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose()))
```
After:
```
config, err := pgx.ParseConfig(connectionString)
	if err != nil {
		return nil, err
	}

	config.PreferSimpleProtocol = true
	sqldb := stdlib.OpenDB(*config)

	d := bun.NewDB(sqldb, pgdialect.New())
	d.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose()))

```

So perhaps it's a driver issue?

**Comment by vmihailenco** [comment]
There is a slim chance this can be caused by the stmt cache in pgx. But it is very unlikely too :)

Anyway, setting `config.PreferSimpleProtocol = true` is the right thing to do with pgx and Bun. You can also try pgdriver - it is stable/mature enough at this point.

**Comment by Edwin-Luijten** [comment]
From what I experienced with my setup It might be the cache.
Because if I refreshed the page sometimes I had the correct record a few times and suddenly a different one a few times.

Going to try pgdriver.

**Comment by merefield** [comment]
> config.PreferSimpleProtocol = true

This fixes it for me, works again with either flavour of `Where` clause!

Thanks guys!

**Comment by vmihailenco** [comment]
I think what happens here is that pgx uses the generated query to cache prepared statements. But Bun assumes that the generated query is not used after it was processed and re-uses the memory. Which leads to all sorts of unexpected behavior.

**Comment by Edwin-Luijten** [comment]
I'm not sure how heavily used bun is at the moment, or pgx + bun, this behavior could be added as a note in the documentation. Or if it's considered a bug/edge case we can fix it.
