### ISSUE TITLE
Select with `HasMany` and `ManyToMany` does not use current transaction

### ISSUE THREAD

**Issue by sbward** [uptrace/bun#364]
When performing a join on a `HasMany` or `ManyToMany` relation, bun starts a new select query as such:

https://github.com/uptrace/bun/blob/25ac1477f98451c0974dc3b57a5af1e91b863676/query_select.go#L346-L349

Unfortunately creating the new query via `q.db` ignores whether `q.conn` might be a `*sql.Tx`, which can break code that performs this join during a transaction. Using `q.db` creates a new connection to perform the query, which will break queries that select data created or modified during a transaction.

**Comment by vmihailenco** [comment]
Thanks for fixing this :+1:
