### ISSUE TITLE
select with relation return err

### ISSUE THREAD

**Issue by bgdnxt** [uptrace/bun#375]
By following the has one relationship example from [here](https://bun.uptrace.dev/guide/relations.html#has-one-relation)

```go

// model
type User struct {
	ID int64 `json:"id,string" bun:",pk"`
	Profile *UserProfile `json:"profile" bun:"rel:has-one,join:id=user_id"`
}

type UserProfile struct {
	ID     int64 `json:"id,string" bun:",pk"`
	UserID int64 `json:"userId"`
}

//selection

user := &User{}
err := DBM.NewSelect().Model(user).Relation("Profile").Where("id = ?", 1).Scan(context.Background())

//debug print sql

SELECT "user"."id", "profile"."id" AS "profile__id", "profile"."user_id" AS "profile__user_id" FROM "users" AS "user" LEFT JOIN "user_profiles" AS "profile" ON ("profile"."user_id" = "user"."id") WHERE (id = 1) 

```

the postgres db return err `ERROR: column reference \"id\" is ambiguous (SQLSTATE=42702)`

**Comment by OleksandrKrupnyk** [comment]
See [https://bun.uptrace.dev/guide/placeholders.html#in](https://bun.uptrace.dev/guide/placeholders.html#in)
use code 
```
DBM.NewSelect().Model(user).Relation("Profile").Where("?TableName.id = ?", 1).Scan(context.Background())
```

**Comment by vmihailenco** [comment]
You should fix your query as Oleksandr suggested.

**Comment by Emptyfruit** [comment]
Fair to say that the doc on the website provides an example with the same error
<img width="788" alt="изображение" src="https://user-images.githubusercontent.com/14968783/194765783-0574f6af-d5c2-46f1-8271-8e37e0d3b854.png">

**Comment by Emptyfruit** [comment]
It also seems that correct fix is not  `?TableName`, but `?TableAlias`.

**Comment by VishwasShashidhar** [comment]
@Emptyfruit is right. it should be `?TableAlias`
