### ISSUE TITLE
Scanner/Value interface

### ISSUE THREAD

**Issue by oiime** [uptrace/bun#382]
Hello, I am trying to implement a custom type, I've attempt to use a valuer scanner interface for it

eg:
```
type JSON json.RawMessage

type NullJSON struct {
	JSON  JSON
	Valid bool
}
func (n *NullJSON) Scan(value interface{}) error {
	if value == nil {
		n.JSON, n.Valid = nil, false
		return nil
	}
	n.Valid = true
	return n.JSON.Scan(value)
}
func (n *NullJSON) Value() (driver.Value, error) {
	if !n.Valid {
		return nil, nil
	}
	return n.JSON.Value()
}
```

Bun however attempts to use its own marshaling from `schema/append_value.go`, Is there a cleaner way to implement custom marshaling types in models?

**Comment by vmihailenco** [comment]
Please see https://github.com/uptrace/bun/tree/master/example/custom-type and provide a similar example that I can run to reproduce the issue.

**Comment by oiime** [comment]
@vmihailenco I've looked into it and the problem relates to defining the type in bun

```
type Model struct {
	bun.BaseModel `bun:"table:tablename"`
	Data  utypes.NullJSON `json:"source_entity,omitempty" bun:"data,type:jsonb"`
}
```
Would yield `{JSON: "payload"}` in the Data column
While removing type:jsonb would yield `payload`

I think the reason is that this does check if *Field implements value scanner before coverting it directly to []byte:
```
switch strings.ToUpper(field.UserSQLType) {
	case sqltype.JSON, sqltype.JSONB:
		return AppendJSONValue
	}
```

**Comment by vmihailenco** [comment]
You are right. We probably should re-order the code to give Scanner/Valuer priority.

**Comment by oiime** [comment]
@vmihailenco Do you still need example code for it? 

Not sure if it's a complicated fix, I would have just put a check there if `field` implements Scanner/Value and if so skip returning AppendJSONValue, but I dont know what meshes nicely with the overall architecture of bun

**Comment by vmihailenco** [comment]
I think this should be fixed by https://github.com/uptrace/bun/pull/386
