### ISSUE TITLE
Error when scanning `uint64` with fixtures

### ISSUE THREAD

**Issue by stevejuma** [uptrace/bun#383]
Observing an issue with fixtures when trying to scan a yaml value into an entity column of type `uint64`. Traced the issue to https://github.com/uptrace/bun/blob/master/dbfixture/fixture.go#L328 return `buf.String()` instead of `buf.Bytes()`.  Seems like the schema scanner in https://github.com/uptrace/bun/blob/master/schema/scan.go#L193 is expecting a byteArray. Changing the code in `fixture.go` as outlined seems to fix the issue. Seems to work with int64 because that uses a `string` separate from all other methods in https://github.com/uptrace/bun/blob/master/schema/scan.go#L163

Exception: 

```
panic: dbfixture: decoding parent_id failed: bun: can't scan "1" into uint64
```

Steps to recreate:
* Clone https://github.com/uptrace/bun/tree/master/example/fixture
* Add a new column to Org `ParentID uint64`
* Update first org fixture to `parent_id: '{{ $.User.smith.ID }}'`
* `go run main.go` and observe that the exception above occurs 
* Update `fixture.go #eval` to return `buf.Bytes()` re-run and observe that the exception does not occur. 

Hope that is enough information.  Happy to open a PR to fix the issue if that helps.

**Comment by vmihailenco** [comment]
That is enough information. Thanks for the reporting.
