### ISSUE TITLE
Problem with UUID

### ISSUE THREAD

**Issue by kkereziev** [uptrace/bun#391]
There seems to be a problem with fixtures in github.com/uptrace/bun/dbfixture v1.0.20. When I try to apply the fixtures the following error occurs - "decoding id failed: Scan: unable to scan type uuid.UUID into UUID". I'm using github.com/google/uuid.

**Comment by vmihailenco** [comment]
You can try using `{{ uuid.String() }}` or `{{ uuid[:] }}` in fixtures to please database/sql. If that does not help, please provide a reproducer.

**Comment by vmihailenco** [comment]
Actually, please try v1.0.21 - it should handle this better.

**Comment by kkereziev** [comment]
v1.0.21 worked just fine, thanks
