### ISSUE TITLE
postgress insert query is empty

### ISSUE THREAD

**Issue by amm266** [uptrace/bun#396]
i create an insert query using docs
`type user struct {
	bun.BaseModel `bun:"table:users,alias:u"`
	userId        int    `bun:"user_id,pk,autoincrement"`
	userName      string `bun:"user_name,notnull"`
	password      string `bun:"password,notnull"`
}

	userObj = &user{
		userId:   10,
		userName: "soo",
		password: "soo1234",
	}
	res, err := db.NewInsert().Model(userObj).Exec(ctx)`
and generated query is:
INSERT INTO "users" () VALUES () 
What's wrong with my code?

**Comment by vmihailenco** [comment]
In Go, unexported fields are considered private and are ingored. It should be:

```
userObj = &user{
	UserId:   10,
	UserName: "soo",
	Password: "soo1234",
}
```
