### ISSUE TITLE
Support for Insert ... Returning in MariaDB

### ISSUE THREAD

**Issue by louis77** [uptrace/bun#397]
MariaDB >= 10.5.0 has support for `INSERT ... RETURNING` clause:

https://mariadb.com/kb/en/insertreturning/

In Bun the current MySQL Implementation simply ignores the Returning(). 
It would be great if it could be implemented so that it works with MariaDB too.

**Comment by vmihailenco** [comment]
Hi Louis,

Glad to see you here :) This should be fixed by https://github.com/uptrace/bun/pull/398. I did not give a thorough testing, but the existing tests are passing so please give it a try.
