### ISSUE TITLE
Documentation mistake?

### ISSUE THREAD

**Issue by elliotcourant** [uptrace/bun#4]
## Now
```go
err := db.NewSelect().Model(&users).Scan(ctx)
res, err := db.NewInsert().Model(&users).Exec(ctx)
res, err := pg.NewUpdate().Model(&users).WherePK().Exec(ctx)
res, err := pg.NewDelete().Model(&users).WherePK().Exec(ctx)
```

![image](https://user-images.githubusercontent.com/37967690/118678870-037d9680-b7c3-11eb-9639-c538ee09eb57.png)

Is `pg.` meant to be in the _New_ section?

Is the documentation website for Bun on github at all?

**Comment by vmihailenco** [comment]
Thanks, should be fixed now. Docs are not on GItHub yet (but they will eventually). For now feel free to post issues you find here or on Discord.
