### ISSUE TITLE
Dialect versioning

### ISSUE THREAD

**Issue by oiime** [uptrace/bun#401]
Hello, I just spent some time debugging some issue and eventually found it was due to pqdialect being v1.0.20 and bun being v1.0.21, in this case the omission of `feature.InsertReturning` made pqdialect not use Returning(), which made me wonder, would it make sense to enforce dialect compatibility? eg maintain a marked "api" version which would warn if the dialect is not up to date with the used bun api version?

**Comment by vmihailenco** [comment]
I would expect the versioning/gomod tool to do that job. Not sure that building our own tool is a good idea...

**Comment by oiime** [comment]
@vmihailenco not really a tool, more like adding `dialectApiVersion` to `type Dialect struct` in pgdialect and `DialectApiVersion` to the main dialect implementation, the version would change if there are any breaking changes eg: adding `feature.InsertReturning` which would prohibit mismatch dialect implementations

relying on gomod might be a bit problematic as not all mods are updated together in a lot of development cases. this also is a potential issue with 3rd party dialect implementations.

but you might be right, not sure

**Comment by vmihailenco** [comment]
I guess we can add version information to dialects and check that versions match:

```go
if Version() != bun.Version() {
    // warn
}
```

This should not be too hard to add.

**Comment by oiime** [comment]
I can make a PR if you'd like, seems super trivial

**Comment by vmihailenco** [comment]
@oiime please do :+1: You will need to create version.go files in dialect packages and update it from https://github.com/uptrace/bun/blob/master/scripts/release.sh#L60. Then add the check I've mentioned when a dialect is created. It propbably makes sense to update one dialect first as an experiment.

**Comment by oiime** [comment]
@vmihailenco I'm not sure using Version() is ideal, not every change in bun breaks dialect implementation, that's why I thought using something like ApiVersion that only changes if the dialect api changes, what do you think?

**Comment by vmihailenco** [comment]
I don't think there are any use cases for using bun v1.0.20 with pgdialect v1.0.21 or v1.0.19 even if there were no incompatible changes in API. Then why bother with introducing and maintaining ApiVersion? We use the same version for all packages so updating all packages at once is the most safest way to go.
