### ISSUE TITLE
How to mock bun?

### ISSUE THREAD

**Issue by hhuseyinpay** [uptrace/bun#407]
Hi, is there any way to mock the Bun other than [sqlmock](https://github.com/DATA-DOG/go-sqlmock), I don't want to write raw SQL queries for testing. I know I can print executed queries to stdout then copy&paste them to the Sqlmock but it's a bit painful.

**Comment by vmihailenco** [comment]
I don't write mocks and thus don't have relevant experience, but you could try to create an additional layer that works with database and mock that layer instead of Bun database. That is all I know on the topic :)

**Comment by hhuseyinpay** [comment]
I'm not experienced in testing. So what is your testing strategy? We're going to develop a relatively big project(web API). Before that, I'm experimenting with different frameworks and technics.

**Comment by vmihailenco** [comment]
Usually I write tests against real database without mocking it. Something like https://github.com/go-bun/bun-realworld-app/blob/master/blog/blog_test.go, but it is not the cleanest example.

**Comment by metalrex100** [comment]
@hhuseyinpay it seems like you have more design issue.
I suggest you to create additional layer like `Storage`.
For each DB entity you will have separate storage service: e.g. `UserStorage` (for `user` table).
`UserStorage` and other storage services will provide public (exported) interface for communication with other packages. And ofc each interface will have private implementation inside `storage` package.

So now just use interface everywhere in you app outside `storage` package. In tests for the code which use your `UserStorage` interface, you just pass mock implementation. (Try `moq` package for generating mocks from interfaces).

For testing storage layer, I would suggest to use `go-containers` package which allows you to setup a real DB docker container before tests started. Check `testify/suite` package which provides before and after tests hooks logic.
So the flow is:
 1. Setup and run DB docker container
 2. Migrate you DB schema
 3. Run test, which test some storage method
 4. Truncate DB before next test to avoid side effects.

The benefit of using containers for DB layer tests is that you can setup the type and version of the DB which is used in your production.
