### ISSUE TITLE
Make migrations more explicit and generic

### ISSUE THREAD

**Issue by Codebreaker101** [uptrace/bun#41]
I've started to use bun migrations and I have a few suggestions for possible improvements and would like to hear your opinions on them. And if you approve some of them I could start working on a PR. 

1. Remove `context` and `bun.DB` parameters from `migrations.CreateGo` or `migrations.CreateSQL` function since they are not used. Is it planned for the future?
2. Make migration directory configurable. Currently, it gets the caller directory, which means I have to alias `Create(.*)` functions in the directory where my migrations are located since I'm calling Create function from some other directory.
3. Make package name configurable for `CreateGo` migration (and/or item 6.)
``` go
func CreateGo(directory, name, package string) error
func CreateSQL(directory, name string) error
```

4. Replace logging with `fmt.Printf` with user configurable logger. Maybe global log function for migration package?  Something like:
``` go
var log = func(format string, a ...interface{}) {
	fmt.Printf(format, a...)
}

func SetLogFn(fn func(format string, a ...interface{})) {
	log = fn
}
```
5. Add more code to generated `go` template like the one bellow since this is a MVP for go migration file.  
``` go
package {{ package_name }}

import (
	"context"

	"github.com/uptrace/bun"
)

func init() {
	Migrations.MustRegister(func(ctx context.Context, db *bun.DB) error {
		fmt.Print(" [up migration] ")
		return nil
	}, func(ctx context.Context, db *bun.DB) error {
		fmt.Print(" [down migration] ")
		return nil
	})
}
```
6. Add option for adding user template for go and sql migration file creation.
7. Add a check before migrate if the required migration tables exist, if not, initialize. Quick and dirty way is to run Init(...) on every migration. Might be cheaper to execute then checking first. But speed is not an issue here. 
8. `Status` function should return a struct containing migration status and not print to console.

**Comment by vmihailenco** [comment]
All of that sounds good :+1: We just need to figure out the details :) I think it will be easier if you split these changes into multiple PRs so we can merge it faster and there is a sense progress being made.

>function since they are not used. Is it planned for the future?

Not really, but I think they can be useful at some point (especially context). I am not sure, but since it is a public API I would not change the signature without a good reason. See below how I suggest to extend the API with options.

>Make package name configurable for CreateGo migration (and/or item 6.)

What about keeping the existing signature and instead adding an option:

```
func CreateGo(ctx context.Context, db *bun.DB, name string, opts ...GoOption) error

migrations.CreateGo(ctx, app.DB(), c.Args().Get(0), migrations.WithGoPackage("something"))
```

This way we can add more options in backwards compatible manner.

Also should not `directory string` be a global option?

```go
var Migrations = migrate.NewMigrations(migrate.WithDirectory(directory))
```

>Add a check before migrate if the required migration tables exist, if not, initialize. Quick and dirty way is to run Init(...) on every migration. Might be cheaper to execute then checking first. But speed is not an issue here.

It used to work this way, but once I broke something (probably changed db schema name) and the app attempted to initialize a new migrations table and re-run all the migrations from scratch in production environment.

Luckily for me nothing was broken, but since then I prefer to require explicit initialization. But we can add an option like `WithAutoInit()` if you insist.

**Comment by Codebreaker101** [comment]
> Not really, but I think they can be useful at some point (especially context). I am not sure, but since it is a public API I would not change the signature without a good reason.

I agree with the context but I'm trying to figure out any future need for `bun.Db`. In most, if not all cases, creating migration is done during development phase where one might not have access to database without first spinning up one. One thing I could come up with where database access would be useful is to load templates from database (I'm spit-balling here) and in that case I'm sure a `CreateSQLFromDB` function would be a more adequate way of doing it. Or maybe generating migration based on diff between last migration and new database state. Again, separate function might be better. 

> See below how I suggest to extend the API with options

That sounds good.

> It used to work this way, but once I broke something (probably changed db schema name) and the app attempted to initialize a new migrations table and re-run all the migrations from scratch in production environment.

That is an interesting problem. Most of my apps are self-initializing and if I would to change table and locksTable at a later time I would have the same problem. I guess the only solution would be to check if the database has any tables before auto-initializing. But that is database specific.

For the rest of the points not mentioned here I will start working on the PRs

**Comment by vmihailenco** [comment]
>Again, separate function might be better.

Let's try it :+1: 

Part of the problem is that migrate is a library, but it is used as a CLI program so it complicates things. For example, it makes sense to change `Status` function to return a struct, but then the CLI should somehow print that struct.

I try to address that by providing a [starter-kit](https://github.com/go-bun/bun-starter-kit/blob/master/cmd/bun/main.go#L80-L204), but it still can be challenging to use the API correctly....

**Comment by vmihailenco** [comment]
>Add more code to generated go template like the one bellow since this is a MVP for go migration file.

This was addressed by https://github.com/uptrace/bun/commit/98281aaa960bb854a36101837282b383cf0294b1.

**Comment by Codebreaker101** [comment]
@vmihailenco  Great!

Then all that remains here is point 6 with maybe point 3:

> Add option for adding user template for go and sql migration file creation
> Make package name configurable for CreateGo migration

What do you think?

**Comment by vmihailenco** [comment]
>Make package name configurable for CreateGo migration

This looks rather straightforward:

```go
migrator.CreateGo(ctx, name, WithPackageName("main"))
```

>Add option for adding user template for go and sql migration file creation

I am not sure about the template, because then we also need to add template data, funcs and so on. What about just allowing to specify migration content:

```go
migrator.CreateGo(ctx, name, WithMigrationContent("go source code here"))
```

And `WithMigrationContent` will ignore `WithPackageName` option.

**Comment by isgj** [comment]
Sorry for jumping in and  interrupting the discussion. Can there be also an option when creating the sql migration to create also the `down` migration.?

**Comment by vmihailenco** [comment]
@isgj yes, probably it should be the default behavior. Empty migrations should work fine and users can delete down migration if they don't need it.

**Comment by vmihailenco** [comment]
@isgj should be done in [v0.3.4](https://github.com/uptrace/bun/blob/master/CHANGELOG.md#v034---jul-19-2021)

**Comment by Codebreaker101** [comment]
@vmihailenco excellent work. I think all of the points are resolved so I am closing this. Thanks!
