### ISSUE TITLE
Problem populating values for has-many relationship (MySQL)

### ISSUE THREAD

**Issue by Rheisen** [uptrace/bun#410]
Hello, I'm having an issue populating a has-many relation field on a Bun model. The models look like this:

```
type Device struct {
	bun.BaseModel `bun:"table:devices"`
	ID            int64   `bun:"id,pk,autoincrement"`
	GUID          string  `bun:"guid,unique"`
	Modes         []*Mode `bun:"rel:has-many,join:id=device_id"`
}

type Mode struct {
	bun.BaseModel `bun:"table:modes"`
	ID            int64      `bun:"id,pk,autoincrement"`
	DeviceID     *int64     `bun:"device_id"`
	Name          *string    `bun:"name"`
	CreatedAt     *time.Time `bun:"created_at"`
	UpdatedAt     *time.Time `bun:"updated_at"`
	DeletedAt     *time.Time `bun:"deleted_at"`
}
```

And the query looks like this (where Circuit is a bun.DB and guids is an []string provided as a function argument):

```
devices := []*dbmodel.Device{}

query := Circuit.
	NewSelect().
	Model(&dbmodel.Device{}).
	Where("guid IN (?)", bun.In(guids)).
	Relation("Modes")
if err := query.Scan(context.Background(), &devices); err != nil {
	return devices, fmt.Errorf("problem scanning select query: %w", err)
}

return devices, nil
```

The query executes with no error, but the Modes list is nil (despite there being modes in the DB for the devices with guids passed into the function). I'm not sure if I'm doing something incorrectly, but any help would be greatly appreciated! Happy to provide additional logs as needed.

Update: Adding the bundebug query hook with verbose logging, it doesn't look like any attempt is made to retrieve information about the relation specified in the query.

**Comment by vmihailenco** [comment]
Please try this:

```go
query := Circuit.
	NewSelect().
	Model(&devices).
	Where("guid IN (?)", bun.In(guids)).
	Relation("Modes")
if err := query.Scan(context.Background()); err != nil {
	return devices, fmt.Errorf("problem scanning select query: %w", err)
}
```

I don't remember details but there are some issues with supporting `Scan(ctx, &models)`...

**Comment by Rheisen** [comment]
Gotcha, that worked! Thanks! I'll use this approach going forward :)
