### ISSUE TITLE
Is `RETURNING` supported in Postgres inserts?

### ISSUE THREAD

**Issue by lalotai** [uptrace/bun#411]
For some reason I cannot get the `RETURNING` clause appended to my Postgres query so I can use the last inserted primary id (I'm hoping to be able to use `account.AccountID` after the returning clause starts working):

```golang
_, err := db.NewInsert().
  Model(account).
  Returning("*").
  Exec(ctx)
```

Returns a query like this (without the `RETURNING *` clause):

```
INSERT INTO "accounts" ("account_id", "uid") VALUES (DEFAULT, 'c4uvnil9481e93skjcb0');
```

What am I missing? :(

---

```
github.com/uptrace/bun v1.0.21
github.com/uptrace/bun/dialect/pgdialect v1.0.20
github.com/uptrace/bun/driver/pgdriver v1.0.20
PostgreSQL 13.3 on x86_64-apple-darwin
```

**Comment by vmihailenco** [comment]
Try replacing `v1.0.20` with `v1.0.21` for all packages. See https://github.com/uptrace/bun/issues/401

**Comment by lalotai** [comment]
Wow, that did it. Thank you so much!
