### ISSUE TITLE
When marshaling to JSON, has many relation's field is null

### ISSUE THREAD

**Issue by Seldszar** [uptrace/bun#413]
Assuming the following sample:
```go
type Comment struct {
  ArticleID int64 `json:"-" bun:",pk"`
}

type Article struct {
  Comments []*Comment `json:"comments" bun:"rel:has-many"`
}

articles := make([]*Article, 0)

db.NewSelect().Model(&articles).Relation("Comments").Scan(context.background())

json.Marshal(articles)
```

If I query articles without comments, then marshal to JSON, the `comments` field will be `null` instead of an empty array.
Is it intended?

**Comment by vmihailenco** [comment]
That is how Go works - the slice is nil by default and is marshaled as JSON null. Changing that behavior is a lot of work that does not look worth it.

**Comment by Seldszar** [comment]
But if I query a "have many" relation, it should return an empty slice, no?

**Comment by vmihailenco** [comment]
Bun does not make a query when there is nothing to select.

**Comment by Seldszar** [comment]
I suppose that's most likely an issue with the JSON marshaler.
I thought this was an Bun issue not making an empty slice (`make(X, 0)`). But if that's not an issue, this is on my side in this case.
