### ISSUE TITLE
Use MySQL for `example/` is better.

### ISSUE THREAD

**Issue by j2gg0s** [uptrace/bun#42]
As the MySQL database server is the world's most popular open source database. 

Use MySQL for `example/` is better then SQLite.

**Comment by Codebreaker101** [comment]
Examples use sqlite in-memory database that allows you to run the examples without needed external database dependency. Additionally, since Bun works with any SQL database that has a go driver and dialect for it, only initialization is different between databases. And that could be as little as two lines of code.

``` diff
- sqldb, err := sql.Open("sqlite3", ":memory:?cache=shared")
+ sqldb, err := sql.Open("mysql", "root:pass@/test")

- db := bun.NewDB(sqldb, sqlitedialect.New())
+ db := bun.NewDB(sqldb, mysqldialect.New())
```

There is no practical use here for using mysql database for examples.

**Comment by vmihailenco** [comment]
As @Codebreaker101 correctly guessed, SQLIte was chosen so you can run examples without configuring anything or running a Docker container. Also it seems more fair this way for PostgreSQL users :)

But the tests are run for all 3 supported databases - https://github.com/uptrace/bun/blob/master/internal/dbtest/db_test.go#L26-L73

**Comment by j2gg0s** [comment]
If bun want to be cross database and be widely used, MySQL and PostgreSQL is our must support.

Consider that, bun is migrated from go-pg, bun with PostgreSQL is good enough.
However, bun with MySQL (special 5.7) has many bugs.

So, write examples with MySQL brings more help.

**Comment by vmihailenco** [comment]
It would be much more useful to run tests on MySQL 5.7 instead of MySQL 8. Examples are not very representative.

**Comment by j2gg0s** [comment]
@vmihailenco do we have any plan to add MySQL 5.7 to `internal/dbtest`.

**Comment by vmihailenco** [comment]
Yes, I think we need something like https://github.com/uptrace/bun/pull/50 (not tested)

**Comment by j2gg0s** [comment]
i run internal/dbtest in my local env, mysql prior version 8.0:
- does not support CTE
- does not support `where` without `from`
- notice system variable: [explicit_defaults_for_timestamp](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp)
- TIMESTAMP/DATETIME does not support time zone #48 , this block our usage with MySQL 5.7

**Comment by vmihailenco** [comment]
All should be fixed in master. Tests that use CTE are skipped on MySQL 5.
