### ISSUE TITLE
id=0 returns after creating record

### ISSUE THREAD

**Issue by bruteforce1414** [uptrace/bun#421]
I use the postgres driver.
But in db id=8 (correct), or any positive number)
Problem exists in v1.0.21, in v.1.0.20 all rigth
	
	if _, err := r.Tx.GetDB(ctx).NewInsert().Model(m).Exec(ctx); err != nil {
		return pkg_errors.NewDatabase(err)
	}
	
	model printing:
	2022/01/26 17:52:33 model {{} 0 Zieme, Cummerata and Franecki 2022-01-26 17:52:33.484212 +0500 +05 m=+44.572367001 
        2022-01-26 17:52:33.484212 +0500 +05 m=+44.572367001}

Possible, that problem exists in other operations

**Comment by vmihailenco** [comment]
Probably https://github.com/uptrace/bun/issues/401 . If that does not help, please re-open with a reproducer.
