### ISSUE TITLE
doc: require more detailed description of struct tags

### ISSUE THREAD

**Issue by j2gg0s** [uptrace/bun#423]
Maybe we need more detailed description of struct tags.

Such as:
`nullzero` will marshal as SQL `NULL`, but when dialect support DefaultPlaceholder, it will marshal as SQL `DEFAULT`.

In my case,
i can't find how to marshal zero value as `DEFAULT` before i read code.
This may be my own reason, not question of document.

**Comment by vmihailenco** [comment]
Thanks for the suggestion - I've updated the docs with your edit.
