### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by kkereziev** [uptrace/bun#431]
Hey, I have the following question- suppose we have many to many relation between tags and players and players also have relation with lets say account table. When I want to get the players for a specific tag is there a way to get the other relations for players, in my specific example to get the account relation for each player?

**Comment by kkereziev** [comment]
I found out the solution for my problem, but I think that [](https://github.com/uptrace/bun/issues/154) this is much needed.

**Comment by vmihailenco** [comment]
https://github.com/uptrace/bun/issues/154 is about convenience - it won't add new features. You can already use nested relations with `q.Relation("Some.Nested.Relation")`.
