### ISSUE TITLE
WARN: bun: missing `bun:",autoincrement" on Migration.ID and MigrationLock.ID field

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#457]
After upgrade from v1.0.21 to v1.0.24:

```
WARN: bun: missing `bun:",autoincrement" on Migration.ID field`
WARN: bun: missing `bun:",autoincrement" on MigrationLock.ID field`
```

**Comment by vmihailenco** [comment]
Thanks for the report. Looks like v1.1 already has the missing options so I will just add it to the v1.0.x branch as well. Overall, the warning is harmless.
