### ISSUE TITLE
WARN: bun: missing `bun:",nullzero" on Player.DeletedAt field` but I have it

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#458]
After upgrade from v1.0.21 to v1.0.24 although I have this line of code I still get the following console warning:

```go
DeletedAt     time.Time `bun:",soft_delete,nullzero"`
```

```
WARN: bun: missing `bun:",nullzero" on Player.DeletedAt field`
```

**Comment by vmihailenco** [comment]
Thanks for the report - I will improve the check. The warning is harmless.
