### ISSUE TITLE
Failed migrations

### ISSUE THREAD

**Issue by hhuseyinpay** [uptrace/bun#474]
Is it expected behavior to insert the migration to the database even if the migration fails? I think if the migration fails, it should not be inserted. Because I need to repeat the migration after fixing the issue.

<img width="1497" alt="Screen Shot 2022-03-03 at 15 27 17" src="https://user-images.githubusercontent.com/14811488/156564596-ab87796a-93c0-4fb5-a761-444864c156a4.png">

**Comment by vmihailenco** [comment]
Yes, that is intentional. Such way you can execute `rollback` to cleanup partially applied migration and re-apply the migration.

Alternatively, you can use transactional migrations which don't have such problem.

**Comment by braindev** [comment]
For those that might stumble on to this thread and still have troubles, don't forget to include the `migrate.WithMarkAppliedOnSuccess(true)` option when creating a migrator.  That's what tripped me up.

something like this:

```go
return migrate.NewMigrator(db, migrations, migrate.WithMarkAppliedOnSuccess(true))
```
