### ISSUE TITLE
Error on `context canceled`?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#476]
I'm using both `bunrouter` and `bun` and I'm very happy with them.

There is one thing I have noticed now: when the context is deleted (maybe because the client has stopped the call that bunrouter is handling) `bun` returns an error: `context canceled`.

Is this the correct way to handle it?

Do we need to return an error?

Or `nil`?

**Comment by vmihailenco** [comment]
>Is this the correct way to handle it?

AFAIK yes, that is an error returned by `context` package. Not sure what else we can do.

>Do we need to return an error?

`context canceled` is an error.

>maybe because the client has stopped the call that bunrouter is handling

Neither bunrouter nor bun cancel contexts or set a timeout on a context. It must be something else.
