### ISSUE TITLE
SCANONLY not working right

### ISSUE THREAD

**Issue by JohnKinyanjui** [uptrace/bun#478]
It seems bun is unable to scan fields with scanonly, i have tried several times:

The Struct:
type User struct {
	ID           int64     `json:"-"`
	UserId       uuid.UUID `json:"user_id" bun:",scanonly"`
        ChatId       uuid.UUID `json:"user_id" bun:",scanonly"`
	ProfileImage string    `json:"profile_image" bun:"profile_image"`
	UserName     string    `json:"username" bun:"username"`
	FullName     string    `json:"full_name" bun:"fullname"`
	PhoneNumber  string    `json:"phone_number" bun:"phone_number"`
	Password     string    `json:"password,omitempty" bun:"password"`
	Country      string    `json:"country" bun:"country"`
	CreatedAt    string    `json:"created_at" bun:"created_at,scanonly"`
}

The Result:
&{
0
00000000-0000-0000-0000-000000000000 https://res.cloudinary.com/johncloudinary12/image/upload/v1621913260/retailer_images/image_picker354608742150412363_asplqq.jpg jakes John 254234575141 
$2a$14$sArx/kafH7wOaKQEW3qeeu16VmJ0wFZyL1K6SlQ7VDvx85usdVZWy KE }

I believe the issue is coming from **scanonly**. I have tested **scanonly** with other fields and its not working right.
please check on it

**Comment by JohnKinyanjui** [comment]
![Capture](https://user-images.githubusercontent.com/52638680/156923289-74df168a-2cf0-4dba-8205-30110831fea7.PNG)

**Comment by vmihailenco** [comment]
Please provide a program that reproduces the problem.

**Comment by JohnKinyanjui** [comment]
sorry thats a bit hard, the code itself is massive, i was migrating from go-pg to bun and i just found some new bugs which i will continue to write them like also `bun:"type:uuid,default:uuid_generate_v4()"` is not working which was an alternative to it.

**Comment by vmihailenco** [comment]
My guess is that you should explicitly specify columns marked as `,scanonly`, for example, `NewSelect().ColumnExpr("user_id")`. But really, the issue should include a reproducer.
