### ISSUE TITLE
`DATETIME` before MySQL 8.0 does not support time zone.

### ISSUE THREAD

**Issue by j2gg0s** [uptrace/bun#48]
`In MySQL 8.0.19 and later, you can specify a time zone offset when inserting a TIMESTAMP or DATETIME value into a table. See Section 9.1.3, “Date and Time Literals”, for more information and examples.
`
Link: https://dev.mysql.com/doc/refman/8.0/en/datetime.html

mysqldialect append for `time.Time` should consider this.
https://github.com/uptrace/bun/blob/57ab844745cfc84bd902250ffd6042fe907f3fe9/dialect/append.go#L97

**Comment by vmihailenco** [comment]
:+1: It is not hard to customize `AppendTime` for MySQL 5.7, but first we need to fix the build.

**Comment by vmihailenco** [comment]
Should be fixed in v0.2.14
