### ISSUE TITLE
bun  migrator Bug when migrate action raise an error

### ISSUE THREAD

**Issue by xiayulu** [uptrace/bun#482]
Hello! Can bun auto generate migrateions?

I build web app using django before, I can migrate database table by :

```shell
python manage.py makemigrations
python manage.py migrate
```

When I read bun's document about migrations, I was confused:

Are files like `20210505110026_test_migration.go`  auto generated? If so, how can I do that?

Thanks for your reply.

**Comment by xiayulu** [comment]
After I Read some examples:

I find this example: https://github.com/uptrace/bun/tree/master/example/migrate

I try to migrate database table by following these steps:
1. I created a cmd and init file of migrations
![image](https://user-images.githubusercontent.com/41274826/158057231-2712fdbd-8eb0-4dcd-8974-d7e612671c09.png)

2. run cmd

```shell
go run .\bin\bun\main.go db create_go init_user
```
I successfully  create `20220313114734_init_user.go`

**Comment by xiayulu** [comment]
I find the BUG why step 5 did not create table users.
I run `go run .\bin\bun\main.go db migrate` for the first time, actually I get

```shell
[bun]  20:09:36.790   INSERT                5.283ms  INSERT INTO bun_migration_locks ("id", "table_name") VALUES (DEFAULT, 'bun_migrations') RETURNING "id"
[bun]  20:09:36.791   SELECT                1.067ms  SELECT * FROM bun_migrations
rated_at") VALUES (DEFAULT, '20220313120145', 1, DEFAULT) RETURNING "id", "migrated_at"
 [up migration] for user model
[bun]  20:09:36.795   CREATE TABLE          2.615ms  CREATE TABLE "users" ("id" BIGSERIAL NOT NULL, "name" uuid DEFAULT uuid_generate_v4(), "avatar" VARCHAR, "bio" VARCHAR, "score" BIGINT DEFAULT 0, "flag" BIGINT DEFAULT 0, "is_admin" BOOLEAN DEFAULT true, "email" VARCHAR, "password" VARCHAR, "phone" VARCHAR, "created_at" TIMESTAMPTZ DEFAULT current_timestamp, "updated_at" TIMESTAMPTZ DEFAULT current_timestamp, "deleted_at" TIMESTAMPTZ, PRIMARY KEY ("id"))          pgdriver.Error: ERROR: function uuid_generate_v4() does not exist (SQLSTATE=42883)   
_migrations')
panic: ERROR: function uuid_generate_v4() does not exist (SQLSTATE=42883)
```

After I remove  `uuid_generate_v4()` from filed `ID        int64 `bun:"id,pk,autoincrement, default: uuid_generate_v4()"``

I got 

```shell
[bun]  20:10:48.657   INSERT                 3.72ms  INSERT INTO bun_migration_locks ("id", "table_name") VALUES (DEFAULT, 'bun_migrations') RETURNING "id"
[bun]  20:10:48.659   SELECT                2.159ms  SELECT * FROM bun_migrations
[bun]  20:10:48.662   DELETE                2.646ms  DELETE FROM bun_migration_locks WHERE ("table_name" = 'bun_migrations')
there are no new migrations to run (database is up to date)
```

**Comment by vmihailenco** [comment]
>The migrator should verify migrate action, if there is no err, a migrate record can insert.

The migrator always marks the migration as applied so you can run `db rollback` to cleanup the database and then re-apply the migration.

>Are files like 20210505110026_test_migration.go auto generated?

No, you write migrations manually.

**Comment by vmihailenco** [comment]
I've updated the docs to mention this - https://bun.uptrace.dev/guide/migrations.html#migration-names
