### ISSUE TITLE
how to use in where in operator to bytea column

### ISSUE THREAD

**Issue by boojongmin** [uptrace/bun#483]
```go
c := make([][]byte, 3)
/*
skip code ....
*/

// (1)
sql.Where(f+" in (?)", c)
//(2)
sql.Where(f+" in (?)", bun.In(c))
```
select syntax is invalid when bytea column with in operator.
I try to (1) and (2) 

how I use in operator with bytea? 

thank you.

**Comment by vmihailenco** [comment]
Thanks for the report - this should be fixed by https://github.com/uptrace/bun/pull/484

**Comment by boojongmin** [comment]
@vmihailenco thank you for your fix.
