### ISSUE TITLE
Typo in document

### ISSUE THREAD

**Issue by Thunder33345** [uptrace/bun#486]
The document in [relations#belongs-to-relation](https://bun.uptrace.dev/guide/relations.html#belongs-to-relation) seems to include a typo

It shows `join=` when it's probably supposed to be `join:`
> 	Profile   *Profile `bun:"rel:belongs-to,join=profile_id=id"`

Excuses if I made this issue under the wrong place, while [CONTRIBUTING](https://github.com/uptrace/bun/blob/06b0e34c092f00c816a2a7fb3a4665ef6cc51c90/CONTRIBUTING.md#documentation) says it should go to [bun-docs](https://github.com/go-bun/bun-docs), but said repo does not exist

**Comment by vmihailenco** [comment]
Thanks, I've fixed the docs.
