### ISSUE TITLE
Should there be a way to migrate to a specific target?

### ISSUE THREAD

**Issue by smyrman** [uptrace/bun#49]
I want to suggest add a method to `migrate.Migrations` to migrate to a specific group number / target. E.g.

```go
func(m *Migrations) MigrateTo(ctx context.Context, db *bun.DB, target int64) error
```

Or an example on how to achieve this without this method.

Use-case:
1. Deploy new API that require the latest schema version (e.g. `5`).
2. Find there is a bug in the API, and roll it back to a previous version that requires an earlier db schema (e.g. `3`).
3. Run to migrate to group `3` (automatically rollback any migrations with a higher group number, and apply any migrations with a lower or eqaul group number).

Assumes that migrations group numbers can be set from the source.

**Comment by vmihailenco** [comment]
>Assumes that migrations group numbers can be set from the source.

Currently you can't set a group number from the source. Group numbers are generated automatically whenever you run migrations.

In theory it is possible to add some way to manually override group numbers (though nothing obvious comes to mind), but then you could also merge migrations together if they must be run as one. Or just delete the migrations you don't want to apply.

>Should there be a way to migrate to a specific target?

I am inclined to say no. At least until you come with a more detailed plan :) Right now group numbers is just an implementation detail and they don't have much meaning / purpose.

**Comment by smyrman** [comment]
The motivation is to have a declarative description of the entire application deployment, including the database version, similar to what we currently do with Gorm (v1) and Gormigrate.

In our current set-up with Kustomize, we have a migration _job_ that are deployed alongside every update to our various micro-services. This job ensures that the database is migrated (up or down) to a _specific_ version that's specified as a kustomize variable. This should happen no matter the state of the initial database. For cases where a down migration _isn't safe_, then we would leave it empty (or in sine cases error).

Perhaps relying on group numbers isn't the best idea, or perhaps bun/migrations isn't the right choice (we could use bun without bun migrations). It's also not important for this to be part of the starter-kit, if included. If there was a RollbackAll (ignoring the group IDs), that _would_ probably help because we could find our _target_ in the migration list, split it in two, migrate the first half, and rollback the second half.

**Comment by vmihailenco** [comment]
I guess I misunderstood. Assuming that there are 2 groups with 2 migrations in each group:

```
group1: migration1, migration2
group2: migration3, migration4
```

And you want to migrate to migration1, then Bun should rollback both groups and then apply migration1:

```shell
bun db migrate migration1
reverting group1: migration1, migration2
reverting group2: migration3, migration4
applying migration1
```

Is that correct?

**Comment by smyrman** [comment]
> And you want to migrate to migration1, then Bun should rollback both groups and then apply migration1:

I think this approach is _only_ an option if groups are specified in the source. It's not an option if groups are generated run-time.

When groups are generated run-time, then the groups on prod can be significantly different from those on a  dev or staging environment. Thus upgrading a dev or staging environment to prod that includes a modest db rollback, could have unforeseen side-effects. Especially so as prod is generally more seldom applied, and the groups might be larger (causing longer rollbacks and potential data loss).

What I am doing for now, is that I am writing my own Migrator type (light-weight copy of `migrate.Migrations`) (still relying on `migraget.Migrate`) with the logic I think is relevant. If it works out well, I can share it back.

**Comment by vmihailenco** [comment]
>PS! I will probably completely ignore groups for now.

Yeah, it sounds like you just don't want groups at all. Perhaps we could add an option to disable groups which will cause Bun to create a group for each migration.

**Comment by smyrman** [comment]
From my experience on writing a _custom_ migrator, it would be very nice if there where a few more public methods on `migrate.Migrations` type, so that the custom migrator could actually be written _on top_ of it.

E.g. non-locking methods:
```go
func (Migrations) MarkDown(name string) error
func (Migrations) MarkUp(name string) error
func (Migrations) Complete() (map[string]struct{}, error)
```

As a cleanup, it could be possible to "deprecate" the current `Migrate`, `MarkComplete` and `Rollback`, replacing them with a built-in "default" Migrator type that retains current semantics.



```go
myMigrations.Init(ctx, db)
myMigrations.Migrate(ctx, db)
myMigrations.Rollback(ctx, db)
myMigrations.Status(ctx, db)
```

You would write:

```go
myMigrations.Init(ctx, db) // alternatively call automatically inside migrator.
migrator := migrate.NewMigrator(myMigrations, db)
migrator.Migrate(ctx)
migrator.Rollback(ctx)
migrator.Status(ctx)
```

Can of course _keep_ the methods on `migrate.Migrations` for backwards compatibility (but document them as deprecated):

```go
// Deprecated: use Migrator instead.
func (m Migrations) Migrate(ctx context.Context, db *bun.DB) error {
    return NewMigrator(m, db).Migrate(ctx)
}

```

**Comment by smyrman** [comment]
> Yeah, it sounds like you just don't want groups at all. Perhaps we could add an option to disable groups which will cause Bun to create a group for each migration.

It could work, but I suppose the "migrator" part of `migrate.Migrations` risk becoming very complex if it needs to handle all sorts of different options. It also doesn't, by itself, solve the problem of migrating to a specific version.

**Comment by smyrman** [comment]
I.e. I think I would be quite happy with a solution that just made writing a _custom_ migrator easier (leaving the default implementation simple).

**Comment by vmihailenco** [comment]
As I understand the main idea is to separate migrations (collection of migrations) and migrator (configurable migration runner). And then expose more API to work with migrations. That sounds reasonable and I think we should do it before releasing v1.0 and locking the API.

@Codebreaker101 already works on some changes to make migrations code cleaner and more robust - let's wait until his changes are in and then decide what to do next.

**Comment by smyrman** [comment]
That's a good summary of my proposed solution. The goal is still the same as described in the initial issue. Either way, waiting for related work before deciding seams like a good idea 👍 

Thanks for a quick response on the issue.

**Comment by vmihailenco** [comment]
@smyrman please check the new API in [v0.3.0](https://github.com/uptrace/bun/tree/master/migrate) and let me know which methods should be exposed.

**Comment by smyrman** [comment]
So, the first thing that is needed, is a sorted list of _all_ migrations (names are enough, but an actual type allows printing information such as when it was created).

Secondly, it's necessary to know which migrations are _completed_.

From what I can see, this information can be fetched from the `Migrator.Status` response, but in my view, the return type is a bit bloated. A simple `MigrationSlice` as a response would do, where `MigratedAt` and `Group` is updated inside the list based on the select completed response.

To get the other information present in the `MigratorStatus` in v0.3.0, simply add methods `MigrationSlice.Complete()`, `MigrationSlice.NoComplte()`, `MigrationSlice.LastGroup()`.

 Finally, what's needed is methods to interact with the migration table. This means:
 
 - Present: Lock table (Migrator.Lock)
 - Present: Unlock table (Migrator.Unlock)
 - Missing: Mark single migration as done (must work after calling Lock)
 - Missing: Mark single migration as not done (must work after calling Lock)
 
 PS! It's possible to create a counting lock if you don't want to expose "mark as done" without locking. the option to mark a migration as done without
 
 A counting lock works something like this....
 
 ```go
 type Migrator struct{
    ...
    mu sync.Mutex
    locks int
}
 
 func (m Migrator) Lock(ctx context.Context) error{
      m.mu.Lock()
      defer m.mu.Unlock()
      if m.locks == 0 {
         // lock table or return error
      }
      m.locks++
 }

func (m Migrator) Unlock() {
      m.mu.Lock()
      defer m.mu.Unlock()
      if m.locks <= 1 {
         // unlock table or return error
         m.locks = 0
         return
      }
      m.locks--
 }
 ```

**Comment by smyrman** [comment]
PS! important detail for the counting lock; don't change the locks count if tableLock / tableUnlock returns an error.

**Comment by smyrman** [comment]
PS! An alternative name to `MigrationSloce.LastGroup` (because it can be confusing what a group is), would be `MigrationSlice.LastApplied`.

**Comment by vmihailenco** [comment]
Most of this should be addressed by https://github.com/uptrace/bun/pull/70. Let's open a new issue if you find anything else.
