### ISSUE TITLE
Possibility to use more complex join with custom has-many relationship.

### ISSUE THREAD

**Issue by Skandalik** [uptrace/bun#495]
I was working today with specific case and I hope that you might be able to help me.
I created a custom structure for the sake of example.

Overview:

There are multiple `Persons` and multiple `Books`. Each person can have a book that comes from the same table and books belonging to the person are saved in the `PersonBook` table with specific type.
```
type Person struct {
	bun.BaseModel `bun:"table:person,alias:p"`

	ID      int `bun:",pk,unique,autoincrement"`
	Name    string
	Surname string

	SciFi    []*PersonBook `bun:"rel:has-many,join:id=person_id"`
	Thriller []*PersonBook `bun:"rel:has-many,join:id=person_id"`
	Fantasy  []*PersonBook `bun:"rel:has-many,join:id=person_id"`
	Drama    []*PersonBook `bun:"rel:has-many,join:id=person_id"`
}

type PersonBook struct {
	bun.BaseModel `bun:"table:person_book,alias:pm"`

	PersonID int     `bun:",pk"`
	Person   *Person `bun:"rel:belongs-to,join:person_id=id"`
	BookID   int     `bun:",pk"`
	Book     *Book   `bun:"rel:belongs-to,join:book_id=id"`

	BookType BookEnum
}

type Book struct {
	bun.BaseModel `bun:"table:book,alias:b"`

	ID    int `bun:",pk,unique,autoincrement"`
	Title string
	Type  BookEnum
}

type BookEnum string

const (
	BookEnum_SciFi    = "sci-fi"
	BookEnum_Thriller = "thriller"
	BookEnum_Fantasy  = "fantasy"
	BookEnum_Drama    = "drama"
)
```

I want to be able to fetch every `PersonBook` individually when using `Relations` e.g:
```
db.NewSelect().
	Model(&persons).
	Relation("SciFi").
	Relation("Thriller").
	Relation("Fantasy").
	Relation("Drama").
	Scan(context.Background())
```

I know I can do a workaround such as this, but it's not convenient for a long run (whenever I need to fetch the `Relation` I need to add query function for custom fetch).
```
db.NewSelect().
	Model(&persons).
	Relation("SciFi", func(q *bun.SelectQuery) *bun.SelectQuery {
		return q.Where("book_type = ?", "sci-fi")
	}).
	Relation("Thriller", func(q *bun.SelectQuery) *bun.SelectQuery {
		return q.Where("book_type = ?", "thriller")
	}).
	Relation("Fantasy", func(q *bun.SelectQuery) *bun.SelectQuery {
		return q.Where("book_type = ?", "fantasy")
	}).
	Relation("Drama", func(q *bun.SelectQuery) *bun.SelectQuery {
		return q.Where("book_type = ?", "drama")
	}).
	Scan(context.Background())
```

I was thinking about having something like this, where `book_type` is additional join filter on sub-entity.
So the SQL result would look like `LEFT JOIN person_book pb ON pb.person_id = person.id AND book_type='sci-fi'`
```
type Person struct {
	bun.BaseModel `bun:"table:person,alias:p"`

	ID      int `bun:",pk,unique,autoincrement"`
	Name    string
	Surname string

	SciFi    []*PersonBook `bun:"rel:has-many,join:id=person_id,join_custom:book_type='sci-fi'"`
	Thriller []*PersonBook `bun:"rel:has-many,join:id=person_id,join_custom:book_type='thriller'"`
	Fantasy  []*PersonBook `bun:"rel:has-many,join:id=person_id,join_custom:book_type='fantasy'"`
	Drama    []*PersonBook `bun:"rel:has-many,join:id=person_id,join_custom:book_type='drama'"`
}
```

If you think it's a good idea, I might take a time and try to do a PR for this.

**Comment by vmihailenco** [comment]
What you suggest looks nice in this specific case, but it does not scale / supports more complex cases.

I think something like this makes more sense, because it allows to use existing API to build queries:

```go
func personScifiBooks(q *bun.SelectQuery) *bun.SelectQuery {
	return q.Relation("SciFi", func(q *bun.SelectQuery) *bun.SelectQuery {
		return q.Where("book_type = ?", "sci-fi")
	}).
}

q  := db.NewSelect().
	Model(&persons).
	Apply(personScifiBooks).
	Apply(personThrillerBooks)
```

But my experiences tells that it is much easier to have a single method responsible for generating the query rather than many small helpers - see https://bun.uptrace.dev/guide/complex-queries.html#query-generation

**Comment by Skandalik** [comment]
Yeah, but having those functions results in some relations being fetched using `Relation` method with just name of the relation and some using `Relation` method function that modifies query as an alternative.
When anyone would like to fetch nested there's a necessity to use `Relation("Books.SciFi", scifiBooksFn)`, instead of simple `Relation("Books.SciFi")`.
Currently it's been done by me in the project just like you said - having single function for multiple relations of this kind.
But having additional tag like `join_custom` or `join_column` that simply adds column to already existing join would resolve those kind of problems and opens up a possibility to use multiple simple joins in single tag, when anyone has database modeled this way.

If you have anything in mind, we could discuss it and I would love to participate, and make a contribution.

**Comment by vmihailenco** [comment]
@Skandalik PR is welcome. I expect something like this to be supported

```go
	Drama    []*PersonBook `bun:"rel:has-many,join:id=person_id,join_on:book_type='drama',join_on:col > 123"`
	Some    []*PersonBook `bun:"rel:has-many,join:id=person_id,join_on:book_type IN ('foo', 'bar')"`
```

I am not too happy to see SQL in struct tags but I can live with that.

**Comment by Skandalik** [comment]
Yeah, it's a compromise, but this is a choice between ease of use and repeatability of code. Thanks for discussion, I'll work on that in spare tim!

**Comment by aep** [comment]
#536 might be the same request ?
