### ISSUE TITLE
CHANGELOG.md is not updated to 1.1.2

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#501]
CHANGELOG.md is not updated to 1.1.2:

![image](https://user-images.githubusercontent.com/41120635/160410879-c3dbe471-4eee-4a71-9418-6e678e75b4b1.png)

**Comment by vmihailenco** [comment]
I've updated the changelog.

**Comment by frederikhors** [comment]
Now is missing 1.1.3. It think something is broken.

**Comment by frederikhors** [comment]
![image](https://user-images.githubusercontent.com/41120635/160582546-ab3b8b8e-fad2-4c70-bd73-4bd1d6be92f9.png)
