### ISSUE TITLE
ModelTableExpr table alias not used for selecting columns

### ISSUE THREAD

**Issue by efournival** [uptrace/bun#504]
Hey,

First, thank you for your amazing work on Bun.
I'm currently using it instead of Gorm in production without any issue.

However, I think I just encountered a bug with `ModelTableExpr` which is not replacing the table's alias when selecting columns.

```
type Treatment3DScan struct {
  ID uuid.UUID
  UserID uuid.UUID
  TreatmentID uuid.UUID
  ...
}

treatment3DScan := &Treatment3DScan{}
_ = db.
  NewSelect().
  Model(treatment3DScan).
  ModelTableExpr("treatment_3d_scans").
  Where("id = ?", id).
  Scan(context.Background())
```

Will generate the following query and cause an error:
```
[bun]  11:35:26.896   SELECT                  735µs  SELECT "treatment3d_scan"."id", "treatment3d_scan"."user_id", "treatment3d_scan"."treatment_id" FROM treatment_3d_scans WHERE (treatment_id = 'xxx-xxx-xxxxx-xxx') 	  pgdriver.Error: ERROR: missing FROM-clause entry for table « treatment3d_scan » (SQLSTATE=42P01)
```

My table's name is `treatment_3d_scans` and not `treatment3d_scan` as generated by Bun.
Name generation is not really an issue, otherwise it would be opinionated (should we put an underscore before a digit or not?).
I don't want to use ``bun.BaseModel `bun:"table:treatment_3d_scans"` `` in my model to ensure clear separation between business logic and technical parts (i.e. I don't want to change my models if I switch from Bun to Gorm or whatever else in the future).

Workaround:
```
_ = db.
  NewSelect().
  Model(treatment3DScan).
  ModelTableExpr("treatment_3d_scans AS treatment3d_scan").
  Where("id = ?", id).
  Scan(context.Background())
```

Is it a real bug or am I using Bun wrong? Thank you

**Comment by efournival** [comment]
Thank you but I'd like to challenge the fact that's "how it is supposed to work", why would `ModelTableExpr` not override the alias? You are suggesting setting the wrongly generated table name as the alias in `ModelTableExpr`, but a better solution, in my opinion, would be to set the table name used to select columns too.

I know I can define `bun.BaseModel` on the model but I don't want to, as models are part of my business logic.
I'm using a [clean architecture](https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html) design.

**Comment by moethu** [comment]
I'd like to second that, I'm having the exact same issue. specifying an alternative table name in the struct doesn't work for a use-case where one needs to support dynamic table names. The behavior of `ModelTableExpr` doesn't seem to be consistent to me. Some examples:

```golang
db.NewCreateTable().Model((*device.DeviceMeasurement)(nil)).ModelTableExpr(table_name).IfNotExists().Exec(ctx)
```
creates a new table successfully with the alternative table name specified in `table_name`.

```golang
var data []device.DeviceMeasurement
db.NewInsert().Model(&data).ModelTableExpr(table_name).Exec(ctx)
```
inserts data into the table with the alternative table name specified in `table_name`.

```golang
var data []device.DeviceMeasurement
db.NewSelect().Model(&data).ModelTableExpr(table_name).Scan(ctx)
```
uses `device_measurement` as a table name, doesn't use the alternative table name specified in `table_name`.

Am I misunderstanding how `ModelTableExpr` is supposed to be used? I do not have any table alias or name set in the struct.

**Comment by vmihailenco** [comment]
I understand the sentiment, but:
- it is hard to, e.g. you would need to parse the alias from `ModelTableExpr`
- always using the same Model alias in `ModelTableExpr` is enough in most case.

>Am I misunderstanding how ModelTableExpr is supposed to be used? I do not have any table alias or name set in the struct.

I would recommend to set an alias in the struct and use it in `ModelTableExpr`. The behavior you suggest makes sense, but can't be easily implemented.

**Comment by moethu** [comment]
Thanks, totally fine with me. A quick note in the docs would have saved me quite some time figuring this out.

**Comment by vmihailenco** [comment]
Update the docs - https://bun.uptrace.dev/guide/models.html#modeltableexpr
