### ISSUE TITLE
How to exclude certain columns when updating 

### ISSUE THREAD

**Issue by SlimskiGM** [uptrace/bun#508]
Hi, 

First of all, thank you for the amazing work that you guys are doing! 

I'm currently working on an update query that excludes certain columns, I did find a feature that provides excluding them by using ExcludeColumn. However, I was wondering if there's a feature like "updatable" in JPA, where if you set 'false' to the column that you don't mean to update, it doesn't when updating. Thank you again!

here's the reference for this feature : https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/Column.html

<img width="640" alt="image" src="https://user-images.githubusercontent.com/101081080/161882187-1854fb4e-ee4a-4e78-bd04-e096a90b45e6.png">

**Comment by vmihailenco** [comment]
We don't have such feature, but there is a similar request to add `,selectonly` / `,selectable` so perhaps we should something similar for updates - see https://github.com/uptrace/bun/issues/374

I like that with `updatatable` / `selectable` we can combine options together like `,selectable,updatable` etc.
