### ISSUE TITLE
"undefined: feature.InsertTableAlias" when installing pgdialect

### ISSUE THREAD

**Issue by sbward** [uptrace/bun#52]
Hi, it appears the latest release introduces an issue for `github.com/uptrace/bun/dialect/pgdialect`

```
go get github.com/uptrace/bun/dialect/pgdialect
# github.com/uptrace/bun/dialect/pgdialect
../../../go/pkg/mod/github.com/uptrace/bun/dialect/pgdialect@v0.2.13/dialect.go:29:3: undefined: feature.InsertTableAlias
```

**Comment by vmihailenco** [comment]
Seems to be working for me. Please make sure all Bun dependencies in go.mod file have the same version:

```
	github.com/uptrace/bun v0.2.13
	github.com/uptrace/bun/dialect/pgdialect v0.2.13
	github.com/uptrace/bun/driver/pgdriver v0.2.13
	github.com/uptrace/bun/extra/bundebug v0.2.13
	github.com/uptrace/bun/extra/bunotel v0.2.13
```

**Comment by sbward** [comment]
🤦 Thanks @vmihailenco, my versions were not lined up in the go.mod, working fine now. This might become a common gotcha, worth mentioning in the docs somewhere.

**Comment by sbward** [comment]
Actually it might be good to make the plugin modules explicitly mark their dependency on the main bun module with the same version.

So for example in `bun/dialect/pgdialect/go.mod` it should say
```
require github.com/uptrace/bun v0.2.13
```

Currently it says `v0.1.1` instead of `v0.2.13`
