### ISSUE TITLE
v1.1.4 breaks my boolean fields

### ISSUE THREAD

**Issue by tsmethurst** [uptrace/bun#523]
Heya! Thanks for your excellent work as always <3

I'm updating GoToSocial to step the Bun and dialect versions we're using from v1.0.20 to v1.1.4.

Mostly looks great (couple of tweaks I need to make), but I can't figure out how to get my boolean defaults working properly again.

One of our structs has a field that look like this:

```
	Avatar            bool             `validate:"-" bun:",notnull,default:false"`
```

With previous Bun versions, the above was created in the db (sqlite) as:

```
"avatar" BOOLEAN NOT NULL DEFAULT false
```

which is perfect, and worked great.

Now with the automatic addition of the `nullzero` tag, we get NOT NULL CONSTRANT errors inserting structs that have 'avatar' set to 'false'.

Is it possible to get the old behavior back, without using bool pointers?

Thanks!
tobi

**Comment by tsmethurst** [comment]
Just some additional info: when I step to v1.1.3 instead of v1.1.4 everything works great and as desired, so it's definitely the new `nullzero` default that's doing it I think...

**Comment by vmihailenco** [comment]
Hey @tsmethurst,

Why not to remove `default:false` then? It looks like you don't benefit from it, because Bun will never generate a `NULL` / `DEFAULT` value.

In v1.1.4 we made change to automatically apply `nullzero` when you have `default:something` option, because otherwise the default is just ignored.

**Comment by tsmethurst** [comment]
Ah okay, thank you! We just need to tidy up our models in GoToSocial then :)
