### ISSUE TITLE
Getting randomly EOF error

### ISSUE THREAD

**Issue by xhkocatepe** [uptrace/bun#525]
We receive sometimes an EOF error from bun as ` *errors.errorString: EOF` .
It is important that we have get issue `sometimes` ; same query, same db, same data, sometimes return data, but sometimes get `EOF` error. 
We get a workaround solution for using retry policy. We try to run same query until we successfully get data from db.

**Is there any real solution for this issue?**

PS:If it is necessary, I can share part of query.

**Comment by xhkocatepe** [comment]
Hello Everyone :) Is there any response?

**Comment by hhuseyinpay** [comment]
Which driver do you use? If you use the pgdriver, there is a hint in [the documentation ](https://bun.uptrace.dev/postgres/#debugging)

**Comment by xhkocatepe** [comment]
yeah we are using pgdriver 1.0.19. It is not working shared file from you.

**Comment by vmihailenco** [comment]
Closing, because there is no way to reproduce the problem. Please re-open if you have more details.

**Comment by xhkocatepe** [comment]
We can reproduce the problem many times. What kind of details dou you want?

**Comment by htdvisser** [comment]
I've been able to reproduce this issue: https://gist.github.com/htdvisser/fe1145e832fe2f323ee609e866fb59be

I'm investigating further and will try to contribute a fix.

**Comment by hypnoglow** [comment]
We still getting a lot of random EOFs with the 1.1.9 bun version. I have no reproducer though at this point.
