### ISSUE TITLE
duplicate key violation on autoincrement after loading fixture

### ISSUE THREAD

**Issue by jessdwitch** [uptrace/bun#528]
If you load a fixture and then try to insert into a table, you can get a `duplicate key value violates unique constraint` error. After loading the fixture, bun doesn't resync the primary key sequence, so DEFAULT pkey inserts are impossible.

Something like `SELECT setval('id_seq', (SELECT MAX(id) FROM table));` needs to be run after loading the fixture to bring it back in sync.

**Comment by jessdwitch** [comment]
Oh! I have a sort of XY problem. The table wasn't being initialized correctly because I was loading the fixtures in table-driven tests and the loading wasn't playing nice with the concurrency. I guess I'm not sure if that's really a bug then, since I don't know that I expect fixtures to be able to load concurrently anyway.

**Comment by codeliger** [comment]
I don't think it was a concurrent problem I am having the same issue. If you use fixtures with fixed ids and not `_id: id1` the sequence is not automatically updated. This is really annoying for unit tests and needs a manual solution. It should definitely be a feature when calling `fixture.Load`. The struct tag `autoincrement` should be used to identify this is a sequence and make the appropriate sequence update.
