### ISSUE TITLE
Closing transactions

### ISSUE THREAD

**Issue by antipopp** [uptrace/bun#530]
Coming from go-pg I was used to manage transactions with this style of code:

```golang
tx, err := db.Begin()
if err != nil {
 log.Fatal(err)
}
defer tx.Close()
```

On Bun I realized there is no `Close()` method and I was wondering what the best approach was. Should I use the context to manage transactions? I'm feeling lost, and the migration guide doesn't mention transactions.

**Comment by vmihailenco** [comment]
We provide [db.RunInTx](https://github.com/uptrace/bun/blob/master/db.go#L391-L415) - check the code to see how we are doing it.

**Comment by antipopp** [comment]
I see, thanks for the example! Maybe add a hint to it to the migration from go-pg article?
