### ISSUE TITLE
[Bug] Error in parsing time with time zone from postgresql to time.Time (Related to #225)

### ISSUE THREAD

**Issue by Vanclief** [uptrace/bun#537]
I am having exactly the same issue as presented at https://github.com/uptrace/bun/issues/225

I know this should been fixed, but for some reason I am having the same error

```
	sqldb := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(dsn)))
	db := bun.NewDB(sqldb, pgdialect.New())
	
	...
	type VerificationCode struct {
	bun.BaseModel `bun:"table:verification_codes"`

	Destinatary string    `bun:",pk" json:"destinatary"`
	Method      string    `json:"method"`
	Expiration  time.Time `json:"expiration"`
	Hash        []byte
        }
        
        ...
       vc.Expiration = time.Now()
       _, err = db.NewInsert().Model(&vc).Exec(context.Background())
	
	...
	
        existingVC := new(models.VerificationCode)
	err := db.NewSelect().Model(existingVC).Where("destinatary = ?", request.Destinatary).Scan(context.Background())
```

Error:
`parsing time "\xff\xff\xff\x00-12-31 17:23:24-06:36:36 BC": extra text: "-06:36:36 BC"`

**Comment by fterrag** [comment]
I'm having the same issue. The column type is timestamptz.

**Comment by vmihailenco** [comment]
Please provide the program that reproduces the problem.

**Comment by Vanclief** [comment]
Apologies, I was unable to reproduce this issue outside my code base. 
So I will close this and reopen if I manage to isolate it
