### ISSUE TITLE
Support Pgx Pool 

### ISSUE THREAD

**Issue by nooize** [uptrace/bun#539]
pgx driver have pool package
github.com/jackc/pgx/pgxpool

it would be great to be able to use it 
as an alternative to a single connection

use case

```
sqldb := stdlib.OpenDBPool(*config)
db := bun.NewDB(sqldb, pgdialect.New())
```

**Comment by vmihailenco** [comment]
pgxpool is not compatible with the pool from database/sql.

**Comment by zekth** [comment]
https://github.com/jackc/pgx/pull/1718 this solves the compatibility issue. Once released I'd say it would be good to have it in the docs.

**Comment by zekth** [comment]
@vmihailenco This feature has been released in `pgx` . We're using it in production since november and haven't noticed any issue. Do you think we should update the bun doc website to document how to wire pgx pool with bun?

**Comment by wagnerSalvador** [comment]
@zekth I would really appreciate it if there were documentation on this

**Comment by maxdml** [comment]
@zekth +1 please could you describe how you did it?

**Comment by vmihailenco** [comment]
Done: https://bun.uptrace.dev/postgres/#pgx

**Comment by zekth** [comment]
Sorry the notifications slipped under my radar. Thanks @vmihailenco for the doc update
