### ISSUE TITLE
View migrator feature?

### ISSUE THREAD

**Issue by smyrman** [uptrace/bun#54]
So far, most of the logic I have seen for handling migrations, is written to handle table creation. But database views are also a very powerful concept that is relevant to database related development as it can greatly simplify the database queries in the application.

Views are different from most tables in that you never _alter_ a view; you drop it and recreate it. However, it is still useful to describe multiple _versions_ of a view, so that you can "migrate" to a specific view version. While doing so, you don't want to drop and recreate all the intermediate view versions.

So a "migrator" for a view would, instead of tracking "applied" migrations, track only a single version _per view_ (or group of views). If the applied version does not match the target version, run the "target" migration "up". We can assume this migration starts with a `DROP VIEW x IF EXISTS;` before creation.

The approach can also be used to manage _materialized views_.

Having a separate migration concept for view could be a real power feature. If it's useful to include in the scope of `bun` or `bun/migrate` is a completely different question, so please feel free to reject this.

**Comment by smyrman** [comment]
> We can assume this migration starts with a DROP VIEW x IF EXISTS; before creation.

Or maybe a more accurate approach.. run `down` on the _applied_ migration, the `up` for the target migration.

**Comment by vmihailenco** [comment]
It is hard to tell whether all (supported) dbs behave the same, but even then being too smart with migrations does not sound like a good idea. I think that rules for running migrations must be simple and consistent. We should not (and likely can't) introduce migration-specific rules.

I personally never had problems with VIEWs and Postgres. The only catch is that you need to re-create them manually whenever base table changes, but it is pretty simple to do with `CREATE OR REPLACE` or `DROP+CREATE`.

>While doing so, you don't want to drop and recreate all the intermediate view versions.

But why? Just to save few queries? It does not seem worth optimizing...

**Comment by smyrman** [comment]
Let's close this.
