### ISSUE TITLE
Where are the Postgresql data types?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#540]
https://bun.uptrace.dev/postgres/data-types.html is broken (404).

Where are the Postgresql data types?

**Comment by ionling** [comment]
I can visit that page normally

**Comment by vmihailenco** [comment]
The page redirects to https://bun.uptrace.dev/postgres/postgres-data-types.html

**Comment by frederikhors** [comment]
I'm not crazy:

![image](https://user-images.githubusercontent.com/41120635/170451959-a67c6931-4a9c-49e1-8b0c-132f985e4e17.png)

This happens if you click from https://bun.uptrace.dev/guide/custom-types.html#conclusion:

![image](https://user-images.githubusercontent.com/41120635/170452011-97965f4c-9eec-4fb7-9321-daad79e6c1ac.png)

Anyway I cannot find a table like the one on go-pg:

![image](https://user-images.githubusercontent.com/41120635/170452217-188a822f-55cf-4ea7-a9cd-48e60bbecde0.png)
