### ISSUE TITLE
Delete queries "require at least one where" when trying to delete all rows from a table

### ISSUE THREAD

**Issue by Rheisen** [uptrace/bun#544]
In instances where you desire to delete all the records in a table, the SQL syntax would be something like:

```
DELETE FROM address_list;
```

Intuitively, that seems like it would translate over to bun as something like this:

```
addressList := h.sqlClient.DB().NewDelete().Model(
    &dbmodel.AddressList{},
)
if _, err := addressList.Exec(ctx); err != nil {
    return err
}
```

However, doing so returns an error: `bun: Update and Delete queries require at least one Where`

What is the recommended way for building a query to delete all rows in a table?

**Comment by vmihailenco** [comment]
You should prefer using `TRUNCATE`, but adding something like `Where("1")` should work too.
