### ISSUE TITLE
String representation of `bun.SelectQuery`

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#549]
I cannot find on docs and on this Github repo a way to have the query's string representation.

I need to test that many cases (really many because we are exposing columns with possible `OR`, `AND` and `NOT` logical operators) are correctly generating SQL queries.

So I think to add many tests to check if the methods we have generate correct final SQL code.

Is there a way to do this?

If I had a way to generate the final SQL string I could just compare them in tests. End.

I searched the old `go-pg` repository and it seems possible to do this: https://github.com/go-pg/pg/issues/1366#issuecomment-659263194.

**Comment by oderwat** [comment]
I thought I want to have this too and found this:

```go
	q := db.NewSelect().Model((*Image)(nil)).
		ColumnExpr("COUNT(*) AS ?", bun.Ident("cnt")).
		ColumnExpr("SUM(Size) AS ?", bun.Ident("bytes"))
	var buf []byte
	buf, err = q.AppendQuery(schema.NewNopFormatter(), nil)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(buf))
```

```sql
SELECT COUNT(*) AS ?, SUM(Size) AS ? FROM "images" AS "image"
```

**Comment by frederikhors** [comment]
I tried. Thanks. It works partially.

For example, if I use this code:

```go
query.Where("team_id ? ?", bun.Safe(getStringComparison(input.TeamID)), where.TeamID.Eq)
```

it prints: `(team_id ? ?)` and not `(team_id = '123')`.

Can you verify?

**Comment by oderwat** [comment]
This uses the NopFormatter which I suppose to not do any formatting. 

Maybe try something like that. I did not dig so far yet.
```go
q.AppendQuery(schema.NewFormatter(sqlitedialect.New()), nil)`
```
