### ISSUE TITLE
func (*Tx) CopyFrom/CopyTo Support similar to go-pg

### ISSUE THREAD

**Issue by qinxinxi** [uptrace/bun#559]
I see go-pg has support for  func (*Tx) CopyFrom/CopyTo  [https://pkg.go.dev/github.com/go-pg/pg#Tx.CopyFrom], Any plans to add similar support for this in uptrace/bun func (tx Tx) ?

**Comment by vmihailenco** [comment]
See https://bun.uptrace.dev/postgres/copy-data.html
