### ISSUE TITLE
Write/find some script that bump versions/dependencies

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/bun#56]
It might be good to make the plugin modules explicitly mark their dependency on the main bun module with the same version.

So for example in bun/dialect/pgdialect/go.mod it should say

```
require github.com/uptrace/bun v0.2.13
```

Currently it says v0.1.1 instead of v0.2.13

**Comment by sbward** [comment]
What is the goal of having multiple modules here? It seems that maybe having just one module containing everything might be a good idea.

**Comment by vmihailenco** [comment]
They all have different dependencies that some of us don't need - mysql/pg/sqlite dialect, YAML etc.

**Comment by Codebreaker101** [comment]
based on #74  this _oneliner_ integrates staging check
``` sh
[ $(git --no-pager diff --name-only --staged | wc -l)  = "0" ] && \
  go mod edit -require github.com/uptrace/bun@v$(VERSION) dialect/pgdialect/go.mod && \
  go mod edit -require github.com/uptrace/bun@v$(VERSION) dialect/mysqldialect/go.mod && \
  go mod edit -require github.com/uptrace/bun@v$(VERSION) dialect/sqlitedialect/go.mod && \
  go mod edit -require github.com/uptrace/bun@v$(VERSION) driver/pgdriver/go.mod && \
  go mod edit -require github.com/uptrace/bun@v$(VERSION) dbfixture/go.mod && \
  go mod edit -require github.com/uptrace/bun@v$(VERSION) extra/bundebug/go.mod && \
  go mod edit -require github.com/uptrace/bun@v$(VERSION) extra/bunotel/go.mod && \
  git add \*.mod && \
  git commit -m "Bump to version $(VERSION)" 
```

or a more condensed version
``` sh 
[ $(git --no-pager diff --name-only --staged | wc -l)  = "0" ] && \
  find . -type f -name "*.mod" -not -path ./go.mod -exec go mod edit -require github.com/uptrace/bun@v$(VERSION) {} \; && \
  git add \*.mod && git commit -m "Bump to version $(VERSION)" 
```

NOTE: not tested but should work

**Comment by vmihailenco** [comment]
Yes, that is a possibility. I hope to adopt something like https://github.com/open-telemetry/opentelemetry-go/blob/main/RELEASING.md, which uses go.mod to detect packages and then a regexp to update all dependencies that contain some substring (e.g. .*github.com/uptrace/bun.*).

**Comment by Codebreaker101** [comment]
So if I understood you correctly, like this:

``` sh
VERSION=v1.2.3; find . -type f -name 'go.mod' -exec sed -i "s/github.com\/uptrace\/bun\([^ ]*\) v[0-9]*\.[0-9]*\.[0-9]/github.com\/uptrace\/bun\1 $VERSION/" {} \;
```

**Comment by vmihailenco** [comment]
I would split one-liners into multiple (simpler) steps, but yes, your example looks pretty good.

I still don't know if updating go.sum without having released version(s) is going to be a problem, but I guess it should not be worse than current situation... Looking at OTel [script](https://github.com/open-telemetry/opentelemetry-go/blob/main/pre_release.sh#L86-L87), they are able to update go.sum somehow...

**Comment by Codebreaker101** [comment]
From what I can tell they are running `go mod tidy` on every directory containing go.mod. But before that (maybe. I don't have experience with `make` so this statement might be wrong) they are running their [crosslink tool](https://github.com/open-telemetry/opentelemetry-go/blob/main/internal/tools/crosslink/crosslink.go). I'm sure this code could be put into shell script with a bit of work. Although this would require dependency on `jq`.
