### ISSUE TITLE
Execute pgdriver.CopyFrom in the transaction, The CopyFrom fails due to the lock waiting.

### ISSUE THREAD

**Issue by qinxinxi** [uptrace/bun#561]
I faced a really annoying issue lately with the pgdriver.CopyFrom.

My code is as follows:

func main() {
	ctx := context.Background()
	dsn := "postgres://postgres:xxxx@xxxx:xxx/database?sslmode=disable"
	pgdb := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(dsn)))
	db := bun.NewDB(pgdb, pgdialect.New())
	db.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose(true)))

	var err error
	err = db.ResetModel(ctx, (*User)(nil))

	user1 := User{Name: "admin1"}
	user2 := User{Name: "admin2"}
	users := []User{user1, user2}

	conn, err := db.Conn(ctx)
	if err != nil {
		_ = fmt.Errorf("failed to get db conn, err: %v", err)
	}
	defer conn.Close()

	_, err = conn.NewInsert().Model(&users).Exec(ctx)

	path := "/home/dexcloud/user_table"
	f2, _ := os.Open(filepath.Clean(path))
	defer f2.Close()

	bf2 := bufio.NewReader(f2)

	db.RunInTx(ctx, nil, func(ctx context.Context, tx bun.Tx) error {
		_, err = tx.Exec(`TRUNCATE user_table`)       // TRUNCATE statement
		_, err = pgdriver.CopyFrom(ctx, conn, bf2, `COPY user_table(id, name) FROM STDIN WITH ENCODING 'UTF-8'`) // exec fails
		return err
	})
}

type User struct {
	bun.BaseModel `bun:"table:user_table,alias:u"`
	ID            int64 `bun:",pk,autoincrement"`
	Name        string
	Email         string
}

The file (/home/dexcloud/user_table ) content is as follows:
1	admin1-new
3	admin3

Problem:
The TRUNCATE statement holds the lock, and the data of the pgdriver.CopyFrom operation involves the data whose id is 1, so pgdriver.CopyFrom want to get the lock. However, as a result of the TRUNCATE statement holding the lock, pgdriver.CopyFrom fails.

![image](https://user-images.githubusercontent.com/107109356/172796152-98c277ef-e5fc-49ae-bacb-efa3c8c9bf42.png)

In this case, CopyFrom can be executed successfully in the previous go-pg [func (tx *Tx) CopyFrom], but the execution in the uptrace/bun [pgdriver.CopyFrom] fails.

**Comment by qinxinxi** [comment]
> I don't understand this issue... How can we solve this problem? From postgres doc: `TRUNCATE acquires an ACCESS EXCLUSIVE lock on each table it operates on, which blocks all other concurrent operations on the table. When RESTART IDENTITY is specified, any sequences that are to be restarted are likewise locked exclusively. If concurrent access to a table is required, then the DELETE command should be used instead.`

I am going to migrate from go-pg to bun. In go-pg, tx.Exec and tx.CopyFrom are executed successively in the transaction. However, in uptrace/bun, tx.Exec and pgdriver.CopyFrom are executed successively in the transaction, but pgdriver.CopyFrom execution fail. How to implement the same go-pg effect in uptrace/bun to implement migration? Thanks a lot.

Total code of go-pg as follows:
import (
	"bufio"
	"context"
	"fmt"
	"github.com/go-pg/pg/extra/pgdebug"
	"github.com/go-pg/pg/v10"
	"os"
	"path/filepath"
)

func main() {
	ctx := context.Background()
	dsn := "postgres://postgres:xxxxxx@xxxxxx:xxxxxx/xxx?sslmode=disable"
	opt, err := pg.ParseURL(dsn)
	fmt.Println(err)
	db := pg.Connect(opt)
	db.AddQueryHook(pgdebug.DebugHook{Verbose: true})

	user1 := User{Name: "admin1"}
	user2 := User{Name: "admin2"}
	users := []User{user1, user2}

	_, err = db.Model(users).Insert()

	path := "/home/dexcloud/user_table"
	f2, _ := os.Open(filepath.Clean(path))
	defer f2.Close()

	bf2 := bufio.NewReader(f2)
	db.RunInTransaction(ctx, func(tx *pg.Tx) error {
		//db.Exec(`TRUNCATE user_table`)
		_, err = tx.Exec(`DELETE FROM user_table`)
		_, err = tx.CopyFrom(bf2, `COPY user_table(id, name) FROM STDIN WITH ENCODING 'UTF-8'`) // exec success
		return err
	})
}

Total code of uptrace/bun as follows:
import (
	"bufio"
	"context"
	"database/sql"
	"fmt"
	"github.com/uptrace/bun"
	"github.com/uptrace/bun/dialect/pgdialect"
	"github.com/uptrace/bun/driver/pgdriver"
	"github.com/uptrace/bun/extra/bundebug"
	"os"
	"path/filepath"
)

func main() {
	ctx := context.Background()
	dsn := "postgres://postgres:xxxxxx@xxxxxx:xx/xxxxxx?sslmode=disable"
	pgdb := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN(dsn)))
	db := bun.NewDB(pgdb, pgdialect.New())
	db.AddQueryHook(bundebug.NewQueryHook(bundebug.WithVerbose(true)))

	var err error
	err = db.ResetModel(ctx, (*User)(nil))

	user1 := User{Name: "admin1"}
	user2 := User{Name: "admin2"}
	users := []User{user1, user2}

	conn, err := db.Conn(ctx)
	if err != nil {
		_ = fmt.Errorf("failed to get db conn, err: %v", err)
	}
	defer conn.Close()

	_, err = conn.NewInsert().Model(&users).Exec(ctx)

	path := "/home/dexcloud/user_table"
	f2, _ := os.Open(filepath.Clean(path))
	defer f2.Close()

	bf2 := bufio.NewReader(f2)
	db.RunInTx(ctx, nil, func(ctx context.Context, tx bun.Tx) error {
		//_, err = tx.Exec(`TRUNCATE user_table`)
		_, err = tx.Exec(`DELETE FROM user_table`)
		_, err = pgdriver.CopyFrom(ctx, conn, bf2, `COPY user_table(id, name) FROM STDIN WITH ENCODING 'UTF-8'`) // exec failed
		return err
	})
}

Database lock hold information is as follows:
![image](https://user-images.githubusercontent.com/107109356/174268367-4df58eac-7191-432a-b887-c4e73b97a391.png)

**Comment by vmihailenco** [comment]
It probably should be `pgdriver.CopyFrom(ctx, tx,`

**Comment by pedrocunha** [comment]
Hey @vmihailenco @qinxinxi - I am facing exactly the same problem. Would we be able to change the signature of CopyFrom to support this? 

It would give me an alternative instead of trying to do this which does not work:
```
	sql := fmt.Sprintf(`
		SET SESSION statement_timeout = 0; 
                 COPY %s (%s) FROM STDIN DELIMITER ',' CSV HEADER;
	`,
		(...), (...)
	_, err = pgdriver.CopyFrom(i.ctx, conn, pipe, sql)
	if err != nil {
		return errors.Wrapf(err, "failed to run COPY FROM")
	}
```

P.S.: also for some reason I can't use args with CopyFrom when my query has "?"

**Comment by fiftin** [comment]
@qinxinxi ,

what error do you get here?

```
_, err = tx.Exec(`DELETE FROM user_table`)
_, err = pgdriver.CopyFrom(ctx, conn, bf2, `COPY user_table(id, name) FROM STDIN WITH ENCODING 'UTF-8'`) // exec failed
```

I can't reprodude.

**Comment by ekalinin** [comment]
Tried to reproduce the issue in a test:
- #583 

And it passed.

Btw, tried to pass `tx` into `pgdriver.CopyFrom` as @vmihailenco [suggested](https://github.com/uptrace/bun/issues/561#issuecomment-1158782430) and got an error:

```
cannot use tx (variable of type bun.Tx) as type bun.Conn in argument to pgdriver.CopyFrom
```

And seems like there's no easy way to pass It into `pgdriver.CopyFrom`.

**Comment by vmihailenco** [comment]
@ekalinin thanks for providing a reproducer. I was able to make the test pass by adding `tx.Commit`.

**Comment by qinxinxi** [comment]
> @qinxinxi ,
> 
> what error do you get here?
> 
> ```
> _, err = tx.Exec(`DELETE FROM user_table`)
> _, err = pgdriver.CopyFrom(ctx, conn, bf2, `COPY user_table(id, name) FROM STDIN WITH ENCODING 'UTF-8'`) // exec failed
> ```
> 
> I can't reprodude.

Errors may occur when you execute pgdriver.CopyFrom in 【func (db *DB) RunInTx(ctx context.Context, opts *sql.TxOptions, fn func(ctx context.Context, tx Tx) error) 】, error as follows:
err: read tcp xx.xx.xxx.xxx:6507->xx.xxx.xx.xxx:5432: i/o timeout

**Comment by qinxinxi** [comment]
> @ekalinin thanks for providing a reproducer. I was able to make the test pass by adding `tx.Commit`.
> 
> #584


Thank you for your answers and handling.

This problem can be solved by using master branch func——【func (c Conn) RunInTx(ctx context.Context, opts *sql.TxOptions, fn func(ctx context.Context, tx Tx) error) 】 instead of 【func (db *DB) RunInTx(ctx context.Context, opts *sql.TxOptions, fn func(ctx context.Context, tx Tx) error) error】
