### ISSUE TITLE
Is it possible to move the `ParseTime` method from internal package ? 

### ISSUE THREAD

**Issue by bubusuke** [uptrace/bun#562]
We want to migrate from `go-pg` to `bun`, but we are in trouble because the `ParseTime` of bun exists in Internal package and cannot be used. Is it possible to move the `ParseTime` method to another package ? 

When we use `go-pg`, the db value of `timestamptz` was set to custom `time.Time` variables by implementing `sql.Scanner` as follows. We want to achieve this code with bun as well.

```
import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/go-pg/pg/v10/types"
)

type CustomTimeType struct {
	Time time.Time
}

// Value implements driver.Valuer.
func (v *CreatedAt) Value() (driver.Value, error) {
	if v == nil {
		return nil, nil
	}

	return v.Time, nil
}

// Scan implements sql.Scanner.
func (v *CustomTimeType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	switch val := value.(type) {
	case []byte:
		t, err := types.ParseTime(val) // !!ParseTime using HERE!!
		if err != nil {
			return fmt.Errorf("data scan error: %w", err)
		}

		v.Time = t
	default:
		return fmt.Errorf("unexpected value type: %T", v)
	}

	return nil
}
```

Thanks!

**Comment by vmihailenco** [comment]
I am okay with exposing the type in `pgdriver.ParseTime`. Can you send a PR?

**Comment by bubusuke** [comment]
Thanks!
I will prepare now!

**Comment by vmihailenco** [comment]
The PR is merged, closing

**Comment by bubusuke** [comment]
Thanks a lot!!! I am happy to contribute to bun.

**Comment by vmihailenco** [comment]
Thank *you*!
