### ISSUE TITLE
Do we support dynamic model?

### ISSUE THREAD

**Issue by mingee2018** [uptrace/bun#57]
In our scenario, we have many tables with the same schema, but different table names. Could we use a dynamic model in select method, like the following:

```sql
err := db.NewSelect().Table("bsc_cake_0x58f876857a02d6762e0101bb5c46a8c1ed44dc16_kline_1m_u").Order("time desc").Limit(100).Model(xxxx).Scan(ctx)
```

Or some other solution?

**Comment by vmihailenco** [comment]
Yes, use `ModelTableExpr` to override Model table name

```go
err := db.NewSelect().
    Model(xxxx).
    ModelTableExpr("bsc_cake_0x58f876857a02d6762e0101bb5c46a8c1ed44dc16_kline_1m_u").
    Order("time desc").
    Limit(100).
    Scan(ctx)
```

[Placeholders](https://bun.uptrace.dev/guide/placeholders.html) may also be useful.
