### ISSUE TITLE
The home page of official site doesn't explicitly show "Bun" as a branding name

### ISSUE THREAD

**Issue by adela-bytebase** [uptrace/bun#580]
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/94903075/174221816-83ba8366-a3d7-4fbb-aa2d-bff6b99e58cf.png">

I got a bit confused when I enter [https://bun.uptrace.dev/](https://bun.uptrace.dev/)

**Comment by vmihailenco** [comment]
Should be fixed - thanks for the feedback.
