### ISSUE TITLE
Unit testing service logic when using - *DB.RunInTx func

### ISSUE THREAD

**Issue by GuyKomari** [uptrace/bun#587]
I have a service with `*bun.DB` instance and a method that handles a transaction using `RunInTx` func.
I would like to add a unit test for this method but in order to do that, I need to use an abstraction over `*bun.DB` 
which seems to be - `bun.IDB` interface.
However,  `bun.IDB` is missing `RunInTx` func and other "transaction-related" methods like - BeginTx, Begin, etc.

simple code example:
```
type MyService struct {
	db            *bun.DB
	myRepo        MyRepo
}

func (s *MyService) DoSmt(ctx context.Context) error {
	err := s.db.RunInTx(ctx, nil, func(ctx context.Context, tx bun.Tx) error {
	        // Get for update
                // Some logic
                // Update
               
               return nil
	})
	
        return err
}

type MyRepo interface { 
     Get(ctx context.Context, db bun.IDB) interface{}, error
     Update(ctx context.Context, db bun.IDB, interface{}) interface{}, error
}
```

Currently, to overcome this issue, I have created this wrapper that can be used instead of `*bun.DB`:
```
type DbWrapper interface {
	bun.IDB
	RunInTx(ctx context.Context, opts *sql.TxOptions, fn func(ctx context.Context, tx bun.Tx) error) error
}
```
However, it would be nice if it was part of `bun.DBI`.
Would it be possible to add the "transaction-related" methods to `bun.DBI` (same as in go-pg)? 
Is there a better approach to handle this case?

TIA, Guy

**Comment by vmihailenco** [comment]
IDB is a common interface for *bun.DB, bun.Conn, and bun.Tx. I don't think we can extend it with `Begin` and `RunInTx`.

But we probably can add another interface, for example, `ITx` in addition to `IConn`. Then we can probably create `ITxDB` in addition to `IDB`. Not sure if it is worth it and makes your task much easier...

**Comment by isgj** [comment]
Some other ORMs offer the same interface also for the transaction, and when you are already in a tx they use `SAVEPOINT`.

The `bun.Tx` can be extended with `Begin`, `RunInTx`.. which will work on save-points. In this case the interface `IDB` can be extended and other than solving this issue it will make it possible for `bun.DB` and `bun.Tx` to be used interchangeably (helpful in some scenarios).

**Comment by vmihailenco** [comment]
@isgj yes, that is an option too. If there is any interest, please send a PR.
