### ISSUE TITLE
'fk' tag equivalent?

### ISSUE THREAD

**Issue by merefield** [uptrace/bun#6]
Continuing migration from go-pg, I've come across this warning:

```
WARN: bun: 2021/05/24 17:43:52 User.OwnerOfGroups has unknown tag option: "fk"
```
eg
```
	OwnerOfGroups          []UserGroup `bun:"fk:owner_id"`
```

I could not identify this from the (otherwise thorough) documentation provided ...

Is there support/an equivalent in bun? thanks!

**Comment by vmihailenco** [comment]
If that is a has-many relation, you can try `bun:"rel:has-many,join:id=owner_id"`. The format is `join:base_column=join_column`.

**Comment by merefield** [comment]
@vmihailenco this is currently failing silently for me, with no error.

Field `OwnerOfGroups` simply isn't being created in the resulting table definition, even though the foreign table exists.

Does it support the foreign ID's with UUIDs?

Models:

```
type User struct {
	ID                     uuid.UUID `bun:"type:uuid,default:uuid_generate_v4()"`
	CreatedAt              time.Time `bun:"default:now()"`
	UpdatedAt              time.Time
	Username               string `bun:",notnull,unique"`
SNIP
	OwnerOfGroups          []*UserGroup `bun:"rel:has-many,join:owner_of_groups=id"`
```
and 
```
type UserGroup struct {
	ID                 uuid.UUID `bun:"type:uuid,default:uuid_generate_v4()"`
	CreatedAt          time.Time `bun:"default:now()"`
	UpdatedAt          time.Time
	DisplayName        string `bun:",unique,notnull"`
	Description        string
SNIP
}
```

**Comment by merefield** [comment]
I've added a repo here which currently demonstrates this issue:  https://github.com/merefield/buncheck

Forward migration will work, but OwnerOfGroups field ends up missing?

**Comment by vmihailenco** [comment]
What do you expect? `OwnerOfGroups` is a destination field into which Bun scans the result of has-many relation. It is not a database column.

**Comment by merefield** [comment]
Ah, forgive me if I'm missing something, I was expecting the field to be instantiated to capture the foreign key's of all the groups for which each user is owner?

If the field is not instantiated in the database, how can one retrieve the groups a specific owner is responsible for? 😕

**Comment by merefield** [comment]
Got it, so I should add:

```
	OwnerID     uuid.UUID
```

To the UserGroup model

and update `OwnerOfGroups` to be:

```
	OwnerOfGroups  []*UserGroup `bun:"rel:has-many,join:id=owner_id""`
```

One more question though - if the type of `OwnerID` is not compatible with User ID (e.g. set to `int64` instead of `UUID`), will/should this be caught at migration time?

**Comment by vmihailenco** [comment]
>will/should this be caught at migration time?

I think Bun will just try to join using those columns and it won't work. It is better to try this yourself.

**Comment by merefield** [comment]
It would be good if the framework could typecheck at the time of migration, instead of being hit with such an error at runtime, but accept this might constitute a nice-to-have feature request! :)
