### ISSUE TITLE
Inconsistencies in the Migration, MigrationGroup and MigrationSlice types

### ISSUE THREAD

**Issue by mlevieux** [uptrace/bun#601]
There are inconsistencies in the receiver types on the methods of `Migration`, `MigrationGroup` and `MigrationSlice`:
- `Migration` is read-only from this package's perspective, and appears as `Migration` mostly, but the receiver is `*Migration`
- `MigrationGroup` is read-only as well from this package's perspective but it is used everywhere as `*MigrationGroup`
- `MigrationSlice` has underlying type `[]Migration` and is used as `MigrationSlice` everywhere

We stumbled upon this when trying something like (of course the following code is simplified):
```go
migrations := migrate.NewMigrations()
for _, m := range migrations.Sorted() {
    fmt.Printf("migration: %s\n", m) // m does not implement fmt.Stringer since the String method is implemented on *Migration but MigrationSlice is []Migration
}
```

Removing these inconsistencies has other advantages:
- Emphasize that those types are read-only, i.e. the migrate package does not mutate a value after returning it, or keep it as a cache...
- Reduce complexity in usage

**Comment by vmihailenco** [comment]
Hey,

I regret that we return `[]Migration` instead of `[]*Migration`, but the correct fix here:

```go
migrations := migrate.NewMigrations()
sorted := migrations.Sorted()
for i := range sorted {
    m := &sorted[i]
}
```

It is inconvenient, but fast because it avoids copying the whole `Migration` struct.

**Comment by vmihailenco** [comment]
I also merged the PR to avoid confusion. Thanks for fixing this.
