### ISSUE TITLE
has-many relationship does not do a JOIN

### ISSUE THREAD

**Issue by naltimari** [uptrace/bun#604]
When two models are related by a has-many relationship, bun will issue two different select statements when you use the Relation() function, instead of a single SQL statement with a JOIN predicate.

This is bad when you need to filter rows, for example. You can't just add a .Where() clause for one of the fields in the child model, because the field just isn't available in the select part.

Even if you use the func in the Relation, you end up eliminating rows on only one of the select statements, thus it behaves like a left or right join, and then the parent model brings data which is not what you expect.

Is this really by design? If that is the case, at least it should be mentioned in the documentation for the has-many section.

**Comment by vmihailenco** [comment]
This is done by design - has-many relation is implemented as a separate query.

**Comment by dillonstreator** [comment]
Agree that some documentation or example could be useful here. I kinda had the same expectation of bun as it felt intuitive. A mention of this in the doc could be useful in the [ORM relations](https://bun.uptrace.dev/guide/relations.html#has-many-relation) section maybe
