### ISSUE TITLE
LastInsertId is not available

### ISSUE THREAD

**Issue by HugHunter** [uptrace/bun#62]
I seem to run into issues when inserting a user struct. I get the following error : "LastInsertId is not available"

Is there potentially another way to access the returned id? I have tried to explicitly add ".Returning("id")" but get the same error.
```
func StoreUser(user *models.User) int64 {
	db := db_test_connect()
	defer db.Close()

	ctx := context.Background()

	result, err := db.NewInsert().Model(user).Exec(ctx)
	if err != nil {
		fmt.Println(err)
		panic(err)
	}
	fmt.Println(result) // Debugging
	userId, err := result.LastInsertId()
	if err != nil {
		fmt.Println(err)
		panic(err)
	}


	return userId
}
```

**Go version:**
go1.16.5 darwin/amd64

**Bun version:**
uptrace/bun v0.2.14
uptrace/bun/dialect/pgdialect v0.2.14

**Comment by isgj** [comment]
> // "auto increment" column when inserting a new row. Not all
	// databases support this feature, and the syntax of such
	// statements varies.

From [dics](https://pkg.go.dev/database/sql#Result) it states not all dbs support it.

What db are you using? Is the `id` of type `int`? If you use other type for the id (let's say UUID) it will error like that, even if the db supports the functionality.

`bun` populates back the id in the struct so you access can it with `user.ID` given it's called `ID`

**Comment by HugHunter** [comment]
Ah yes, your last sentence solved it! I thought the Id was returned when calling the insert function. But accessing the field `Id` in the struct `user` gives me the proper Id. Thanks a lot!
