### ISSUE TITLE
bug(pgdialect): `uint32` field will overflow

### ISSUE THREAD

**Issue by ionling** [uptrace/bun#624]
https://github.com/uptrace/bun/blob/92b81c341b2908dd2dde344e20f3d7e816f63e2c/dialect/pgdialect/dialect.go#L104

If the value of a `uint32` field is `2881420146`, the final inserted value will be `-1413547150`, it's overflowed.

**Comment by vmihailenco** [comment]
Postgres does not support unsigned numbers. Use `int32` or `int64` if you are worried about overflows.

**Comment by ionling** [comment]
Yeah, the Postgres does not have uint32 type, but in my code I use `uint32` for avoiding the none sense type conversion.
And I think if the ORM support uint32 type, it should handle it correctly, instead of letting it overflow, and make the developer choose a right type for it. No one knows `2881420146` will overflow, if they don't check the database.

**Comment by Aoang** [comment]
Another situation arises when the user specifies the type as `numeric`. This conversion behavior can lead to data anomalies. Maybe, instead of converting it ourselves, we should let the database throw an error.

**Comment by j2gg0s** [comment]
@vmihailenco

We can avoid truncating here and instead let the database throw an error?

Explicit errors are always better than silent ones.

**Comment by vmihailenco** [comment]
@j2gg0s such change is fine with me, but technically we don't truncate anything. All the bits are preserved.

**Comment by vmihailenco** [comment]
>Explicit errors are always better than silent ones.

Agreed :+1:
