### ISSUE TITLE
Implement `Is(error) bool` method on `pgdriver.Error` type

### ISSUE THREAD

**Issue by htdvisser** [uptrace/bun#636]
After working on #633 I realized that it may be possible to trigger the builtin retry behavior of `database/sql` when receiving `FATAL` errors from PostgreSQL (for instance, the `57P01 terminating connection due to administrator command` that I was working with in #633).

`database/sql/driver` godoc says:

> ErrBadConn should be returned by a driver to signal to the sql package that a driver.Conn is in a bad state (such as the server having earlier closed the connection) and the sql package should retry on a new connection. 
>
> To prevent duplicate operations, ErrBadConn should NOT be returned if there's a possibility that the database server might have performed the operation. Even if the server sends back an error, you shouldn't return ErrBadConn.
>
> Errors will be checked using errors.Is. An error may wrap ErrBadConn or implement the Is(error) bool method.

If we already received the FATAL error from PostgreSQL _before we sent an operation to the server_, there is no possibility that the database might have performed that operation, so we could immediately return (a variant of) `pgdriver.Error` that returns `true` for `Is(driver.ErrBadConn)`, so that `database/sql` can retry the operation on another (or a new) connection, and the application will not even have to see the error.

To illustrate this, I'm running 2 SELECT queries, then terminating the connection and then running 2 more SELECT queries (with the same code as I used to reproduce #525), here's the current situation:

```
=== RUN   TestUptraceBunPgdriver
=== RUN   TestUptraceBunPgdriver/SELECT_1
=== RUN   TestUptraceBunPgdriver/SELECT_2
=== RUN   TestUptraceBunPgdriver/SELECT_3
    main_test.go:37: FATAL: terminating connection due to administrator command (SQLSTATE=57P01)
=== RUN   TestUptraceBunPgdriver/SELECT_4
--- FAIL: TestUptraceBunPgdriver (0.06s)
    --- PASS: TestUptraceBunPgdriver/SELECT_1 (0.01s)
    --- PASS: TestUptraceBunPgdriver/SELECT_2 (0.00s)
    --- FAIL: TestUptraceBunPgdriver/SELECT_3 (0.00s)
    --- PASS: TestUptraceBunPgdriver/SELECT_4 (0.00s)
FAIL
FAIL    htdvisser.dev/exp/sql-errors    0.208s
FAIL
```

Situation if `(pgdriver.Error).Is(driver.ErrBadConn)` returns `true` for `FATAL` errors:

```go
func (err Error) Is(target error) bool {
	if target == driver.ErrBadConn {
		return isBadConn(err, false)
	}
	if target, ok := target.(Error); ok {
		// TODO: implement comparison against other pgdriver.Error types:
	}
	return false
}
```

```
=== RUN   TestUptraceBunPgdriver
=== RUN   TestUptraceBunPgdriver/SELECT_1
=== RUN   TestUptraceBunPgdriver/SELECT_2
=== RUN   TestUptraceBunPgdriver/SELECT_3
=== RUN   TestUptraceBunPgdriver/SELECT_4
--- PASS: TestUptraceBunPgdriver (0.08s)
    --- PASS: TestUptraceBunPgdriver/SELECT_1 (0.01s)
    --- PASS: TestUptraceBunPgdriver/SELECT_2 (0.00s)
    --- PASS: TestUptraceBunPgdriver/SELECT_3 (0.01s)
    --- PASS: TestUptraceBunPgdriver/SELECT_4 (0.00s)
PASS
ok      htdvisser.dev/exp/sql-errors    0.447s
```

**Comment by vmihailenco** [comment]
>Implement Is(error) bool method on pgdriver.Error type

Would be prudent to check if pgx / libpq do the same.

But I wonder what would happen in case like this:

```go
_. err := db.Exec("SELECT pg_terminate_backend(pid) FROM pg_stat_activity")
```

I guess the query will be retried because it is equal to `driver.ErrBadConn`....

**Comment by htdvisser** [comment]
That would indeed be problematic, so the error should only equal `ErrBadConn` if it occurred _before_ running the command, so that it actually satisfies `ErrBadConn`:

> To prevent duplicate operations, ErrBadConn should NOT be returned if there's a possibility that the database server might have performed the operation.

---

Based on what I observe in my tests, `lib/pq` seems to do something that (in some cases) lets `database/sql` retry when the connection closes. `jackc/pgx` doesn't seem to do this.

**Comment by vmihailenco** [comment]
I think we can close this for now since doing what you suggest might cause more problems than it solves and it does not seem like a big issue in the first place.

But thanks for reporting this.
