### ISSUE TITLE
Select only one field  from related model on has:one relation

### ISSUE THREAD

**Issue by rahulbreezo** [uptrace/bun#65]
On struct like this

```
type User struct {
ID string 
AuthenticationProvider *AuthenticationProvider `bun:"rel:has-one"`
}
```

```
type AuthenticationProvider struct {
	bun.BaseModel    `bun:"authentication_provider,alias:authentication_provider"`
	UniqueID         string `json:"-" bun:"-"`
	AuthenticationID string `json:"authentication_id"`
	UserId           string `json:"-"`
	ProviderName     string `json:"-"`
}
```

When I fill values in User struct var and print it , it comes like this:
```
{
id: "jkdojd",
AuthenticationProvider: {
authentication_id: "jjhkjjlk"
}
}
```
but I want it like this:

```
{
id: "jkdojd",
authentication_id: "jjhkjjlk"
}
```

Right now I am achieving this by changing user struct to like this:
```
type User struct {
ID string 
AuthenticationProvider *AuthenticationProvider `bun:"rel:has-one"`
AuthenticationID       string                  `json:"authentication_id" bun:"-"`
}
```

Is there any direct way  to achieve same result without adding  AuthenticationID field to User struct?

and how does I handle foreign key in structs?

**Comment by vmihailenco** [comment]
>Is there any direct way to achieve same result without adding AuthenticationID field to User struct?

Perhaps you want `belongs-to` relation - it has the layout you need.

>and how does I handle foreign key in structs?

Bun does not use information about foreign keys. But you can create foreign keys when creating a table - https://bun.uptrace.dev/guide/queries.html#creating-tables

**Comment by rahulbreezo** [comment]
will try , if  there is no more doubt or problem , I will close this issue

**Comment by rahulbreezo** [comment]
`belongs-to` give me same response layout, and probably that's how it should be given that type is struct so layout should also be struct.
  ```
{
        "id": "c0068408-9c59-4a19-b701-ed2f12181ebe",
        "organisation_name": "",
        "first_name": "Yas",
        "last_name": "Kal",
        "email_id": "demo@test.in",
        "email_verified": true,
        "country_code": "+78",
        "phone_number": "0010000000",
        "created_at": "2021-07-08T16:40:01.535251Z",
        "updated_at": "2021-07-09T03:58:05.547421Z",
        "authentication_id": "",
        "AuthenticationProvider": {
            "authentication_id": "60ae10e6cb1fe7006ac2ebd7"
        }
    }
```
