### ISSUE TITLE
Using sslmode=disable with pgdriver

### ISSUE THREAD

**Issue by Okeanos** [uptrace/bun#652]
According to the [documentation](https://bun.uptrace.dev/postgres/#supported-drivers) there are multiple ways to configure a Postgres connection, e.g.

1. Example: 
  ```go
  pgconn := pgdriver.NewConnector(
  	pgdriver.WithAddr("localhost:5437"),
  //...
  )
  ```
2. Example
  ```go
  pgconn := pgdriver.NewConnector(
  	pgdriver.WithDSN("postgres://postgres:@localhost:5432/test?sslmode=verify-full"),
  )
  ```

Now, I wanted to test this out with a local dockerized Postgres that is running without SSL/TLS.

The following connection string works as expected:

```go
dsn := fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=disable&search_path=%s", cfg.User, cfg.Password, cfg.Host, cfg.Port, cfg.Database, cfg.Scheme)
connector := pgdriver.NewConnector(pgdriver.WithDSN(dsn))

sqldb := sql.OpenDB(connector)

db := bun.NewDB(sqldb, pgdialect.New())
// ...
```

However, if I transform that into the syntax from  example 1, I get an error "pgdriver: SSL is not enabled on the server":

```go
connector := pgdriver.NewConnector(
	pgdriver.WithAddr(fmt.Sprintf("%s:%d", cfg.Host, cfg.Port)),
	pgdriver.WithUser(cfg.User),
	pgdriver.WithPassword(cfg.Password),
	pgdriver.WithDatabase(cfg.Database),
	pgdriver.WithConnParams(map[string]interface{}{
		"sslmode":     "disable",
		"search_path": cfg.Scheme,
	}))

sqldb := sql.OpenDB(connector)

db := bun.NewDB(sqldb, pgdialect.New())
// ...
```

It appears that the `sslmode` connection parameter is ignored for some reason? Additionally specifying `pgdriver.WithTLSConfig(&tls.Config{InsecureSkipVerify: true})` or even `pgdriver.WithTLSConfig(&tls.Config{})` does nothing either.

Sadly there isn't an actual example for what I am trying to do and there doesn't appear to be an open (or closed) issue here either. Apparently, I am overlooking something – presumably something basic but what is it? Sorry, if this is a trivial problem.

---

Local test setup:

- Database: `postgres:13-alpine`
- Go: `1.18`, `1.19`
- go-bun:
  ```txt
  github.com/uptrace/bun v1.1.7
  github.com/uptrace/bun/dialect/pgdialect v1.1.7
  github.com/uptrace/bun/driver/pgdriver v1.1.7
  github.com/uptrace/bun/extra/bundebug v1.1.7
  github.com/uptrace/bun/extra/bunotel v1.1.7
  ```

**Comment by vmihailenco** [comment]
`WithConnParams` specifies PostgreSQL server params like https://www.postgresql.org/docs/14/runtime-config.html. Perhaps we should rename it to `WithServerParams`. So this is working as expected.

**Comment by Okeanos** [comment]
Okay, that makes sense. Thanks for the information. 

As a follow up question: what would be the correct way to specify `sslmode=disable` (or any other) with the connection configuration style from example 1? Is it even possible to do that?

**Comment by vmihailenco** [comment]
WithInsecure(true) - https://pkg.go.dev/github.com/uptrace/bun/driver/pgdriver#WithInsecure
