### ISSUE TITLE
bug(bunotel): No option attributes

### ISSUE THREAD

**Issue by ionling** [uptrace/bun#653]
The attributes passed by `bunotel.WithDBName()` and `bunotel.WithAttributes()` are not set.

https://github.com/uptrace/bun/blob/887135cca7f903d14aa487a62867019acc231e98/extra/bunotel/otel.go#L92-L98

We should:

```go
	attrs = append(attrs, h.attrs...)
```

**Comment by vmihailenco** [comment]
:+1: Could you send a PR?
