### ISSUE TITLE
Can't Insert Struct Array

### ISSUE THREAD

**Issue by ElecTwix** [uptrace/bun#669]
- **Database**: PostgreSQL

 **Things have been tried**: 
> - like normal struct
> - [postgres-arrays](https://bun.uptrace.dev/postgres/postgres-arrays.html)
> - [isssue#413](https://github.com/uptrace/bun/issues/413)

```go
type User struct {
	bun.BaseModel `bun:"table:users,alias:u"`
	ID            int64 `bun:",pk,autoincrement"`
	Name          string
	Emails        int
	Something     Hello
}

type Hello struct {
	ArrSome []warn `bun:",array"`
}

type warn struct {
	issuer string
	reason string
	time   time.Time
}
```

Insert Code

```go
	users := User{
		Name:   "random name hello",
		Emails: i,
		Something: Hello{
			ArrSome: []warn{{
				issuer: "test",
				reason: "abc",
				time:   time.Now(),
			}},
		},
	}

	fmt.Println(users.Something)

	_, err := db.NewInsert().Model(&users).Exec(*ctx)
	if err != nil {
		panic(err.Error())
	}
```

**Before** insert

-  Data: `{[{test abc {13888975035297425718 129413817 0x8d1120}}]}`

**After**  insert

-  Data: `[{  {0 0 <nil>}}]`

- Checked Database via **DataGrip** and also with **Query** with Bun & PostgreSQL Cli SQL

- Output of ArrSome ( []warn )

**Comment by danclive** [comment]
Please keep the first letter of your structure field in upper case, like:

```go
type warn struct {
	Issuer string
	Reason string
	Time   time.Time
}
```
