### ISSUE TITLE
How to reset `deleted_at` if in "soft delete" mode?

### ISSUE THREAD

**Issue by merefield** [uptrace/bun#68]
This query fails:

``` go
  db.NewUpdate().
    Model(new(model.User)).
    Set("deleted_at = NULL").
    WhereAllWithDeleted().
    Exec(ctx)
```

(I'm trying to reset state during a test suite run)

**Comment by vmihailenco** [comment]
Seems to be working for me - https://github.com/uptrace/bun/blob/master/internal/dbtest/soft_delete_test.go#L77-L89. Can you provide a reproducer?

**Comment by merefield** [comment]
Reproducer here:  https://github.com/merefield/buncheck

run with `go run main.go runtest`

the error you get with this statement is:

`"bun: Update and Delete queries require at least one Where"`

which is odd because of course we have supplied: ` WhereAllWithDeleted().`

**Comment by vmihailenco** [comment]
Bun does not allow to execute that query, because it will delete all users. If you insist, you can add a dummy `Where("1")` or use `NewTrucate` to truncate the table.

**Comment by merefield** [comment]
Surely it should not delete all users but instead set the deleted_at to null thereby ‘undeleting’ the soft deleted records?

How should one undelete soft deleted records?

**Comment by vmihailenco** [comment]
Yes, update all records, not delete.

>How should one undelete soft deleted records?

```go
_, err = db.NewUpdate().
	Model(new(model.User)).
	Set("deleted_at = NULL").
	WhereAllWithDeleted().
	Where("deteted_at IS NOT NULL").
	Exec(c.Context)
```

**Comment by merefield** [comment]
Thanks, that works!

(although in terms of code readability, I cannot see why from face value the first query should not be legal - surely it should select all rows in the entire table? (and update them) )
