### ISSUE TITLE
Column filtering with OmitZero causes invalid update statement

### ISSUE THREAD

**Issue by Karimerto** [uptrace/bun#684]
I am trying to limit the number of columns that can be updated via an incoming REST request, but my idea is not working. I have the following (dummy) model:

    type Mytable struct {
        Id int    `json:"id" bun:",pk,autoincrement"`
        A  string `json:"a"`
        B  int    `json:"b"`
        C  string `json:"c"`
    }

And I would like that, for example, only columns A and B can be updated, and only if they actually contain something. So to that end I tried the following:

	var mytable Mytable
	// Parse from json, excluded for brevity
	if _, err := db.NewUpdate().
		Model(&mytable).
		Column("a", "b").
		OmitZero().
		WherePK().
		Returning("*").
		Exec(ctx); err != nil {
		return err
	}
	// Return jsonified response

When called with a proper request, for instance (in Python):

	requests.put("localhost:8080/api/mytable/123", json={"a": "some string"})

The result is fine, as expected. But when called with "invalid" request, the server fails with an internal error since the SQL generated is broken.

	requests.put("localhost:8080/api/mytable/123", json={"c": "this cannot be updated"})

The resulting SQL is something like the following:

	UPDATE "mytable" SET  WHERE ("mytable"."id" = 1) RETURNING *

As can be seen, the `SET` clause is empty, and naturally this is invalid SQL.

Is there a "proper" way this can be done, either with Bun itself, or Bunrouter? Or should I just add some filtering before running the update command?

**Comment by jamesjulich** [comment]
Bumping since I am also experiencing this. Can confirm that I have reproduced a similar error.

If you ask bun to create an update statement using a model with all nil fields, then call OmitZero, you will end up with an invalid query as seen here.

```
db.NewUpdate().
	Where("? = ?", bun.Ident(identifier), c.Params(identifier)).
	OmitZero().
	Model(&myEmptyStruct{}).
	String();
```

will produce SQL like this: ```UPDATE "test" AS "test_struct" SET  WHERE ("id" = '1')```
