### ISSUE TITLE
Postgre `identity` lack of `GENERATED ALWAYS` support

### ISSUE THREAD

**Issue by necipallef** [uptrace/bun#688]
[Here](https://github.com/uptrace/bun/blob/28915f89b0e864ee7c43782fe3234f8d65831e00/query_table_create.go#L173) it seems like the `identity` tag results in `GENERATED BY DEFAULT` only. However, Postgre has an option `GENERATED ALWAYS` as seen [in this link](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-identity-column/):
`The 'GENERATED ALWAYS' instructs PostgreSQL to always generate a value for the identity column. If you attempt to insert (or update) values into the 'GENERATED ALWAYS AS IDENTITY' column, PostgreSQL will issue an error.`

Also, I could not find any documentation for the `identity` tag. I was able to find the `identity` tag ever exists by searching through the issues. Is it me or is there a lack of information on the `identity` tag?

**Comment by GauteHaugen** [comment]
I can see that this issue has been here for some time now. Are there any updates or plans to work on this? In addition to the lack of GENERATED ALWAYS keywords, there are also missing the optional sequence_options that go with the identity column.

This definition is taken from PostgreSQL documentation:
```GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( sequence_options ) ]```

**Comment by bevzzz** [comment]
@vmihailenco WDYT about extending the tag to allow `identity:always`, defaulting to `BY DEFAULT` if the tag has no options?
