### ISSUE TITLE
Primary key

### ISSUE THREAD

**Issue by sloan-dog** [uptrace/bun#69]
Models/schema

```
type BaseModel struct {
	bun.BaseModel
	ID int64 `bun:"pk,autoincrement"`
}

type User struct {
	BaseModel
	//this represents the customer

	FirstName  string `bun:"type:varchar(255)"`
	SecondName string `bun:"type:varchar(255)"`

	PasswordHash string

	Email *string

	AddressID int
	///address_id is a foreign_key from the address table....
	CreatedAt *time.Time
	UpdatedAt *time.Time

	Links []*Link `bun:"rel:has-many"`
}

type Link struct {
	BaseModel
	Title   string `bun:"type:varchar(255)"`
	Address string `bun:"type:varchar(255)"`
	UserID  int64
}
```
Migration
```
	Migrations.MustRegister(func(ctx context.Context, db *bun.DB) error {
		db.RegisterModel((*models.User)(nil), (*models.Link)(nil))
		return nil
	}, nil)
```

When running the migration i get `panic: bun: model=User does not have primary keys`

How do i inform bun of User's ID key being primary key

**Comment by isgj** [comment]
Maybe by adding another `pk` option
```go
type User {
    ID int64 `bun:"pk,pk,autoincrement"`
}
```
The first `pk` to tell that field `ID` is backed by `pk` column in db, the second to tell it's a primary key. Looking at the code it should warn about the usage of `pk` as a column name as it is also an option

```go
if tag.Name != sqlName && isKnownFieldOption(tag.Name) {
	internal.Warn.Printf(
		"%s.%s tag name %q is also an option name; is it a mistake?",
		t.TypeName, f.Name, tag.Name,
	)
}
```

**Comment by vmihailenco** [comment]
Should be fixed https://github.com/uptrace/bun/commit/51766534ce79d359e424cb3ba85647996ef362c2

>Looking at the code it should warn about the usage of pk as a column name as it is also an option

It is unrelated to this issue, but we may indeed improve the check in case of `bun:"pk,pk`.

**Comment by sloan-dog** [comment]
Is the bun:"option1,option2,option3" format documented anywhere? I could not find a comprehensive list of struct tags and their components in current bun docs. Know it is a new -ish project, but derived from another. It was not apparent to me how to canonically indicate a field is a primary key in bun.

**Comment by vmihailenco** [comment]
Looks like that info was lost during migration :( I will restore it, but meanwhile you can check https://pg.uptrace.dev/models/#struct-tags

**Comment by vmihailenco** [comment]
Docs were updated - https://bun.uptrace.dev/guide/models.html#struct-tags
