### ISSUE TITLE
[question] How to add column during migration

### ISSUE THREAD

**Issue by vijayrajah** [uptrace/bun#694]
I have already defined a Model & created the table using migration. (With some data)

I found no way (using GO migration) to add a column. 

There is a NewAddColumn(), but I can't seem to set the new column name. if I try with the full model, I get `bun: AddColumnQuery requires exactly one column`

Maybe I'm being a idiot, can you give an example on how to do this?

I have searched the docs, I can't find anything that would help me.

**Comment by l0nax** [comment]
Try this:
```go
	_, err = db.NewAddColumn().
		Table("stories").
		ColumnExpr("new_column TEXT DEFAULT ''").
		Exec(ctx)
```

**Comment by vijayrajah** [comment]
@l0nax  -- Thanks I will try this, I used raw query to workarund this issue 

```
bun.NewRawQuery(db, "alter table status add column updated_time timestamp with time zone ").Scan(ctx, &status)
```
