### ISSUE TITLE
Any plans to support Cockroach?

### ISSUE THREAD

**Issue by algoflows** [uptrace/bun#699]
Hey team,

Are there any plans for Bun to support CockroachDB, its gaining major traction lately and it would be awesome to use Bun as the query builder/ORM?

Thanks in advance :))

**Comment by Egbert-Jan** [comment]
You can use a Postgres ORM if you want to use CockroachDB

**Comment by vmihailenco** [comment]
Yes, use pgdialect with CockroachDB - https://bun.uptrace.dev/postgres/ . If there are incompatibilities, we can create a separate dialect for CockroachDB.
