### ISSUE TITLE
Should I create slices of structs with capacity 0?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#7]
I have an old doubt about what's the most performant version of this code (or if it's the same).

I just read https://philpearl.github.io/post/bad_go_not_sizing_arrays/ too.

I'm switching to Bun so I'm asking it right now, I hope you'll help me understand this once for all, @vmihailenco. 😄 😢

This is the code I'm using:

```go
func (r PlayerRepository) Players(ctx context.Context) ([]player.Player, error) {
  limit := 100

  players := make([]Player, limit) // <<<<---------- this line

  query := db.NewCustomQuery(ctx, r.db, &players)

  query.Limit(limit)

  err := query.Select()
  if err != nil {
    return nil, err
  }

  return players, nil
}
```

The doubt is about using this line:

```go
players := make([]Player, limit)
```

or this one:

```go
players := make([]Player, 0, limit)
```

Should I use the first or the second one?

Is this unnecessary for `go-pg`?

Is the same for `go-pg` and `Bun`?

**Comment by vmihailenco** [comment]
>Should I use the first or the second one?

`make([]Player, 0, limit)` is more bullet-proof and more explicit, but they produce the same result in go-pg and bun (with same performance).

Overall specifying the slice capacity is only important for performance and I usually don't bother with it. It is more practical to optimize the hot path later.
