### ISSUE TITLE
Many-to-Many Relationship with extra ID field results in a scan error

### ISSUE THREAD

**Issue by longchu-1209** [uptrace/bun#709]
Hi, I was trying to setup bun many-2-many with the below specs

``` go
type Order struct {
	ID    int64  `bun:",pk"`
	Items []Item `bun:"m2m:order_to_items,join:Order=Item"`
}

type Item struct {
	ID int64 `bun:",pk"`
}

type OrderToItem struct {
	ID      string `bun:",pk" json:"id"`
	OrderID int64  `bun:",notnull"`
	Order   *Order `bun:"rel:belongs-to,join:order_id=id"`
	ItemID  int64  `bun:",notnull"`
	Item    *Item  `bun:"rel:belongs-to,join:item_id=id"`
}
```

The execution would result in a scan error because both OrderToItem.ID and Order.ID columns are `id`. The column names collide in the mapping which leads to this:
```
sql: Scan error on column index 0, name "id": Scan: unable to scan type string into int64
```

Do you guys have any suggestion because the "extra" ID in the pivot table is inevitable to our business.
Thanks alot!

**Comment by rtalhouk** [comment]
I'm having a similar issue so I'm just +1-ing this thread. Any insight would be appreciated
