### ISSUE TITLE
integrating with aws xray for tracing

### ISSUE THREAD

**Issue by rahulbreezo** [uptrace/bun#71]
Hi ,
I  am using  aws xray for tracing (https://github.com/aws/aws-xray-sdk-go)
I was able to integrate `aws-x-ray` with `bun` without any error  by doing this:

```
	connStr := config.GetConfig().ReadPostgresqlConnStr

	instrumentedDB, err := xray.SQLContext("pg", connStr)
	log.Println(err)

	readDBPool = bun.NewDB(instrumentedDB, pgdialect.New())
	readDBPool.AddQueryHook(bundebug.NewQueryHook())
```
It did not throw any error.

but when I  do this:

```
var result int
	rows, err := db.QueryContext(ctx, "SELECT 1+1")
	if err != nil {
		return false, errors.Wrap(err, errors.DBConnectionFailedException)
	}

	err = db.ScanRows(ctx, rows, &result)
	if err != nil {
		return false, errors.Wrap(err, errors.DBConnectionFailedException)
	}
	return true, nil
```

**It gives me this error:**
`sql: expected 1 arguments, got 0`

same if my psql `select` query returns 10 values then error says,
`sql: expected 10 arguments, got 0`

I could not solve this error.  Another way I can think of integrating aws xray using hooks. Though that will require more code changes so I prefer to integrate in a above mentioned method. 

I created this issue first in aws xray repo but got no reponse there. 

Though it was working fine when I did not integrated aws-xray
**Note**
and I am doing this in local so I have done this:
`os.Setenv("AWS_XRAY_SDK_DISABLED", "TRUE")`

**Comment by vmihailenco** [comment]
Thanks for the report. Should be fixed in v0.3.1

**Comment by rahulbreezo** [comment]
@vmihailenco  , Now I am getting error unexpectedly .

For most of the time everything is running fine but when I hit an API multiple times consecutively. Only the first one gets succeeds , next one fails with error like this ` *errors.errorString: pgdriver: query returned 19 columns, but dest has 10 items`

**Comment by vmihailenco** [comment]
Please try v0.3.2 :mushroom:
