### ISSUE TITLE
Migration Documentation

### ISSUE THREAD

**Issue by sloan-dog** [uptrace/bun#72]
The migration documentation lacks concrete examples of how to go from no tables and schema, to creating schema/tables in the database. I borrowed from the starter kit and the real world repo to infer structuring migrations, but as a newcomer to bun, it was difficult to piece together the necessary API calls for the migrations to run. 

Happy to put up some PRs for docs based on my experiences thus far. I am stoked on this library, because it is minimal, supports explicitly defined migrations based on code, and has an intuitive query builder. Would like to support!

The portions of migrations I was most unclear on were
How to drive the Migrator
How to hydrate the Migrations
How to define the content of a migration without using a fixture
How to include foreign key constraints
How to best tag structs

If these areas are addressed, i believe this project becomes more approachable and utilized, which means more help to develop and refine which is good for the ecosystem. 

I imagine a start to finish mini tutorial would be helpful.
1. 2 Models with a many to one and foreign key necessitated, example tags on the models
2. Write the go based migration with actual bun API calls
3. Write the sql based migration
4. Code to populate the Migrations instance with the go or sql migrations
5. Code to drive the Migrator with Migrations
6. Create a new go migration file to modify one of the tables/models.
7. Create a new sql migration file to modify one of the tables/models
8. Run the next migration

**Comment by vmihailenco** [comment]
Thanks for the feedback. I think we have all that information here and there, but I understand that it can be hard to find it. At the same time, it is not clear how we can have it all on the same page (struct tags, migrations, fixtures - basically everything).

The only thing that comes to mind is writing some tutorial / series of articles for newcomers. Eventually I will do that for https://github.com/go-bun/bun-realworld-app or something, but it will take time and releasing v1.0 is probably more important. Any help is welcome.

**Comment by sloan-dog** [comment]
Cool, i'll start drafting a tutorial, and once its in a solid place, ill get some feedback from you, to make sure I'm doing things canonically. I'll write it in markdown for portability, and if it comes together in a way we like, we can put it somewhere.

**Comment by vmihailenco** [comment]
You could try https://github.com/go-bun/bun-docs. It is very simple to work with. I've created https://github.com/go-bun/bun-docs/pull/3 to show how to add articles.

**Comment by lakkinzimusic** [comment]
Good evening! Thank you for your work.

I was impressed with your starter-kit, but I decided not to use it because I wanted to use the gin router.
In this regard, I wrote a draft of the cli to call the migration tools.

```
package main

import (
	"context"
	"flag"
	"fmt"
	"github.com/uptrace/bun/migrate"
	"log"
	"myproject/config"
	"myproject/database/migrations"
)

func main() {
	action := flag.String("action", "", "init/create/createSql/run/rollback")
	flag.Parse()

	conf, err := config.LoadConfig()
	if err != nil {
		log.Fatal("cannot load config:", err)
	}

	db := InitDB(conf)
	migrator := migrate.NewMigrator(db, migrations.Migrations)

	switch *action {
	case "createSql":
		createMigrationSql(migrator)
	default:
		log.Fatal("cannot parse action")
	}
}

func createMigrationSql(migrator *migrate.Migrator) {
	mf, err := migrator.CreateSQL(context.TODO(), "random_name")
	if err != nil {
		panic(err)
	}
	fmt.Printf("created migration %s (%s)\n", mf.FileName, mf.FilePath)
}
```

The migrations package is identical:
https://github.com/go-bun/bun-starter-kit/blob/master/cmd/bun/migrations/main.go

The usage examples for migration are taken from your cli tool:
https://github.com/go-bun/bun-realworld-app/blob/master/cmd/bun/main.go

Perhaps this will help someone in working with bun or documentation.
Please, correct me if I am using the migration tool incorrectly or my decision not to use the starter-kit is not reasonable. Thank you!

**Comment by vmihailenco** [comment]
It is probably easier to replace treemux with Gin rather than re-create the whole starter kit, but it looks like treemux is not the only "problem" :) Overall there is nothing wrong with such approach and Bun can be used without starter kit just fine.

**Comment by vmihailenco** [comment]
@sloan-dog any new on this? :) If you have any results, please share and I will try to finish it...
