### ISSUE TITLE
Eager loading

### ISSUE THREAD

**Issue by fterrag** [uptrace/bun#721]
Hi there! Does Bun support eager loading?

**Comment by goferHiro** [comment]
No

**Comment by goferHiro** [comment]
You could develop some controllers for the model to eager load. You this for reference. Just specify the relation...

https://bun.uptrace.dev/guide/relations.html#introduction

**Comment by goferHiro** [comment]
Eager loading only slows bun's performance hence its not supported. If you want to fetch all relations at once just build a model controller
