### ISSUE TITLE
structTableModel.ScanColumn() fails when the Column names from database driver are not in pure lowercase

### ISSUE THREAD

**Issue by m29h** [uptrace/bun#724]
I was trying to use bun in conjunction with the [mattn/go-adodb](https://github.com/mattn/go-adodb) driver. 
When trying to scan a sql SELECT into a go struct with a bun model i got repeated errors from the `(*structTableModel).ScanColumn()` function. 

After a bit of debugging it turned out that my database driver returns `rows.Columns()` in uppercase characters, while bun seems to expect by some arbitrary convention lowercase. The lookup of an non lowercase column name in the lowercase keyed [FieldMap](https://github.com/uptrace/bun/blob/master/model_table_struct.go#L327) will (obviously) fail.

The `database/sql` [(sql.*Rows).Columns()](https://cs.opensource.google/go/go/+/go1.19.3:src/database/sql/sql.go;l=3084) function does not seem to specify that the values can be trusted to always be in lowercase. Wouldn't it be therefore a good idea to make sure bun also woks with databases that return `(sql.*Rows).Columns()` in something other than lowercase?

**Comment by vmihailenco** [comment]
You should be able to override the SQL name used by Bun via `bun:"CUSTON_NAME"`. Does that help?

**Comment by m29h** [comment]
Thank you @vmihailenco, the character_case of the column name placed after `bun:"` gets propagated up to the internal FieldMap that bun uses to match table columns to the go struct fields. Therefore if I write each column name in CAPITAL letters there, my problem is solved!

From my point of view this is still an odd behavior given that SQL internally matches columns case-_insensitive_ while bun matches columns case-**sensitive** to the string they are aliased inside of the SQL statement.

To illustrate the following struct is currently a fully valid bun struct that can be used to execute both `SELECT/INSERT/UPDATE/DELETE` commands on.  (only `CREATE TABLE` fails because the database will refuse to create three columns that in lowercase are all three spelled `name`
```go
type User struct {
	bun.BaseModel `bun:"table:users"`
	ID            int64 `bun:"id,pk,autoincrement"`
	NaME          int64 `bun:"NaME"`
	NAmE          int64 `bun:"NAmE"`
	Name          string
	Emails        []string
}

/* will instruct bun to  make statements such as
SELECT "user"."id", "user"."NaME", "user"."NAmE", "user"."name", "user"."emails" FROM "users" AS "user" ORDER BY id ASC
*/
```

**Comment by vmihailenco** [comment]
There is no easy way to make Golang map match keys case-insensitive and it would not be a good practice anyway.

See warnings in https://bun.uptrace.dev/guide/models.html#sql-naming-convention
