### ISSUE TITLE
Table's schema in the `bun` tag

### ISSUE THREAD

**Issue by bevzzz** [uptrace/bun#728]
Following our discussion [here,](https://github.com/uptrace/bun/issues/456#issuecomment-1335177025) I am opening an ticket for this feature.

Context from the linked comment:
> I couldn't find a convenient mechanism in bun's API for specifying the schema to which a certain table belongs. [...] It could be worked around with, e.g. `BeforeCreateTableHook`, but I feel like we should have a simpler solution (like adding a schema key in the bun: tag) for something so commonplace  

A proposed solution would be:
> It probably can be supported via a tag like you suggested bun:"schema:name",  [...]

For example, if specified:
```go
type Model struct {
    bun.BaseModel `bun:"schema:custom"`
    ...
}

db.NewCreateTable().Model((*Model)(nil)).Exec(ctx)
// Output: CREATE TABLE custom.models;

db.NewSelect().Model((*Model)(nil)).Count().Scan(ctx, &n)
// Output: SELECT COUNT(*) FROM custom.models;

// Etc.
```  
If omitted, the generated query does not include any schema name (i.e. does not assume `public`), the behavior stays as is.

**Comment by vmihailenco** [comment]
An alternative could be:

```go
type Model struct {
    bun.BaseModel `bun:"schema.table_name"`
    ...
}
```

That is actually what I use right now, but Bun is completely unaware about the schema name.

So the questions is: How do we plan to use the schema name?

**Comment by bevzzz** [comment]
That's actually a pretty neat alternative, I haven't thought of that before.  Theoretically, we could make use of the schema name for something  like `CREATE/DROP/ALTER SCHEMA` queries, but it seems that's not a priority or a much-needed feature at the moment.

**Comment by goferHiro** [comment]
```go
type Book struct {
	ID		 int64
	AuthorID int64
	Author	 Author `bun:"rel:belongs-to,join:author_id=id"`
}

type Author struct {
	ID int64
}

err := db.NewSelect().
	Model(book).
	Relation("Author").
	Where("id = 1").
	Scan(ctx)

```

**Comment by smyrman** [comment]
I am relying on  `bun:"table:schema.table_name"` today for my queries, and I feel it works relatively well.

---

FWIW, I also have a migration tool to create schemas (and put a per schema "bun_migrations" table _inside_ the schema), but this is a complete separate concern for me, and doesn't have a direct relationship to the struct tags themselves.

Here is a very small extract from some of the code:

```go
// Schema declares a database schema name to create,
// and a list of associated migrations.
type Schema struct {
	// Name of the database schema to use for the
	// bun_migrations table.
	Name string
	
	// Migration set. By convention, only include migrations
	// that operate on the schema matched by Name. This
	// way, if the schema is dropped, both the migration
	// table and created content is dropped together.
	Migrations *migrate.Migrations
}

// Migrator returns a Migrator instance for sc.
func (sc Schema) Migrator(db *bun.DB) *Migrator { 
	m := New(db, sc.Migrations)
	if sc.Name != "" {
		m.SetTable(sc.Name + ".bun_migrations")
	}
	return m
}
```
