### ISSUE TITLE
Clear up join documentation

### ISSUE THREAD

**Issue by comsma** [uptrace/bun#745]
I was having issues doing a join between to models by using two consecutive join parameters. For my one to many relation to work I have to use a join for the first column and a join_on for the second column. Is that the expected functionality? if so can we update the docs https://github.com/go-bun/bun-docs/edit/master/docs/guide/relations.md

**Comment by vmihailenco** [comment]
@comsma could you show your models? `join:col1=col2,col3=col4` should be working fine.

**Comment by comsma** [comment]
To pull the data I need I use this function and this works as expected.

```go
s.DB.NewSelect().Model(customer).Where("customer_id = ? AND company_id = ?", 100000, "Company1").Relation("Orders").Scan(ctx)
```

Using ```rel:has-many,join:customer_id=customer_id,company_id=company_id``` also works.
 
When I follow the documentation though [ORM: Table relationships](https://github.com/go-bun/bun-docs/blob/cbfaa5daaeda537ca6cef5305f43d6eff67a2038/docs/guide/relations.md?plain=1#LL147C96-L147C96)

"You can specify multiple join columns, for example, ```join:company_id=company_id,join:customer_id=customer_id```" it fails to query.

# Here are my models
## Contact
```go
type Customer struct {
	bun.BaseModel   `bun:"table:customer"`
	CustomerID      float64        `bun:"customer_id,pk"`
	CompanyID       string         `bun:"company_id,pk"`
	CustomerName    sql.NullString `bun:"customer_name"`
	CreditLimit     float32        `bun:"credit_limit"`
	CreditLimitUsed float32        `bun:"credit_limit_used"`

	Orders []*Order `bun:"rel:has-many,join:customer_id=customer_id,join_on:company_id=company_id"`
}
```

## Order
```go
type Order struct {
	bun.BaseModel        `bun:"table:oe_hdr"`
	OrderNo              string         `bun:"order_no,pk"`
	Approved             sql.NullString `bun:"approved"`
	ContactID            sql.NullString `bun:"contact_id"`
	CompanyID            string         `bun:"company_id"`
	Completed            sql.NullString `bun:"completed"`
	CustomerID           float64        `bun:"customer_id"`
	DeleteFlag           string         `bun:"delete_flag"`
	DeliveryInstructions sql.NullString `bun:"delivery_instructions"`
	OrderDate            sql.NullTime   `bun:"order_date"`
}
```

**Comment by comsma** [comment]
> @comsma could you show your models? `join:col1=col2,col3=col4` should be working fine.

Trying ```"join:col1=col2,col3=col4``` is not legal because bun requires a tag option after each comma. Bun also throws a warning stating ```has unknown tag option:"col3=col4"``` 

This means that the docs should be updated to reflect specifying that ```"join:col1=col2,join_on:col3=col4"``` is the only legal way to do a join
