### ISSUE TITLE
Running tests with unreleased version and go workspaces

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/bun#748]
To reproduce:

```shell
git checkout release/v1.1.10
go test
schema/table.go:11:2: github.com/uptrace/bun@v1.1.10: reading github.com/uptrace/bun/go.mod at revision v1.1.10: unknown revision v1.1.10
internal/hex.go:4:2: github.com/uptrace/bun@v1.1.10: reading github.com/uptrace/bun/go.mod at revision v1.1.10: unknown revision v1.1.10
schema/append_value.go:17:2: github.com/uptrace/bun@v1.1.10: reading github.com/uptrace/bun/go.mod at revision v1.1.10: unknown revision v1.1.10
```

v1.1.10 is still unreleased so the error is legit, but it used to work with `replace` directives. @goferHiro do you have any ideas?

**Comment by vmihailenco** [comment]
I've reverted go workspaces in https://github.com/uptrace/bun/commit/acb605354d39e38fb10975ac983336b9bc5b8f07

**Comment by goferHiro** [comment]
you need to release it first with alpha tags first & i.e git push it. Then do go test

**Comment by goferHiro** [comment]
which folder did u run go test on

**Comment by goferHiro** [comment]
did u try go work sync

**Comment by goferHiro** [comment]
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/103487904/213376224-ae139550-0a42-4a1b-ab69-d78a56e11bfc.png">

<img width="890" alt="image" src="https://user-images.githubusercontent.com/103487904/213376378-61df0904-b4ed-469b-b917-0e1d06c79c5c.png">

**Comment by goferHiro** [comment]
it doesn't matter what version is in the go.mod. It will use the local package not the one in GoPATH

**Comment by goferHiro** [comment]
@vmihailenco u can safely revert back to go workspaces. Do all the go tests before releasing the versions.

If u r releasing versions, then do the test after releasing the version

**Comment by vmihailenco** [comment]
Thanks, but as is go workspaces don't help with any issues I am aware of and make the release process harder. I'd rather postpone until there is a proper solution for versioning.
