### ISSUE TITLE
Any queries executed through `Exec()` returns `nil` error when zero rows affected

### ISSUE THREAD

**Issue by M0rdecay** [uptrace/bun#752]
For example:
```go
	res, err = q.NewUpdate().
		Model(&model).
		Column("owner_id", "owned_by", "shared", "title", "description", "purpose", "weight").
		Where("id = ?", m.Id).
		Returning("owner_id, owned_by, shared, title, description, purpose, weight").
		Exec(ctx)
```
In standard library raw query returns `sql.ErrNoRows` when no record with provided id was found, but Bun returns `nil`.
Looks like this is an intended behaviour for any queries, than executing by `Exec()`:
https://github.com/uptrace/bun/blob/master/hook.go#L97
```go
func (db *DB) afterQuery(
	ctx context.Context,
	event *QueryEvent,
	res sql.Result,
	err error,
) {
	switch err {
	case nil, sql.ErrNoRows:
		// nothing
........
```
But this differs from the expected and also complicates migration.
Same issue - https://github.com/uptrace/bun/issues/556

**Comment by vmihailenco** [comment]
You want to replace `Exec(ctx)` with `Scan(ctx)` which is available in v1.1.10.

>In standard library raw query returns sql.ErrNoRows when no record with provided id was found, but Bun returns nil

ErrNoRows is only returned by Scan. See [docs](https://pkg.go.dev/database/sql#pkg-variables) on ErrNoRows.
