### ISSUE TITLE
rollback can't restore deleted record

### ISSUE THREAD

**Issue by bruteforce1414** [uptrace/bun#753]
logs:
SELECT "trn"."id", "trn"."date", "trn"."type", "trn"."amount", "trn"."wallet_from", "trn"."wallet_to", "trn"."created_at", "trn"."updated_at" FROM "transactions" AS "trn" WHERE (id = 115) LIMIT 1
SELECT "trn"."id", "trn"."date", "trn"."type", "trn"."amount", "trn"."wallet_from", "trn"."wallet_to", "trn"."created_at", "trn"."updated_at" FROM "transactions" AS "trn" WHERE (id = 115) LIMIT 1
DELETE FROM "transactions" AS "trn" WHERE (id = 115)

... select request with error

ROLLBACK

**Comment by vmihailenco** [comment]
To get help, you need to provide more information and show some code. Also please use [Discussions](https://github.com/uptrace/bun/discussions) for questions.
