### ISSUE TITLE
Override default polymorphic column value

### ISSUE THREAD

**Issue by comsma** [uptrace/bun#757]
I am trying to make my bun model based of an existing database schema.
There is an existing table that has a column called TransType that contains the polymorphic key. When InventoryReceiptLine is using InvTran it is linked by an IRA key.  The problem is when using buns polymorphic relations it expects the key to be InventoryReceiptsLine which it is not. Can I override what the string is stored in the polymorphic column?

### InventoryReceiptLine
```go 
type InventoryReceiptLine struct {
	bun.BaseModel `bun:"table:inventory_receipts_line"`

	ReceiptNumber int32   `bun:"receipt_number,pk"`
	InvMastUid    int32   `bun:"inv_mast_uid"`

	OrderTransactions []*InvTran       `bun:"rel:has-many,join:inv_mast_uid=inv_mast_uid,join:type=trans_type,polymorphic"`
}
```

### InvTran
```go
type InvTran struct {
	bun.BaseModel `bun:"table:inv_tran"`

	TransactionNumber float32 `bun:"transaction_number,pk"`
	InvMastUid        int32   `bun:"inv_mast_uid"`
	TransType         string  `bun:"trans_type"`
}
```

**Comment by smyrman** [comment]
I would also very much like to be able to override the polymorphic `type` name.

Maybe instead of `type`, you could allow  static values in JOIN, as in `join:'my-type'=trans_type`?

**Comment by smyrman** [comment]
Still relevant.

**Comment by j2gg0s** [comment]
> I would also very much like to be able to override the polymorphic `type` name.
> 
> Maybe instead of `type`, you could allow static values in JOIN, as in `join:'my-type'=trans_type`?

I believe we support this feature, but it’s not reflected in the documentation.
[table.go#L688](https://github.com/uptrace/bun/blob/master/schema/table.go#L688)
```go
	polymorphicValue, isPolymorphic := field.Tag.Option("polymorphic")
...
	if isPolymorphic {
		rel.PolymorphicField = joinTable.FieldMap[polymorphicColumn]
		if rel.PolymorphicField == nil {
			panic(fmt.Errorf(
				"bun: %s has-many %s: %s must have polymorphic column %s",
				t.TypeName, field.GoName, joinTable.TypeName, polymorphicColumn,
			))
		}

		if polymorphicValue == "" {
			polymorphicValue = t.ModelName
		}
		rel.PolymorphicValue = polymorphicValue
	}
```

I verified it in the example.

```shell
diff --git a/example/rel-has-many-polymorphic/main.go b/example/rel-has-many-polymorphic/main.go
index 3478994..19f2511 100644
--- a/example/rel-has-many-polymorphic/main.go
+++ b/example/rel-has-many-polymorphic/main.go
@@ -23,7 +23,7 @@ type Article struct {
        ID   int64 `bun:",pk,autoincrement"`
        Name string

-       Comments []Comment `bun:"rel:has-many,join:id=trackable_id,join:type=trackable_type,polymorphic"`
+       Comments []Comment `bun:"rel:has-many,join:id=trackable_id,join:type=trackable_type,polymorphic:custom_type"`
 }
```
After modifying the code, the SQL becomes as follows:
```sql
SELECT "comment"."trackable_id", "comment"."trackable_type", "comment"."text" FROM "comments" AS
"comment" WHERE ("comment"."trackable_id" IN (1)) AND ("trackable_type" = 'custom_type')
```

**Comment by vmihailenco** [comment]
I've added a note to the docs: https://github.com/uptrace/bun-docs/commit/3e61083e220bb399eb1b01e61c781eb5dba3d592
