### ISSUE TITLE
Cannot insert PostgreSQL array

### ISSUE THREAD

**Issue by stefan-npo** [uptrace/bun#759]
Our use case is very similar to [this example](https://bun.uptrace.dev/postgres/postgres-arrays.html) from your documentation:

```go
type Article struct {
	ID   int64
	Tags []Tag `bun:"tags,array"`
}

type Tag struct {
	ID    string  `bun:"tag_id,nullzero"`
	Label *string `bun:"tag_label,nullzero"`
}
```

However when trying to insert a new record with a non-empty `Tags` fields we're getting
```
ERROR: syntax error at or near "{" (SQLSTATE=42601)
```
as bun generates an ambiguous query containing `{{`:

```
INSERT INTO "articles" ("id", "tags") VALUES ('article-id', '{'{"ID":"tag-id-1","Label":"tag-label-1"}','{"ID":"tag-id-2","Label":"tag-label-2"}'}')
```
Reading through your documentation it seems that one should use `pgdialect.Array` to insert arrays. However changing the insert statement to something like:

```go
tags := []Tag{{ID: "tag-id-1", Label: StringPointer("tag-label1")}, {ID: "tag-id-2", Label: StringPointer("label-id-c")}}
tx.NewInsert().Model(&article).Set("tags = ?", pgdialect.Array(tags)).Exec(db.context)
```
still results in the same error.

When changing the syntax manually as suggested [here](https://stackoverflow.com/a/35081935) the insert does work:
```
INSERT INTO "articles" ("id", "tags") VALUES ('article-id', array['{"ID":"tag-id-1","Label":"tag-label-1"}','{"ID":"tag-id-2","Label":"tag-label-2"}']::json[])
```

**Comment by svekko** [comment]
There also seems to be a problem with slice of string pointers:

`[]*string{ptr("foo"), ptr("bar")}` is converted to `'{'foo','bar'}'` that results in a syntax error.

I have some kind of a working solution that seems to resolve both issues, but I'm not really sure if it's the best solution: https://github.com/svekko/bun/commit/7c749a736f6ec574737b2cd7f1899f0a38d5e3fb
