### ISSUE TITLE
Bun - citext integration support

### ISSUE THREAD

**Issue by victormihaita** [uptrace/bun#764]
The queries generated by Bun don't work as expected in regards to case insensitivity when matching citext columns.
Is the citext type supported by Bun at the moment?  @vmihailenco 

```
type User struct {
	bun.BaseModel `bun:"table:User"`

	ID        string `bun:",pk"`
	Email     string `bun:"email,notnull,unique"` // Makes use of `citext` type/extension
```

For this email we always get back the error if we don't respect the case of each character in the email: 
```
Failed to create user with abc@abc.com: ERROR: duplicate key value violates unique constraint "User.email._UNIQUE" (SQLSTATE=23505)
```

**Comment by vmihailenco** [comment]
I don't know anything about `citext` and fail to see what Bun has to do with it.

**Comment by victormihaita** [comment]
@vmihailenco The citext module provides a case-insensitive character string type. Is an extension used for attributes at DB level which helps when comparing values. so for example: `abc@test.com` would equal `ABC@test.com`. 
After migrating to bun, this functionality stopped working for us and we started to receive the errors mentioned above.
