### ISSUE TITLE
Question: How to create a table in postgres with time column set to "timestamp without time zone"

### ISSUE THREAD

**Issue by bantl23** [uptrace/bun#769]
I define a model like so:

```
type Table struct {
	ID              uuid.UUID        `json:"id" bun:"id,pk,type:uuid"`
	CreatedAt       time.Time        `json:"created_at" bun:"created_at,nullzero,notnull,default:current_timestamp"`
	UpdatedAt       time.Time        `json:"updated_at" bun:"updated_at,nullzero,notnull,default:current_timestamp"`
}
```
And I create the table with this:
```
_, err = bundb.NewCreateTable().
	Model((*Table)(nil)).
	IfNotExists().
	Exec(context.Background())
```

Here is the resulting table schema:
```
      Column      |           Type           | Collation | Nullable |      Default
------------------+--------------------------+-----------+----------+-------------------
 id               | uuid                     |           | not null |
 created_at       | timestamp with time zone |           | not null | CURRENT_TIMESTAMP
 updated_at       | timestamp with time zone |           | not null | CURRENT_TIMESTAMP
```

How can I get the type for created_at and updated_at to say `timestamp without time zone` ?

I couldn't find anything in the documentation that mentioned options for time zone.

**Comment by svekko** [comment]
Just add `type:timestamp` to `CreatedAt` and `UpdatedAt` under `bun` tag:

`bun:"created_at,nullzero,notnull,default:current_timestamp"` -> `bun:"created_at,type:timestamp,nullzero,notnull,default:current_timestamp"`

https://bun.uptrace.dev/guide/models.html#struct-tags

**Comment by bantl23** [comment]
@svekko That worked!

However, the link provided to the struct-tags table doesn't show the `type:timestamp` type. At least I can't find it. The docs should be updated IMHO to show that explicitly.
