### ISSUE TITLE
JSONB Operators in Where

### ISSUE THREAD

**Issue by mbolt35** [uptrace/bun#798]
Is it possible to use JSONB operators in a _safe_ Where clause? For example, if I have the following table: 
```go
type book struct {
    bun.BaseModel `bun:"table:book"`
    Id            uuid.UUID              `bun:"id,type:uuid"`
    Name          string                 `bun:"name,notnull"`
    Metadata      map[string]interface{} `bun:"metadata,type:jsonb"`
}
```

I would like to write a query like the following:
```sql
SELECT id, name, metadata FROM book WHERE metadata->'tags' ? 'adventure';
```
However, the `?` operator seems to cause a problem when attempting to use a safe `.Where`:
```go
userInput := "foo" // this comes from a user, need safety

var books []*book

err := db.NewSelect().
	Model(&books).
	Column("id", "name", "metadata").
	Where("metadata->'tags' ? ?", userInput). // <-- Since '?' is a replacement marker, there are problems
	Scan(context.Background())
```

Is it possible to escape the `?` so I can use it as an operator? 

Ultimately, would love any suggestion on how to avoid sql injection risk when using/leveraging jsonb. 

Thanks for an amazing open source project!

**Comment by vmihailenco** [comment]
You can try to escape `?` with a backslash: `\?`.

**Comment by mbolt35** [comment]
> You can try to escape `?` with a backslash: `\?`.
That looks to have done it:
``````
Where("metadata->'tags' \\? ?", userInput).
```

Thanks for the response!

**Comment by Koumbaya** [comment]
Does this still work ?
I'm facing the exact same issue, but trying the code above I just get `msg: "SQL logic error: near \"?\": syntax error (1)",`

I'm trying to do this:

```
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  labels jsonb DEFAULT '{}',
  str text
);

INSERT INTO EMPLOYEE VALUES (0001, '{"superpower":null}', NULL);
INSERT INTO EMPLOYEE VALUES (0002, '{"activity":"surgeon"}', 'something');
INSERT INTO EMPLOYEE VALUES (0003, '{"superpower":"none"}', NULL);
SELECT * FROM EMPLOYEE WHERE EMPLOYEE.labels ? 'superpower' AND (EMPLOYEE.labels ->> 'superpower') IS NULL;
```
But I have no luck passing the ? into a where.
