### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by mayowa** [uptrace/bun#8]
Hello!
How do transactions work? 
In the docs I find db.Begin() and db.BeginTx() but there is no mention of db.Commit() or db.Rollback() (or equivalent functions)
I've also noticed the functions such as NewSelectQuery() do not support transactions.

Hence my question, are transactions not supported yet? or is the support there but it works in a non obvious way?
Thank you.

**Comment by vmihailenco** [comment]
Commit and Rollback are on `db.Tx` - see https://golang.org/pkg/database/sql/#example_DB_BeginTx

Once you have a tx, you have 2 options:
- `tx.NewSelectQuery()`
- `db.NewSelectQuery().Conn(tx)`

Make sure you are on v0.1.14

**Comment by mayowa** [comment]
Thank you. I'll try it and provide feedback if any (or comeback to close the issue)
