### ISSUE TITLE
Limit 0 returns all row set instead of empty set

### ISSUE THREAD

**Issue by KaitoHH** [uptrace/bun#801]
The following lines
https://github.com/uptrace/bun/blob/7cd855e64a02459579c8dd2b7bedfdc00df89cf3/query_select.go#L634-L637

causes bun omits to append `Limit 0` when selecting rows, resulting in returning all of the rows, which is not consistent with the expected empty set

**Comment by wikylyu** [comment]
I think `limit 0` is meaningless. If you want to `limit 0`, why not just return [] without selecting database.
