### ISSUE TITLE
MSSQL performance is degraded by this pull request

### ISSUE THREAD

**Issue by babashark** [uptrace/bun#824]
https://github.com/uptrace/bun/pull/768

We do not need 'N' if you are using collation Latin1_General_100_CI_AI_SC_UTF8.

Adding the 'N' make sql server failed to use index seek, caused a lot of dead lock and performance issues.

I think we should add option to use 'N' or not.

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/127459243/236183286-48399bda-73a2-4f02-bbb0-2cbefd616158.png">

**Comment by vmihailenco** [comment]
It should be fairly straightforward to add this as an option to dialect: https://github.com/uptrace/bun/blob/master/dialect/mssqldialect/dialect.go#L130-L134

**Comment by vmihailenco** [comment]
This should be a dialect-wide option, e.g.

```go
dialect := mssqldialect.New(mssqldialect.WithUnicode(false))
```
