### ISSUE TITLE
Transaction update effecting very late instead of instantly

### ISSUE THREAD

**Issue by rahulbreezo** [uptrace/bun#84]
So Our update flow is like this,

- Update 2 tables within transaction using `RunInTx`
```
transactionOptions := sql.TxOptions{Isolation: 0, ReadOnly: false}

if err := db.RunInTx(ctx, &transactionOptions, transactionFunc); err != nil {
		return User{}, errors.Wrap(err, errors.UpdatingUserException)
	}
```

- Then a GetUser call to function , that  makes get query and returns updated user.

Most of the time it works  good but sometime unexpectedly it does not return updated field but returns old value even after update transaction ran fine as after this making a `GET` API call returns correct response.

We had similiar flow before using this ORM but never face this issue before, so I am guessing its something related to ORM.

Note:  we have diff  read and write connections for same db.

@vmihailenco

**Comment by vmihailenco** [comment]
Please provide a reproducer, but Bun just wraps `sql.Tx` so there is no much that can go wrong. If you are using pdriver, you can try to replace pgdriver with pgx and see if the problem goes away.

**Comment by rahulbreezo** [comment]
okay , it could be because of pg driver cause last time we were using pgx and it was working fine, will try

**Comment by rahulbreezo** [comment]
1 out of 20 times is still failing , could it be because of isolation level? Should I change it to  3 manually? Actually I also could not reproduce this in local, its happening only on staging where read and write connections are different.

**Comment by vmihailenco** [comment]
It is not clear what do you expect, but generally transaction only sees changes made within the transaction. If you make changes in another transaction, then it becomes complicated (meaning I don't know :)

**Comment by rahulbreezo** [comment]
I am closing this cause it seems unrelated to `bun`,
