### ISSUE TITLE
`bun.UpdateQuery`'s `.Set` method causes any other model fields to be ignored

### ISSUE THREAD

**Issue by ardenn** [uptrace/bun#862]
Updates to a model's fields appear to be ignored whenever `.Set` is used on the query even when I add `.Column`.
I often update a table through the model struct (`account.UpdatedAt = time.Now()`), but also set some fields using a query like (`q.Set("update_count = update_count + 1")`). Only the fields set with `.Set` get updated. Is this by design? I remember being able to do this with `go-pg`.

Example:
```golang
account.UpdatedAt = time.Now()
_, err := db.NewUpdate().Model(&account).WherePK().
	Column("updated_at","update_count").Set("update_count = update_count + 1").
	OmitZero().Returning("*").Exec(ctx)
```
generates the query:
`UPDATE account SET update_count = update_count + 1 ...`

instead of
`UPDATE account SET updated_at = '2023-07-08T08:51:27.217Z' , update_count = update_count + 1 ...`

**Comment by ardenn** [comment]
Based on [this](https://github.com/uptrace/bun/blob/838a3bce1805234d25d90c87a75591f2377d3bf3/query_update.go#L261) and [this](https://github.com/uptrace/bun/blob/838a3bce1805234d25d90c87a75591f2377d3bf3/query_update.go#L265) it looks like `.Set` and updating model struct fields are mutually exclusive - we return early as soon as `len(q.set) > 0`. Any chance of combining the two update sources?

**Comment by qindj** [comment]
#647
