### ISSUE TITLE
Documentation for relationship should include base model

### ISSUE THREAD

**Issue by robvdl** [uptrace/bun#864]
Ran into issues following this: https://bun.uptrace.dev/guide/relations.html#many-to-many-relation

It's missing the bun.BaseModel struct embed on the bridge table as (and other tables too). Ran into an error about "please register models" even though I was.

The issue was that the docs need to embed bun.BaseModel in those models and then it works fine.

Just needs a documentation fixup.

**Comment by codeliger** [comment]
I also mentioned this in #882
