### ISSUE TITLE
Postgres migration fails with ERROR: null value in column "id" violates not-null constraint

### ISSUE THREAD

**Issue by oba2cat3** [uptrace/bun#873]
Problem: Cannot migrate using bun migrate package with Postgres database (Docker postgres:12), using sqlitedialect.
Expected: Migrations to work.

Details:
I cannot use bun to add a column in my database - it fails with this error:
INSERT INTO bun_migrations ("name", "group_id", "migrated_at") VALUES ('2023', 1, current_timestamp) RETURNING "id", "migrated_at"        pgdriver.Error: ERROR: null value in column "id" violates not-null constraint (SQLSTATE=23502)

I have a single migration block that looks like this:
```
	migration := migrate.Migration{
		ID:      0,
		Name:    "2023",
		Comment: "add_report",
		Up: func(ctx context.Context, db *bun.DB) error {
			fmt.Print(" [up migration] ")
			return nil
		},
		Down: func(ctx context.Context, db *bun.DB) error {
			fmt.Print(" [down migration] ")
			return nil
		},
	}
	Migrations.Add(migration)
```
This is not a standard code from the examples. I adapted it to investigate the problem.
The migration Object definition looks like this. The problem is in the ID field.
```
type Migration struct {
	bun.BaseModel

	ID         int64 `bun:",pk,autoincrement"`
	Name       string
	Comment    string `bun:"-"`
	GroupID    int64
	MigratedAt time.Time `bun:",notnull,nullzero,default:current_timestamp"`

	Up   MigrationFunc `bun:"-"`
	Down MigrationFunc `bun:"-"`
}
```

my Migrate call fail on this call, and generates the error.
```
func (m *Migrator) MarkApplied(ctx context.Context, migration *Migration) error {
	_, err := m.db.NewInsert().Model(migration).
		ModelTableExpr(m.table).
		Exec(ctx)
	return err
}
```

Reason: the ID field is 0, which maps to Zero/Null value.
Trying to set the ID to 1, will mark the migration as done, in the IsApplied method:
```
func (m Migration) IsApplied() bool {
	return m.ID > 0
}
```

**Comment by ikkerens** [comment]
So I can into a similar issue here and found that it was because the table in question wasn't using the PG Serial type for its primary key, so it would never increment.

After a bit of digging, I did find that Bun does support this, and the error was my own:
My db wasn't using `pgdialect.New()`, instead it was still using `sqlitedialect.New()`

Maybe you're running into a different issue here, but that what was solved it for me.
