### ISSUE TITLE
contribution proposal: buncli, a commandline to interact with db through bun definitions

### ISSUE THREAD

**Issue by aep** [uptrace/bun#875]
Hi

we have a hand written cli to manage objects in bun.
i realized in another project that this could just be autogenerated with reflect.

should we contribute something like this?

here's an idea how that could look like:

https://github.com/kraudcloud/buncli

https://github.com/uptrace/bun/assets/136926/6910be88-bd4e-439f-beef-1bd98d58314c

**Comment by vmihailenco** [comment]
Hey,

If you mean generating SQL tables from Bun models, then we have [this issue](https://github.com/uptrace/bun/issues/456) with some discussion.

The consensus is that yes, we want it, but none is brave enough so far to do all the hard work :) I guess most people are happy enough to write migrations by hand.

**Comment by vmihailenco** [comment]
@aep could you remind me if https://github.com/kraudcloud/buncli was a thing? @bevzzz was kind enough to complete AutoMigrator so we definitely need a CLI now.

**Comment by aep** [comment]
Ah no sorry. Never really went anywhere. :(
