### ISSUE TITLE
SQLite: Creating a table from a model is not respecting autoincrement for primary keys

### ISSUE THREAD

**Issue by jeffreydwalter** [uptrace/bun#878]
I have the following model:
```
type Product struct {
	ID           int64 `bun:",pk,autoincrement"`
	Val         string
}

sqldb, err := sql.Open(sqliteshim.ShimName, "file:sqllite.db?cache=shared")
if err != nil {
panic(err)
}
defer sqldb.Close()

db = bun.NewDB(sqldb, sqlitedialect.New())

// Register the Product structs with bun
db.RegisterModel((*Product)(nil))

if err := db.ResetModel(context.Background(), (*Product)(nil)); err != nil {
panic(err)
}
```

It produces the following SQL:
```
CREATE TABLE "products" ("id" INTEGER NOT NULL, "val" VARCHAR, PRIMARY KEY ("id"))
```

It should produce:
```
CREATE TABLE "products" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "val" VARCHAR);
```

I also tried with just `bun:",pk`, which didn't add `AUTOINCREMENT` either.

After more debugging, the problem seems to be with the sqlitedialect. If I print the return value of `db.Dialect().Features().Has(feature.AutoIncrement)` it returns false.
```
fmt.Printf("AUTOINCREMENT: %t\n", db.Dialect().Features().Has(feature.AutoIncrement))

$ go run sqlite.go 
AUTOINCREMENT: false
 ```

**Comment by codeliger** [comment]
> On an [INSERT](https://www.sqlite.org/lang_insert.html), if the ROWID or INTEGER PRIMARY KEY column is not explicitly given a value, then it will be filled automatically with an unused integer, usually one more than the largest ROWID currently in use. This is true regardless of whether or not the AUTOINCREMENT keyword is used.

https://www.sqlite.org/autoinc.html

Did you try inserting data? I am assuming it will auto-increment anyway.

**Comment by jeffreydwalter** [comment]
Not sure what it was, but I ended up getting it working.

**Comment by jeffwalter-rum** [comment]
Just to provide more context here, auto-incrementing does NOT work with sqlite3 unless I explicitly add "autoincrement" to the id column.
