### ISSUE TITLE
Wrong float value when using pgdriver

### ISSUE THREAD

**Issue by karolsarnacki** [uptrace/bun#88]
Hi,

I'm getting strange results with pgdriver when reading float values from the database. Eg. when I try to read `1.1` value, what I get is `1.100000023841858`. The results are similarly wrong with different floating point numbers that cannot be precisely represented in binary system.

The test below fails with the message `got: 1.100000023841858, want: 1.1`:

```go
func TestBunPgdriver(t *testing.T) {
	sqlDB := sql.OpenDB(pgdriver.NewConnector(pgdriver.WithDSN("postgres://postgres@localhost:5432/postgres?sslmode=disable")))
	db := bun.NewDB(sqlDB, pgdialect.New())

	var f float64
	db.QueryRow("SELECT 1.1::float AS f").Scan(&f)
	if f != 1.1 {
		t.Fatalf("got: %g, want: %g", f, 1.1)
	}
}
```

I've tested the same query with Gorm, go-pg, Bun (pgdriver), Bun (pgx) and Bun (pgx with simple protocol). I am getting wrong results only with Bun+pgdriver - all other ORMs/drivers return `1.1`.

System: macOS Big Sur 11.2.3
DB: PostgreSQL 13.3
Go: 1.16.6
Bun: 0.3.8

I've added a gist with the tests: https://gist.github.com/karolsarnacki/5078e9ed4731e4209dc728e828972922

**Comment by vmihailenco** [comment]
Thanks for the report - should be fixed in v0.3.9
