### ISSUE TITLE
Has many self relationship throwing error

### ISSUE THREAD

**Issue by garthreckers** [uptrace/bun#884]
This may be a similar to [this issue](https://github.com/uptrace/bun/issues/158) but when I try to do a has-many relationship that references the same model, it won't work if the parent field is a pointer (edit: used to say non-pointer but should have said pointer).

This is the non-working code:

``` go
type (
	Category struct {
		bun.BaseModel `bun:"category,alias:category"`

		ID          uint        `bun:"id,pk,autoincrement" json:"id"`
		Name        string      `bun:"name" json:"name"`
		ParentID    *uint       `bun:"parent" json:"parent_id"`
		CreatedAt   *time.Time  `bun:"created_at" json:"created_at"`
		UpdatedAt   *time.Time  `bun:"updated_at" json:"updated_at"`
		AllChildren []*Category `bun:"rel:has-many,join:id=parent" json:"all_children,omitempty"`
	}
)

func ListCategories() []Category {
	var categories []Category

	db.GetDB().
		NewSelect().
		Model(&categories).
		Relation("AllChildren").
		Where("parent IS NULL").
		Order("name ASC").
		Scan(context.TODO())

	return categories
}
```

The above code will return the parent categories without the children. If I check the logs, I see this error:

```
SELECT `category`.`id`, `category`.`name`, `category`.`parent`, `category`.`created_at`, `category`.`updated_at` FROM `category` WHERE (`category`.`parent` IN (4, 7, 15, 1))      *errors.errorString: bun: has-many relation=AllChildren does not have base model=Category with id=[%!q(*uint=0x400035ab58)] (check join conditions)
```

If I replace the ParentID with a non-pointer uint and run the code, it works as expected with the parents at the top level and the nested AllChildren.

``` go
type (
	Category struct {
		bun.BaseModel `bun:"category,alias:category"`

		ID          uint        `bun:"id,pk,autoincrement" json:"id"`
		Name        string      `bun:"name" json:"name"`
		ParentID    uint        `bun:"parent" json:"parent_id"`
		CreatedAt   *time.Time  `bun:"created_at" json:"created_at"`
		UpdatedAt   *time.Time  `bun:"updated_at" json:"updated_at"`
		AllChildren []*Category `bun:"rel:has-many,join:id=parent" json:"all_children,omitempty"`
	}
)

func ListCategories() []Category {
	var categories []Category

	db.GetDB().
		NewSelect().
		Model(&categories).
		Relation("AllChildren").
		Where("parent IS NULL").
		Order("name ASC").
		Scan(context.TODO())

	return categories
}
```

Am I missing something?

I tried the duplicate struct that the above issue (they did Message and MessageX) and could get it to work that way but that's not really ideal.

**Comment by codeliger** [comment]
i think you forgot a `,` before your relationship. You are setting the ID of your column to `rel:has-many`

change:
`AllChildren []*Category `bun:"rel:has-many,join:id=parent" json:"all_children,omitempty"``
to:
`AllChildren []*Category `bun:",rel:has-many,join:id=parent" json:"all_children,omitempty"``

**Comment by garthreckers** [comment]
@codeliger - Doesn't look like its necessary for a relationship. I have a lot of other working relationships without the leading comma and the documentation doesn't include it: https://bun.uptrace.dev/guide/relations.html#has-many-relation

Thanks for the suggestion though.

**Comment by codeliger** [comment]
Have you tried renaming AllChildren to Categories, or specifying a table name in the definition? 

I think the reason there is no table name defined is because it derives it from `Profiles []*Profile `bun:"rel:has-many,join:id=user_id"`

**Comment by e200** [comment]
Same situation here. In my case, the **has-many** relation SQL is simply not being generated. You can see the main SQL being generated and executed but no relation is loaded and the field is null.

**Comment by taoberquer** [comment]
Has anyone found a solution? I have the same problem :/
