### ISSUE TITLE
Is Bun docs project public? Can I subscribe to it?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bun#9]
I'm switching to Bun (from go-pg) and I would like to follow all the news in the documentation, but I can't find the docs in Github. Is the source public? So I can subscribe to any news.

**Comment by frederikhors** [comment]
I?m referring to the pages on bun.uptrace.dev.

**Comment by vmihailenco** [comment]
Documentation is not public yet. I will update this issue once it's ready.

**Comment by vmihailenco** [comment]
Docs are available at https://github.com/go-bun/bun-docs

**Comment by oderwat** [comment]
> Docs are available at https://github.com/go-bun/bun-docs

This ends up in 404
