### ISSUE TITLE
Calling Update on an empty model creates malformed query

### ISSUE THREAD

**Issue by mojtabacazi** [uptrace/bun#90]
Given:

```
type Book struct {
    ID int64

    name *string
}

book := Book{
    ID: 1,
}

```

trying to update the model without any values generates an invalid query 
```
db.NewUpdate().Model(&book).Where("id = ?", book.ID).Exec(ctx)

=> 'UPDATE "books" AS "book" SET  WHERE (id = 1)'
```

The same issue exists in go-pg as well.

**Comment by vmihailenco** [comment]
What do you expect instead?

**Comment by d-fal** [comment]
this is the expected result!

**Comment by vmihailenco** [comment]
Perhaps you meant to write `Name *string` so the field is exported

```go
type Book struct {
    ID int64

    Name *string
}
```

We could check number of fields but it is not clear what that improves. Closing for now.
