### ISSUE TITLE
Omitzero not working with NewUpdate SET

### ISSUE THREAD

**Issue by soheeeeP** [uptrace/bun#906]
According to the docs, `Omitzero` for `NewUpdate` is to update columns only when it does not contain an empty value. but it seems to work properly only when using a struct object (not working when using the`Set` method)

``` go
type User struct {
	ID                 int64  `bun:",pk,autoincrement"`
	Description        string `bun:"type:text,nullzero,notnull"`
	Count              int64          `bun:"default:0,notnull,nullzero"`
}
```
Example of a struct object which contains an empty value: it works
 ``` go
updateUser := &model.User{
	ID:          ID,
	Count:              count,
}

if _, err := db.NewUpdate().Model(updateUser).
	OmitZero().WherePK().Returning("*").Exec(ctx); err != nil {
	return nil, err
}
```

Example of using `Set` method in order to define fields to update:
 ``` go
var updateUser *model.User
if _, err := db.NewUpdate().Model(&updateUser).
        Set("count = ?", count) 
	OmitZero().WherePK().Returning("*").Exec(ctx); err != nil {
	return nil, err
}
 ```

As `Golang` uses zero value as nil for integer and float, the `count` field must not be included in the update query but it generates the query like: `UPDATE "user" AS "user" SET count = 0 WHERE (id = 'id' ) RETURNING *`
which seems `OmitZero` option is not properly applied for the empty integer value.

Is this by design or an issue?

**Comment by nb-park** [comment]
This is still an issue. Found in my case because `OmitZero` isn't checked when doing a `Bulk` update.
