### ISSUE TITLE
How to write foreign key UUID?

### ISSUE THREAD

**Issue by Kolobamanacas** [uptrace/bun#91]
Let's say, I have two models `User` and `Group`:

```go
type User struct {
	ID    uuid.UUID  `bun:"type:uuid,default:uuid_generate_v4()" json:"id"`
	Name  string     `json:"name"`
	Group *Group     `bun:"rel:belongs-to" json:"group"`
}

type Group struct {
	ID uuid.UUID `bun:"type:uuid,default:uuid_generate_v4()" json:"id"`
}
```

Every user could have or not have a group, i.e. `group_id` in DB accepts `NULL`. Also all groups are already exist in DB, so I only add users to DB (again with or without a group).

I get a user from a client side in a JSON like

```json
{
  "id": "SomeGuid",
  "name": "SomeString",
  "group": {
    "id": "SomeString"
  }
}
```

The question is: how do I save `User` to DB with `group_id` set to `User.Group.ID`?

- Saving it as it is, leads to `group_id` is set to `NULL` even if group is presented in received JSON.
- I've added `GroupId` to `User's` model and setting in manually with `user.GroupId = user.Group.ID` partly solves the issue, but fails when `User` has no `Group` in JSON.
- The only way it works as I expect is when I manually set `.Column()`, but in this case I have to run different queries for cases when `Group` is presented and when it's not. And it seems like very odd solution, especially when more nullable fields are added to a model (i.e. for 2 fields it's 4 cases, for 3 it's 6, etc.).

What is the right way to accomplish such a task?

p.s. Sorry, I didn't find a better place to ask a question as the project is still not that widespread.

**Comment by vmihailenco** [comment]
The code should be

```go
type User struct {
	ID    uuid.UUID  `bun:"type:uuid,default:uuid_generate_v4()" json:"id"`
	Name  string     `json:"name"`
	Group *Group     `bun:"rel:belongs-to" json:"group"`
        GroupID uuid.UUID
}

type Group struct {
	ID uuid.UUID `bun:"type:uuid,default:uuid_generate_v4()" json:"id"`
}
```

Then you make 2 inserts:
- first insert the group getting the group.ID
- set `user.GroupID = group.ID` and insert the user

And it is best to use [discussions](https://github.com/uptrace/bun/discussions) for questions.

**Comment by Arcayr** [comment]
Apologies for bumping a closed issue, however I felt the question was directly related.

Would it be within the vision of Bun to detect "GroupUUID" in this particular example, as the UUID field to reference on?

For my schema, I'm using "uuid" as the column name for the primary key, and "xxx_uuid" as the foreign key reference.

**Comment by vmihailenco** [comment]
@Arcayr yes, if your primary key is named `UUID`, e.g.

```
type User struct {
	UUID    uuid.UUID  `bun:"type:uuid,default:uuid_generate_v4()" json:"id"`
	Name  string     `json:"name"`
	Group *Group     `bun:"rel:belongs-to" json:"group"`
        GroupUUID uuid.UUID
}

type Group struct {
	UUID uuid.UUID `bun:"type:uuid,default:uuid_generate_v4()" json:"id"`
}
```

If it does not work, please open an issue.
