### ISSUE TITLE
no transactional migrations support

### ISSUE THREAD

**Issue by user3160** [uptrace/bun#924]
It seems there is no transactional migrations support like we had in go-pg with MustRegisterTx().

Even if I create my own transaction inside migration, when it gets rolled back, the metadata in DB table bun_migrations is still stored as if the migration was sucessfull.

**Comment by zavitkov** [comment]
great question!
it would be great to have an opportunity to run migrations in transaction, so if any step of migration fails, it automatically rollbacks previously applied changes and there is no new records in bun_migrations table.
