### ISSUE TITLE
pgdriver.WithDSN panic when password contains a '#' and at least one letter before '#'

### ISSUE THREAD

**Issue by zhuyanxi** [uptrace/bun#935]
My PostgreSQL's password has a character '#'
(my dsn sample:  `postgres://postgres:1A#34@localhost:5432/postgres?sslmode=disable`)

And I see pgdriver.WithDSN calls url.Parse() which will cause this error: `parse "postgres://postgres:1A": invalid port ":1A" after host`

The panic stack is: 
```shell
panic: parse "postgres://postgres:1A": invalid port ":1A" after host

goroutine 1 [running]:
github.com/uptrace/bun/driver/pgdriver.WithDSN.func1(0xc0001ad040)
	C:/Users/yxzhu/go/pkg/mod/github.com/uptrace/bun/driver/pgdriver@v1.1.16/config.go:191 +0x1d2
github.com/uptrace/bun/driver/pgdriver.NewConnector({0xc00051dc28, 0x1, 0x1})
	C:/Users/yxzhu/go/pkg/mod/github.com/uptrace/bun/driver/pgdriver@v1.1.16/driver.go:76 +0xf1
```

**Comment by bevzzz** [comment]
As [per documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS), the DSN should be a valid URL:

> The connection URI needs to be encoded with [percent-encoding](https://tools.ietf.org/html/rfc3986#section-2.1) if it includes symbols with special meaning in any of its parts. Here is an example where the equal sign (=) is replaced with %3D and the space character with %20:

There are many [guides online](https://golang.cafe/blog/how-to-url-encode-string-in-golang-example.html) and this simple change should fix your issue:

```go
pgdriver.WithDSN(fmt.Sprintf("postgres://postgres:%s@localhost:5432/postgres?sslmode=disable", url.QueryEscape(password)))
```

IMO, ensuring the validity of the URL should be the client code's responsibility.

**Comment by zhuyanxi** [comment]
> As [per documentation](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS), the DSN should be a valid URL:
> 
> > The connection URI needs to be encoded with [percent-encoding](https://tools.ietf.org/html/rfc3986#section-2.1) if it includes symbols with special meaning in any of its parts. Here is an example where the equal sign (=) is replaced with %3D and the space character with %20:
> 
> There are many [guides online](https://golang.cafe/blog/how-to-url-encode-string-in-golang-example.html) for URL-encoding a string in Golang and this simple change should fix your issue:
> 
> ```go
> password := "invalid#pwd"
> pgdriver.WithDSN(fmt.Sprintf("postgres://postgres:%s@localhost:5432/postgres?sslmode=disable", url.QueryEscape(password)))
> ```
> 
> IMO, ensuring the validity of the URL should be the client code's responsibility.

Oh, sorry, I made a stupid mistake. I forgot to escape the dsn string. 
Everything is fine now, thank you so much. Wish you a good day.

**Comment by betrok** [comment]
I feel like there should be safe way to check/use DSN without panic.

Maybe just export parseDSN function so users can check error on theirs end.

**Comment by bevzzz** [comment]
> I feel like there should be safe way to check/use DSN without panic.
Maybe just export parseDSN function so users can check error on theirs end.

@betrok here `parseDSN` panics because the URL passed by the user is an invalid one. The underlying error is returned by `url.Parse`, as can be seen in [this example](https://go.dev/play/p/hGDGyzktC1H).
There are several things one can already do to avoid the panic:
-  always URL-encoding their DSN
- in case there's a preferred way of handling it, check for the error with `_, err := url.Parse(dsn)` before passing the DSN along
- pass all parameters via dedicated functional options (see an example from the [docs](https://bun.uptrace.dev/postgres/#pgdriver) below)

```go
pgconn := pgdriver.NewConnector(
	pgdriver.WithNetwork("tcp"),
	pgdriver.WithAddr("localhost:5437"),
	pgdriver.WithTLSConfig(&tls.Config{InsecureSkipVerify: true}),
	pgdriver.WithUser("test"),
	pgdriver.WithPassword(`^_^Sp00kyP@$$w0rd#`),  // <-- invalid URL characters here
	pgdriver.WithDatabase("test"),
)
```

**Comment by betrok** [comment]
There are more situations where parseDSN can return error leading to panic other than straight up invalid URL, including certificate verification.
