### ISSUE TITLE
Composite primary keys?

### ISSUE THREAD

**Issue by tschellenbach** [uptrace/bun#94]
Are composite primary keys supported? They are not mentioned in the docs but are available in go-pg

**Comment by j2gg0s** [comment]
I think it's ok, example in test: https://github.com/uptrace/bun/blob/master/internal/dbtest/orm_test.go#L293

**Comment by vmihailenco** [comment]
Yes, composite keys are supported. See the [migration guide](https://bun.uptrace.dev/guide/pg-migration.html#new-features) for the list of changes.
