### ISSUE TITLE
How to handle logical names of columns that are too long?

### ISSUE THREAD

**Issue by iwashi623** [uptrace/bun#962]
There is a restriction that the string used for AS in PostgresQL must be less than 63 bytes.
https://www.postgresql.org/docs/current/runtime-config-preset.html#GUC-MAX-IDENTIFIER-LENGTH

In bun, logical names used in AS are generated in a format such as `table_name__column_name`. Logical names exceeding 63 bytes are truncated on the PostgresQL side.

ex:  Query Results `hoge__bar__piyo__wai__foo__buz__fizz__tic__fuga__boo__column_name` -> `hoge__bar__piyo__wai__foo__buz__fizz__tic__fuga__boo__column_na`

In this example, the result of the query returned from Postgres has the trailing two ``me`` characters cut off, so the column/struct mapping does not work on the bun side, resulting in the following error
```
bun: model=hoge does not have column=hoge__bar__piyo__wai__foo__buz__fizz__tic__fuga__boo__column_na
```

How can I resolve this one?

**Comment by codeliger** [comment]
This is a huge issue. Even adding aliases to models doesn't seem to solve the problem. The aliases are not used.

**Comment by kiharakarua** [comment]
Any workarounds for this?

**Comment by codeliger** [comment]
Anything about this?

**Comment by john8329** [comment]
This makes using `.Relation()` completely useless for tables with reasonable column names and sub-entities. I switched to having my layer over the ORM perform extra queries. Inefficient, but works.

A reasonable workaround would be manually defining aliases for related tables like:
```go
CustomizedForClient   *Contact `bun:"rel:belongs-to,join:customized_for_client_id=id,alias:cfc"`
```
but it's not implemented so far.
