### ISSUE TITLE
Ambiguous Column Reference Id

### ISSUE THREAD

**Issue by zgunz42** [uptrace/bun#990]
```go

func (r *EmailMessageRepository) GetByID(ctx context.Context, id int) (*model.EmailMessage, error) {
	message := new(model.EmailMessage)
	err := r.db.NewSelect().Model(message).Where("id = ?", id).Relation("Events").Relation("Account").Scan(ctx)
	return message, err
}
```

## Error Msg
pgdriver.Error {m: map[uint8]string [83: "ERROR", 86: "ERROR", 67: "42702", 77: "column reference \"id\" is ambiguous", 80: "619", 70: "parse_relation.c", 76: "831", 82: "scanRTEForColumn", ]}

**Comment by khanakia** [comment]
@zgunz42 how did you solve the issue ?

I could solve it using prefix the table name in where like this `email_messages.id = 11`

**Comment by zgunz42** [comment]
@khanakia I create MySQL function to remove generate index so for example remove index with suffix _num somehow temporary solve the problem
